// Generated by CIRCT firtool-1.62.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for prints and assertions.

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module AXI4DummySD(	// src/main/scala/device/AXI4DummySD.scala:68:7
  input         clock,	// src/main/scala/device/AXI4DummySD.scala:68:7
                reset,	// src/main/scala/device/AXI4DummySD.scala:68:7
  output        io_in_awready,	// src/main/scala/device/AXI4Slave.scala:28:14
  input         io_in_awvalid,	// src/main/scala/device/AXI4Slave.scala:28:14
  input  [31:0] io_in_awaddr,	// src/main/scala/device/AXI4Slave.scala:28:14
  output        io_in_wready,	// src/main/scala/device/AXI4Slave.scala:28:14
  input         io_in_wvalid,	// src/main/scala/device/AXI4Slave.scala:28:14
  input  [63:0] io_in_wdata,	// src/main/scala/device/AXI4Slave.scala:28:14
  input  [7:0]  io_in_wstrb,	// src/main/scala/device/AXI4Slave.scala:28:14
  input         io_in_bready,	// src/main/scala/device/AXI4Slave.scala:28:14
  output        io_in_bvalid,	// src/main/scala/device/AXI4Slave.scala:28:14
                io_in_arready,	// src/main/scala/device/AXI4Slave.scala:28:14
  input         io_in_arvalid,	// src/main/scala/device/AXI4Slave.scala:28:14
  input  [31:0] io_in_araddr,	// src/main/scala/device/AXI4Slave.scala:28:14
  input         io_in_rready,	// src/main/scala/device/AXI4Slave.scala:28:14
  output        io_in_rvalid,	// src/main/scala/device/AXI4Slave.scala:28:14
  output [63:0] io_in_rdata	// src/main/scala/device/AXI4Slave.scala:28:14
);

  wire        io_in_arready_0;	// src/main/scala/device/AXI4Slave.scala:71:29
  wire [31:0] _sdHelper_data;	// src/main/scala/device/AXI4DummySD.scala:114:24
  wire        _sdHelper_io_ren_T_2 = io_in_arready_0 & io_in_arvalid;	// src/main/scala/chisel3/util/Decoupled.scala:51:35, src/main/scala/device/AXI4Slave.scala:71:29
  reg         r_busy;	// src/main/scala/utils/StopWatch.scala:24:20
  assign io_in_arready_0 = io_in_rready | ~r_busy;	// src/main/scala/device/AXI4Slave.scala:71:{29,32}, src/main/scala/utils/StopWatch.scala:24:20
  reg         ren_REG;	// src/main/scala/device/AXI4Slave.scala:73:17
  reg         io_in_rvalid_r;	// src/main/scala/utils/StopWatch.scala:24:20
  reg         w_busy;	// src/main/scala/utils/StopWatch.scala:24:20
  wire        io_in_wready_0 = io_in_awvalid | w_busy;	// src/main/scala/device/AXI4Slave.scala:95:30, src/main/scala/utils/StopWatch.scala:24:20
  wire        _io_in_bvalid_T_1 = io_in_wready_0 & io_in_wvalid;	// src/main/scala/chisel3/util/Decoupled.scala:51:35, src/main/scala/device/AXI4Slave.scala:95:30
  reg         io_in_bvalid_r;	// src/main/scala/utils/StopWatch.scala:24:20
  reg  [31:0] regs_0;	// src/main/scala/device/AXI4DummySD.scala:72:43
  reg  [31:0] regs_1;	// src/main/scala/device/AXI4DummySD.scala:72:43
  reg  [31:0] regs_4;	// src/main/scala/device/AXI4DummySD.scala:72:43
  reg  [31:0] regs_5;	// src/main/scala/device/AXI4DummySD.scala:72:43
  reg  [31:0] regs_6;	// src/main/scala/device/AXI4DummySD.scala:72:43
  reg  [31:0] regs_7;	// src/main/scala/device/AXI4DummySD.scala:72:43
  reg  [31:0] regs_8;	// src/main/scala/device/AXI4DummySD.scala:72:43
  reg  [31:0] regs_15;	// src/main/scala/device/AXI4DummySD.scala:72:43
  reg  [31:0] regs_20;	// src/main/scala/device/AXI4DummySD.scala:72:43
  wire [3:0]  strb =
    io_in_awaddr[2] ? io_in_wstrb[7:4] : io_in_wstrb[3:0];	// src/main/scala/device/AXI4DummySD.scala:138:{22,28,47,68}
  wire [31:0] _GEN = {{8{strb[3]}}, {8{strb[2]}}, {8{strb[1]}}, {8{strb[0]}}};	// src/main/scala/device/AXI4DummySD.scala:138:22, src/main/scala/utils/BitUtils.scala:27:{26,29,45}
  wire        _GEN_0 = _io_in_bvalid_T_1 & io_in_awaddr[12:0] == 13'h0;	// src/main/scala/chisel3/util/Decoupled.scala:51:35, src/main/scala/device/AXI4DummySD.scala:135:35, src/main/scala/utils/LookupTree.scala:24:34, src/main/scala/utils/RegMap.scala:32:{32,41}
  wire [31:0] _regs_0_T_3 = io_in_wdata[31:0] & _GEN | regs_0 & ~_GEN;	// src/main/scala/device/AXI4DummySD.scala:72:43, :141:48, src/main/scala/utils/BitUtils.scala:27:26, :34:{14,26,37,39}
  wire        _regs_0_T_4 = _regs_0_T_3[5:0] == 6'h1;	// src/main/scala/device/AXI4DummySD.scala:84:20, :85:18, src/main/scala/utils/BitUtils.scala:34:26
  wire        _regs_0_T_5 = _regs_0_T_3[5:0] == 6'h2;	// src/main/scala/device/AXI4DummySD.scala:84:20, :85:18, src/main/scala/utils/BitUtils.scala:34:26
  wire        _regs_0_T_6 = _regs_0_T_3[5:0] == 6'h9;	// src/main/scala/device/AXI4DummySD.scala:84:20, :85:18, src/main/scala/utils/BitUtils.scala:34:26
  wire        _regs_0_T_7 = _regs_0_T_3[5:0] == 6'hD;	// src/main/scala/device/AXI4DummySD.scala:84:20, :85:18, src/main/scala/utils/BitUtils.scala:34:26
  reg  [63:0] io_in_rdata_REG;	// src/main/scala/device/AXI4DummySD.scala:144:44
  reg  [63:0] io_in_rdata_r;	// src/main/scala/device/AXI4DummySD.scala:144:36
  always @(posedge clock) begin	// src/main/scala/device/AXI4DummySD.scala:68:7
    automatic logic [31:0] _rdata_T_23;	// src/main/scala/chisel3/util/Mux.scala:30:73
    _rdata_T_23 =
      (io_in_araddr[12:0] == 13'h0 ? regs_0 : 32'h0)
      | (io_in_araddr[12:0] == 13'h38 ? regs_15 : 32'h0)
      | (io_in_araddr[12:0] == 13'h18 ? regs_6 : 32'h0);	// src/main/scala/chisel3/util/Mux.scala:30:73, src/main/scala/device/AXI4DummySD.scala:72:43, :135:35, src/main/scala/utils/LookupTree.scala:24:34
    if (reset) begin	// src/main/scala/device/AXI4DummySD.scala:68:7
      r_busy <= 1'h0;	// src/main/scala/utils/StopWatch.scala:24:20
      ren_REG <= 1'h0;	// src/main/scala/device/AXI4Slave.scala:73:17, src/main/scala/utils/StopWatch.scala:24:20
      io_in_rvalid_r <= 1'h0;	// src/main/scala/utils/StopWatch.scala:24:20
      w_busy <= 1'h0;	// src/main/scala/utils/StopWatch.scala:24:20
      io_in_bvalid_r <= 1'h0;	// src/main/scala/utils/StopWatch.scala:24:20
      regs_0 <= 32'h0;	// src/main/scala/device/AXI4DummySD.scala:72:43
      regs_1 <= 32'h0;	// src/main/scala/device/AXI4DummySD.scala:72:43
      regs_4 <= 32'h0;	// src/main/scala/device/AXI4DummySD.scala:72:43
      regs_5 <= 32'h0;	// src/main/scala/device/AXI4DummySD.scala:72:43
      regs_6 <= 32'h0;	// src/main/scala/device/AXI4DummySD.scala:72:43
      regs_7 <= 32'h0;	// src/main/scala/device/AXI4DummySD.scala:72:43
      regs_8 <= 32'h0;	// src/main/scala/device/AXI4DummySD.scala:72:43
      regs_15 <= 32'h0;	// src/main/scala/device/AXI4DummySD.scala:72:43
      regs_20 <= 32'h0;	// src/main/scala/device/AXI4DummySD.scala:72:43
    end
    else begin	// src/main/scala/device/AXI4DummySD.scala:68:7
      automatic logic _io_in_rvalid_T_3;	// src/main/scala/chisel3/util/Decoupled.scala:51:35
      automatic logic _io_in_bvalid_T_2;	// src/main/scala/chisel3/util/Decoupled.scala:51:35
      _io_in_rvalid_T_3 = io_in_rready & io_in_rvalid_r;	// src/main/scala/chisel3/util/Decoupled.scala:51:35, src/main/scala/utils/StopWatch.scala:24:20
      _io_in_bvalid_T_2 = io_in_bready & io_in_bvalid_r;	// src/main/scala/chisel3/util/Decoupled.scala:51:35, src/main/scala/utils/StopWatch.scala:24:20
      r_busy <= _sdHelper_io_ren_T_2 | ~_io_in_rvalid_T_3 & r_busy;	// src/main/scala/chisel3/util/Decoupled.scala:51:35, src/main/scala/utils/StopWatch.scala:24:20, :26:{19,23}, :27:{20,24}
      ren_REG <= _sdHelper_io_ren_T_2;	// src/main/scala/chisel3/util/Decoupled.scala:51:35, src/main/scala/device/AXI4Slave.scala:73:17
      io_in_rvalid_r <=
        ren_REG & (_sdHelper_io_ren_T_2 | r_busy) | ~_io_in_rvalid_T_3 & io_in_rvalid_r;	// src/main/scala/chisel3/util/Decoupled.scala:51:35, src/main/scala/device/AXI4Slave.scala:73:17, :74:{35,50}, src/main/scala/utils/StopWatch.scala:24:20, :26:{19,23}, :27:{20,24}
      w_busy <= ~w_busy & io_in_awvalid | ~_io_in_bvalid_T_2 & w_busy;	// src/main/scala/chisel3/util/Decoupled.scala:51:35, src/main/scala/device/AXI4Slave.scala:94:18, src/main/scala/utils/StopWatch.scala:24:20, :26:{19,23}, :27:{20,24}
      io_in_bvalid_r <= _io_in_bvalid_T_1 | ~_io_in_bvalid_T_2 & io_in_bvalid_r;	// src/main/scala/chisel3/util/Decoupled.scala:51:35, src/main/scala/utils/StopWatch.scala:24:20, :26:{19,23}, :27:{20,24}
      if (_GEN_0) begin	// src/main/scala/utils/RegMap.scala:32:32
        regs_0 <= _regs_0_T_3;	// src/main/scala/device/AXI4DummySD.scala:72:43, src/main/scala/utils/BitUtils.scala:34:26
        if (_regs_0_T_4)	// src/main/scala/device/AXI4DummySD.scala:85:18
          regs_4 <= 32'h80FF8000;	// src/main/scala/device/AXI4DummySD.scala:72:43, :87:22
        else if (_regs_0_T_5)	// src/main/scala/device/AXI4DummySD.scala:85:18
          regs_4 <= 32'h1;	// src/main/scala/device/AXI4DummySD.scala:72:43, :90:22
        else if (_regs_0_T_6)	// src/main/scala/device/AXI4DummySD.scala:85:18
          regs_4 <= 32'h92404001;	// src/main/scala/device/AXI4DummySD.scala:72:43, :96:22
        else if (_regs_0_T_7)	// src/main/scala/device/AXI4DummySD.scala:85:18
          regs_4 <= 32'h0;	// src/main/scala/device/AXI4DummySD.scala:72:43
      end
      if (_io_in_bvalid_T_1 & io_in_awaddr[12:0] == 13'h4)	// src/main/scala/chisel3/util/Decoupled.scala:51:35, src/main/scala/device/AXI4DummySD.scala:135:35, src/main/scala/utils/LookupTree.scala:24:34, src/main/scala/utils/RegMap.scala:32:{32,41}
        regs_1 <= io_in_wdata[31:0] & _GEN | regs_1 & ~_GEN;	// src/main/scala/device/AXI4DummySD.scala:72:43, :141:48, src/main/scala/utils/BitUtils.scala:27:26, :34:{14,26,37,39}
      if (~_GEN_0 | _regs_0_T_4) begin	// src/main/scala/device/AXI4DummySD.scala:72:43, :85:18, src/main/scala/utils/RegMap.scala:32:{32,48}
      end
      else if (_regs_0_T_5) begin	// src/main/scala/device/AXI4DummySD.scala:85:18
        regs_5 <= 32'h0;	// src/main/scala/device/AXI4DummySD.scala:72:43
        regs_6 <= 32'h0;	// src/main/scala/device/AXI4DummySD.scala:72:43
        regs_7 <= 32'h15000000;	// src/main/scala/device/AXI4DummySD.scala:72:43, :93:22
      end
      else if (_regs_0_T_6) begin	// src/main/scala/device/AXI4DummySD.scala:85:18
        regs_5 <= 32'hD24B97E3;	// src/main/scala/device/AXI4DummySD.scala:72:43, :97:39
        regs_6 <= 32'hF5F803F;	// src/main/scala/device/AXI4DummySD.scala:72:43, :98:22
        regs_7 <= 32'h8C26012A;	// src/main/scala/device/AXI4DummySD.scala:72:43, :99:22
      end
      else if (_regs_0_T_7) begin	// src/main/scala/device/AXI4DummySD.scala:85:18
        regs_5 <= 32'h0;	// src/main/scala/device/AXI4DummySD.scala:72:43
        regs_6 <= 32'h0;	// src/main/scala/device/AXI4DummySD.scala:72:43
        regs_7 <= 32'h0;	// src/main/scala/device/AXI4DummySD.scala:72:43
      end
      if (_io_in_bvalid_T_1 & io_in_awaddr[12:0] == 13'h20)	// src/main/scala/chisel3/util/Decoupled.scala:51:35, src/main/scala/device/AXI4DummySD.scala:135:35, src/main/scala/utils/LookupTree.scala:24:34, src/main/scala/utils/RegMap.scala:32:{32,41}
        regs_8 <= io_in_wdata[31:0] & _GEN | regs_8 & ~_GEN;	// src/main/scala/device/AXI4DummySD.scala:72:43, :141:48, src/main/scala/utils/BitUtils.scala:27:26, :34:{14,26,37,39}
      if (_io_in_bvalid_T_1 & io_in_awaddr[12:0] == 13'h38)	// src/main/scala/chisel3/util/Decoupled.scala:51:35, src/main/scala/device/AXI4DummySD.scala:135:35, src/main/scala/utils/LookupTree.scala:24:34, src/main/scala/utils/RegMap.scala:32:{32,41}
        regs_15 <= io_in_wdata[31:0] & _GEN | regs_15 & ~_GEN;	// src/main/scala/device/AXI4DummySD.scala:72:43, :141:48, src/main/scala/utils/BitUtils.scala:27:26, :34:{14,26,37,39}
      if (_io_in_bvalid_T_1 & io_in_awaddr[12:0] == 13'h50)	// src/main/scala/chisel3/util/Decoupled.scala:51:35, src/main/scala/device/AXI4DummySD.scala:135:35, src/main/scala/utils/LookupTree.scala:24:34, src/main/scala/utils/RegMap.scala:32:{32,41}
        regs_20 <= io_in_wdata[31:0] & _GEN | regs_20 & ~_GEN;	// src/main/scala/device/AXI4DummySD.scala:72:43, :141:48, src/main/scala/utils/BitUtils.scala:27:26, :34:{14,26,37,39}
    end
    io_in_rdata_REG <=
      {2{{_rdata_T_23[31:8],
          _rdata_T_23[7:0] | {io_in_araddr[12:0] == 13'h34, 7'h0}}
           | (io_in_araddr[12:0] == 13'h14 ? regs_5 : 32'h0)
           | (io_in_araddr[12:0] == 13'h1C ? regs_7 : 32'h0)
           | (io_in_araddr[12:0] == 13'h50 ? regs_20 : 32'h0)
           | (io_in_araddr[12:0] == 13'h10 ? regs_4 : 32'h0)
           | (io_in_araddr[12:0] == 13'h4 ? regs_1 : 32'h0)
           | (io_in_araddr[12:0] == 13'h20 ? regs_8 : 32'h0)
           | (io_in_araddr[12:0] == 13'h40 ? _sdHelper_data : 32'h0)}};	// src/main/scala/chisel3/util/Mux.scala:30:73, src/main/scala/device/AXI4DummySD.scala:72:43, :114:24, :116:40, :135:35, :144:{44,49}, src/main/scala/utils/LookupTree.scala:24:34
    if (ren_REG)	// src/main/scala/device/AXI4Slave.scala:73:17
      io_in_rdata_r <= io_in_rdata_REG;	// src/main/scala/device/AXI4DummySD.scala:144:{36,44}
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/device/AXI4DummySD.scala:68:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/device/AXI4DummySD.scala:68:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/device/AXI4DummySD.scala:68:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// src/main/scala/device/AXI4DummySD.scala:68:7
      automatic logic [31:0] _RANDOM[0:25];	// src/main/scala/device/AXI4DummySD.scala:68:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/device/AXI4DummySD.scala:68:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/device/AXI4DummySD.scala:68:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/device/AXI4DummySD.scala:68:7
        for (logic [4:0] i = 5'h0; i < 5'h1A; i += 5'h1) begin
          _RANDOM[i] = `RANDOM;	// src/main/scala/device/AXI4DummySD.scala:68:7
        end	// src/main/scala/device/AXI4DummySD.scala:68:7
        r_busy = _RANDOM[5'h0][0];	// src/main/scala/device/AXI4DummySD.scala:68:7, src/main/scala/utils/StopWatch.scala:24:20
        ren_REG = _RANDOM[5'h0][1];	// src/main/scala/device/AXI4DummySD.scala:68:7, src/main/scala/device/AXI4Slave.scala:73:17, src/main/scala/utils/StopWatch.scala:24:20
        io_in_rvalid_r = _RANDOM[5'h0][2];	// src/main/scala/device/AXI4DummySD.scala:68:7, src/main/scala/utils/StopWatch.scala:24:20
        w_busy = _RANDOM[5'h0][3];	// src/main/scala/device/AXI4DummySD.scala:68:7, src/main/scala/utils/StopWatch.scala:24:20
        io_in_bvalid_r = _RANDOM[5'h0][4];	// src/main/scala/device/AXI4DummySD.scala:68:7, src/main/scala/utils/StopWatch.scala:24:20
        regs_0 = {_RANDOM[5'h0][31:5], _RANDOM[5'h1][4:0]};	// src/main/scala/device/AXI4DummySD.scala:68:7, :72:43, src/main/scala/utils/StopWatch.scala:24:20
        regs_1 = {_RANDOM[5'h1][31:5], _RANDOM[5'h2][4:0]};	// src/main/scala/device/AXI4DummySD.scala:68:7, :72:43
        regs_4 = {_RANDOM[5'h4][31:5], _RANDOM[5'h5][4:0]};	// src/main/scala/device/AXI4DummySD.scala:68:7, :72:43
        regs_5 = {_RANDOM[5'h5][31:5], _RANDOM[5'h6][4:0]};	// src/main/scala/device/AXI4DummySD.scala:68:7, :72:43
        regs_6 = {_RANDOM[5'h6][31:5], _RANDOM[5'h7][4:0]};	// src/main/scala/device/AXI4DummySD.scala:68:7, :72:43
        regs_7 = {_RANDOM[5'h7][31:5], _RANDOM[5'h8][4:0]};	// src/main/scala/device/AXI4DummySD.scala:68:7, :72:43
        regs_8 = {_RANDOM[5'h8][31:5], _RANDOM[5'h9][4:0]};	// src/main/scala/device/AXI4DummySD.scala:68:7, :72:43
        regs_15 = {_RANDOM[5'hF][31:5], _RANDOM[5'h10][4:0]};	// src/main/scala/device/AXI4DummySD.scala:68:7, :72:43
        regs_20 = {_RANDOM[5'h14][31:5], _RANDOM[5'h15][4:0]};	// src/main/scala/device/AXI4DummySD.scala:68:7, :72:43
        io_in_rdata_REG =
          {_RANDOM[5'h15][31:5], _RANDOM[5'h16], _RANDOM[5'h17][4:0]};	// src/main/scala/device/AXI4DummySD.scala:68:7, :72:43, :144:44
        io_in_rdata_r = {_RANDOM[5'h17][31:5], _RANDOM[5'h18], _RANDOM[5'h19][4:0]};	// src/main/scala/device/AXI4DummySD.scala:68:7, :144:{36,44}
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/device/AXI4DummySD.scala:68:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/device/AXI4DummySD.scala:68:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  SDHelper sdHelper (	// src/main/scala/device/AXI4DummySD.scala:114:24
    .clk     (clock),
    .ren     (io_in_araddr[12:0] == 13'h40 & _sdHelper_io_ren_T_2),	// src/main/scala/chisel3/util/Decoupled.scala:51:35, src/main/scala/device/AXI4DummySD.scala:116:{40,51}, :135:35
    .data    (_sdHelper_data),
    .setAddr
      (_GEN_0 & ~(_regs_0_T_4 | _regs_0_T_5 | _regs_0_T_6 | _regs_0_T_7)
       & _regs_0_T_3[5:0] == 6'h12),	// src/main/scala/device/AXI4DummySD.scala:81:25, :84:20, :85:18, src/main/scala/utils/BitUtils.scala:34:26, src/main/scala/utils/RegMap.scala:32:{32,48}
    .addr    (regs_1)	// src/main/scala/device/AXI4DummySD.scala:72:43
  );
  assign io_in_awready = ~w_busy;	// src/main/scala/device/AXI4DummySD.scala:68:7, src/main/scala/device/AXI4Slave.scala:94:18, src/main/scala/utils/StopWatch.scala:24:20
  assign io_in_wready = io_in_wready_0;	// src/main/scala/device/AXI4DummySD.scala:68:7, src/main/scala/device/AXI4Slave.scala:95:30
  assign io_in_bvalid = io_in_bvalid_r;	// src/main/scala/device/AXI4DummySD.scala:68:7, src/main/scala/utils/StopWatch.scala:24:20
  assign io_in_arready = io_in_arready_0;	// src/main/scala/device/AXI4DummySD.scala:68:7, src/main/scala/device/AXI4Slave.scala:71:29
  assign io_in_rvalid = io_in_rvalid_r;	// src/main/scala/device/AXI4DummySD.scala:68:7, src/main/scala/utils/StopWatch.scala:24:20
  assign io_in_rdata = io_in_rdata_r;	// src/main/scala/device/AXI4DummySD.scala:68:7, :144:36
endmodule

