// Generated by CIRCT firtool-1.62.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for prints and assertions.

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module DummyDPICWrapper(	// difftest/src/main/scala/DPIC.scala:288:15
  input        clock,	// difftest/src/main/scala/DPIC.scala:288:15
  input [63:0] io_value_1,	// difftest/src/main/scala/DPIC.scala:290:14
               io_value_2,	// difftest/src/main/scala/DPIC.scala:290:14
               io_value_3,	// difftest/src/main/scala/DPIC.scala:290:14
               io_value_4,	// difftest/src/main/scala/DPIC.scala:290:14
               io_value_5,	// difftest/src/main/scala/DPIC.scala:290:14
               io_value_6,	// difftest/src/main/scala/DPIC.scala:290:14
               io_value_7,	// difftest/src/main/scala/DPIC.scala:290:14
               io_value_8,	// difftest/src/main/scala/DPIC.scala:290:14
               io_value_9,	// difftest/src/main/scala/DPIC.scala:290:14
               io_value_10,	// difftest/src/main/scala/DPIC.scala:290:14
               io_value_11,	// difftest/src/main/scala/DPIC.scala:290:14
               io_value_12,	// difftest/src/main/scala/DPIC.scala:290:14
               io_value_13,	// difftest/src/main/scala/DPIC.scala:290:14
               io_value_14,	// difftest/src/main/scala/DPIC.scala:290:14
               io_value_15,	// difftest/src/main/scala/DPIC.scala:290:14
               io_value_16,	// difftest/src/main/scala/DPIC.scala:290:14
               io_value_17,	// difftest/src/main/scala/DPIC.scala:290:14
               io_value_18,	// difftest/src/main/scala/DPIC.scala:290:14
               io_value_19,	// difftest/src/main/scala/DPIC.scala:290:14
               io_value_20,	// difftest/src/main/scala/DPIC.scala:290:14
               io_value_21,	// difftest/src/main/scala/DPIC.scala:290:14
               io_value_22,	// difftest/src/main/scala/DPIC.scala:290:14
               io_value_23,	// difftest/src/main/scala/DPIC.scala:290:14
               io_value_24,	// difftest/src/main/scala/DPIC.scala:290:14
               io_value_25,	// difftest/src/main/scala/DPIC.scala:290:14
               io_value_26,	// difftest/src/main/scala/DPIC.scala:290:14
               io_value_27,	// difftest/src/main/scala/DPIC.scala:290:14
               io_value_28,	// difftest/src/main/scala/DPIC.scala:290:14
               io_value_29,	// difftest/src/main/scala/DPIC.scala:290:14
               io_value_30,	// difftest/src/main/scala/DPIC.scala:290:14
               io_value_31	// difftest/src/main/scala/DPIC.scala:290:14
);

  DifftestArchIntRegState dpic (	// difftest/src/main/scala/DPIC.scala:291:20
    .clock       (clock),
    .enable      (1'h1),	// difftest/src/main/scala/DPIC.scala:289:19, :291:20
    .io_value_0  (64'h0),	// difftest/src/main/scala/DPIC.scala:290:14, :291:20
    .io_value_1  (io_value_1),
    .io_value_2  (io_value_2),
    .io_value_3  (io_value_3),
    .io_value_4  (io_value_4),
    .io_value_5  (io_value_5),
    .io_value_6  (io_value_6),
    .io_value_7  (io_value_7),
    .io_value_8  (io_value_8),
    .io_value_9  (io_value_9),
    .io_value_10 (io_value_10),
    .io_value_11 (io_value_11),
    .io_value_12 (io_value_12),
    .io_value_13 (io_value_13),
    .io_value_14 (io_value_14),
    .io_value_15 (io_value_15),
    .io_value_16 (io_value_16),
    .io_value_17 (io_value_17),
    .io_value_18 (io_value_18),
    .io_value_19 (io_value_19),
    .io_value_20 (io_value_20),
    .io_value_21 (io_value_21),
    .io_value_22 (io_value_22),
    .io_value_23 (io_value_23),
    .io_value_24 (io_value_24),
    .io_value_25 (io_value_25),
    .io_value_26 (io_value_26),
    .io_value_27 (io_value_27),
    .io_value_28 (io_value_28),
    .io_value_29 (io_value_29),
    .io_value_30 (io_value_30),
    .io_value_31 (io_value_31),
    .io_coreid   (8'h0)	// difftest/src/main/scala/DPIC.scala:290:14, :291:20
  );
endmodule

