// Generated by CIRCT firtool-1.62.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for prints and assertions.

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module EmbeddedTLBExec_1(	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:177:7
  input          clock,	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:177:7
                 reset,	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:177:7
  output         io_in_ready,	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:178:14
  input          io_in_valid,	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:178:14
  input  [38:0]  io_in_bits_addr,	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:178:14
  input  [2:0]   io_in_bits_size,	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:178:14
  input  [3:0]   io_in_bits_cmd,	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:178:14
  input  [7:0]   io_in_bits_wmask,	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:178:14
  input  [63:0]  io_in_bits_wdata,	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:178:14
  input          io_out_ready,	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:178:14
  output         io_out_valid,	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:178:14
  output [31:0]  io_out_bits_addr,	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:178:14
  output [2:0]   io_out_bits_size,	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:178:14
  output [3:0]   io_out_bits_cmd,	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:178:14
  output [7:0]   io_out_bits_wmask,	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:178:14
  output [63:0]  io_out_bits_wdata,	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:178:14
  input  [120:0] io_md_0,	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:178:14
                 io_md_1,	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:178:14
                 io_md_2,	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:178:14
                 io_md_3,	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:178:14
  output         io_mdWrite_wen,	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:178:14
  output [3:0]   io_mdWrite_windex,	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:178:14
                 io_mdWrite_waymask,	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:178:14
  output [120:0] io_mdWrite_wdata,	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:178:14
  input          io_mdReady,	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:178:14
                 io_mem_req_ready,	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:178:14
  output         io_mem_req_valid,	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:178:14
  output [31:0]  io_mem_req_bits_addr,	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:178:14
  output [3:0]   io_mem_req_bits_cmd,	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:178:14
  output [63:0]  io_mem_req_bits_wdata,	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:178:14
  input          io_mem_resp_valid,	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:178:14
  input  [3:0]   io_mem_resp_bits_cmd,	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:178:14
  input  [63:0]  io_mem_resp_bits_rdata,	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:178:14
                 io_satp,	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:178:14
  input  [1:0]   io_pf_privilegeMode,	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:178:14
  input          io_pf_status_sum,	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:178:14
                 io_pf_status_mxr,	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:178:14
  output         io_pf_loadPF,	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:178:14
                 io_pf_storePF,	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:178:14
  output [38:0]  io_pf_addr,	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:178:14
  output         io_isFinish,	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:178:14
  input          isAMO__bore
);

  wire        io_out_valid_0;	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:387:31
  wire        storePF;	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:248:13, :275:18
  wire        loadPF;	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:247:12, :275:18
  reg         io_pf_storePF_REG;	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:243:27
  reg         io_pf_loadPF_REG;	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:242:26
  wire [63:0] _LogPerfHelper_1_timer;	// difftest/src/main/scala/common/LogPerfControl.scala:60:79
  wire        _LogPerfHelper_1_logEnable;	// difftest/src/main/scala/common/LogPerfControl.scala:60:79
  wire [63:0] _LogPerfHelper_timer;	// difftest/src/main/scala/common/LogPerfControl.scala:60:79
  wire        _LogPerfHelper_logEnable;	// difftest/src/main/scala/common/LogPerfControl.scala:60:79
  wire [26:0] _hitVec_T_37 = {9'h1FF, io_md_0[77:60]};	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:209:152, src/main/scala/nutcore/mem/TLB.scala:131:9
  wire [26:0] _hitVec_T_78 = {9'h1FF, io_md_1[77:60]};	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:209:152, src/main/scala/nutcore/mem/TLB.scala:131:9
  wire [26:0] _hitVec_T_119 = {9'h1FF, io_md_2[77:60]};	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:209:152, src/main/scala/nutcore/mem/TLB.scala:131:9
  wire [26:0] _hitVec_T_160 = {9'h1FF, io_md_3[77:60]};	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:209:152, src/main/scala/nutcore/mem/TLB.scala:131:9
  wire [3:0]  hitVec =
    {io_md_3[52] & io_md_3[93:78] == io_satp[59:44]
       & (_hitVec_T_160 & io_md_3[120:94]) == (_hitVec_T_160 & io_in_bits_addr[38:12]),
     io_md_2[52] & io_md_2[93:78] == io_satp[59:44]
       & (_hitVec_T_119 & io_md_2[120:94]) == (_hitVec_T_119 & io_in_bits_addr[38:12]),
     io_md_1[52] & io_md_1[93:78] == io_satp[59:44]
       & (_hitVec_T_78 & io_md_1[120:94]) == (_hitVec_T_78 & io_in_bits_addr[38:12]),
     io_md_0[52] & io_md_0[93:78] == io_satp[59:44]
       & (_hitVec_T_37 & io_md_0[120:94]) == (_hitVec_T_37 & io_in_bits_addr[38:12])};	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:200:30, :209:{71,100,117,132,180,201,211}, src/main/scala/nutcore/mem/TLB.scala:131:{9,37,48,84}
  wire        hit = io_in_valid & (|hitVec);	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:209:211, :210:{25,35}
  wire        miss = io_in_valid & ~(|hitVec);	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:209:211, :210:35, :211:{26,29}
  reg  [63:0] victimWaymask_lfsr;	// src/main/scala/utils/LFSR64.scala:25:23
  wire [3:0]  waymask = hit ? hitVec : 4'h1 << victimWaymask_lfsr[1:0];	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:177:7, :209:211, :210:25, :213:{42,53}, :214:20, src/main/scala/utils/LFSR64.scala:25:23
  wire [68:0] _hitMeta_T_10 =
    (waymask[0] ? io_md_0[120:52] : 69'h0) | (waymask[1] ? io_md_1[120:52] : 69'h0)
    | (waymask[2] ? io_md_2[120:52] : 69'h0) | (waymask[3] ? io_md_3[120:52] : 69'h0);	// src/main/scala/chisel3/util/Mux.scala:30:73, :32:36, src/main/scala/nutcore/mem/EmbeddedTLB.scala:178:14, :214:20
  wire [51:0] _hitData_T_10 =
    (waymask[0] ? io_md_0[51:0] : 52'h0) | (waymask[1] ? io_md_1[51:0] : 52'h0)
    | (waymask[2] ? io_md_2[51:0] : 52'h0) | (waymask[3] ? io_md_3[51:0] : 52'h0);	// src/main/scala/chisel3/util/Mux.scala:30:73, :32:36, src/main/scala/nutcore/mem/EmbeddedTLB.scala:178:14, :214:20
  wire        _io_isFinish_T_1 = io_pf_loadPF_REG | io_pf_storePF_REG;	// src/main/scala/nutcore/Bundle.scala:131:23, src/main/scala/nutcore/mem/EmbeddedTLB.scala:242:26, :243:27
  wire        hitWB =
    hit & (~(_hitMeta_T_10[6]) | ~(_hitMeta_T_10[7]) & io_in_bits_cmd[0])
    & ~(loadPF | storePF | _io_isFinish_T_1);	// src/main/scala/bus/simplebus/SimpleBus.scala:74:22, src/main/scala/chisel3/util/Mux.scala:30:73, src/main/scala/nutcore/Bundle.scala:131:23, src/main/scala/nutcore/mem/EmbeddedTLB.scala:210:25, :222:38, :226:{23,34,37,48,81,84,104}, :247:12, :248:13, :275:18
  wire [7:0]  hitRefillFlag = {io_in_bits_cmd[0], 7'h40} | _hitMeta_T_10[7:0];	// src/main/scala/bus/simplebus/SimpleBus.scala:74:22, src/main/scala/chisel3/util/Mux.scala:30:73, src/main/scala/nutcore/mem/EmbeddedTLB.scala:227:{26,69,79}, :326:31
  reg  [39:0] hitWBStore;	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:228:29
  wire        _permCheck_T = io_pf_privilegeMode == 2'h0;	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:228:33, :231:61
  wire        _permCheck_T_5 = io_pf_privilegeMode == 2'h1;	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:231:108
  wire        hitCheck =
    hit & ~(_permCheck_T & ~(_hitMeta_T_10[4]))
    & ~(_permCheck_T_5 & _hitMeta_T_10[4] & ~io_pf_status_sum);	// src/main/scala/chisel3/util/Mux.scala:30:73, src/main/scala/nutcore/mem/EmbeddedTLB.scala:210:25, :222:38, :231:{42,61,71,74,86,89,108,131,135}
  wire        hitADCheck = ~(_hitMeta_T_10[6]) | ~(_hitMeta_T_10[7]) & io_in_bits_cmd[0];	// src/main/scala/bus/simplebus/SimpleBus.scala:74:22, src/main/scala/chisel3/util/Mux.scala:30:73, src/main/scala/nutcore/mem/EmbeddedTLB.scala:222:38, :226:{23,37}, :232:{78,92}
  wire        hitLoad =
    hitCheck & ~hitADCheck & (_hitMeta_T_10[1] | io_pf_status_mxr & _hitMeta_T_10[3]);	// src/main/scala/chisel3/util/Mux.scala:30:73, src/main/scala/nutcore/mem/EmbeddedTLB.scala:222:38, :231:86, :232:78, :233:29, :234:{41,55,72}
  wire        hitStore = hitCheck & ~hitADCheck & _hitMeta_T_10[2];	// src/main/scala/chisel3/util/Mux.scala:30:73, src/main/scala/nutcore/mem/EmbeddedTLB.scala:222:38, :231:86, :232:78, :233:29, :235:42
  wire        _loadPF_T_9 =
    ~hitLoad & ~(io_in_bits_cmd[0]) & ~(io_in_bits_cmd[3]) & hit & ~isAMO__bore;	// src/main/scala/bus/simplebus/SimpleBus.scala:73:{18,29,33}, :74:22, src/main/scala/nutcore/mem/EmbeddedTLB.scala:210:25, :234:41, :247:{15,47,50}
  wire        _storePF_T_13 =
    ~hitStore & io_in_bits_cmd[0] & hit | ~hitLoad & ~(io_in_bits_cmd[0])
    & ~(io_in_bits_cmd[3]) & hit & isAMO__bore;	// src/main/scala/bus/simplebus/SimpleBus.scala:73:{18,29,33}, :74:22, src/main/scala/nutcore/mem/EmbeddedTLB.scala:210:25, :234:41, :235:42, :247:15, :248:{17,44,52,88}
  reg  [2:0]  state;	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:253:22
  reg  [1:0]  level;	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:254:22
  reg  [63:0] memRespStore;	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:256:25
  reg  [17:0] missMaskStore;	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:258:26
  reg  [31:0] raddr;	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:262:18
  wire        _io_isFinish_T = io_out_ready & io_out_valid_0;	// src/main/scala/chisel3/util/Decoupled.scala:51:35, src/main/scala/nutcore/mem/EmbeddedTLB.scala:387:31
  reg         alreadyOutFire;	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:263:33
  reg         needFlush;	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:266:26
  reg         missIPF;	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:272:24
  wire        _GEN = state == 3'h1;	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:253:22, :275:18, :282:15
  wire        _GEN_0 = state == 3'h2;	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:253:22, :275:18, :294:44
  wire        _missMask_T_1 = level == 2'h2;	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:254:22, :303:73
  wire        _GEN_1 =
    ~(io_mem_resp_bits_rdata[1] | io_mem_resp_bits_rdata[3]) & ((&level) | _missMask_T_1);	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:254:22, :298:44, :303:{21,34,49,58,65,73}
  wire        _GEN_2 =
    ~(io_mem_resp_bits_rdata[0]) | ~(io_mem_resp_bits_rdata[1])
    & io_mem_resp_bits_rdata[2];	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:298:44, :304:{16,28,32,44}
  wire        _GEN_3 = _GEN_0 & io_mem_resp_valid;	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:262:18, :275:18, :299:31, :300:24
  wire        permCheck =
    io_mem_resp_bits_rdata[0] & ~(_permCheck_T & ~(io_mem_resp_bits_rdata[4]))
    & ~(_permCheck_T_5 & io_mem_resp_bits_rdata[4] & ~io_pf_status_sum);	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:231:{61,108,135}, :298:44, :320:{41,70,73,86,89,132}
  wire        permAD =
    ~(io_mem_resp_bits_rdata[6]) | ~(io_mem_resp_bits_rdata[7]) & io_in_bits_cmd[0];	// src/main/scala/bus/simplebus/SimpleBus.scala:74:22, src/main/scala/nutcore/mem/EmbeddedTLB.scala:298:44, :321:{71,83,87,99}
  wire        _GEN_4 = needFlush | _GEN_1;	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:260:32, :266:26, :300:24, :303:{49,82}, :319:36
  wire        _GEN_5 = ~(|state) | _GEN;	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:253:22, :260:32, :275:18
  wire        _GEN_6 = _GEN_5 | ~_GEN_3 | _GEN_4 | ~(|level);	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:254:22, :260:32, :262:18, :275:18, :299:31, :300:24, :303:82, :319:{27,36}
  wire [7:0]  missRefillFlag =
    _GEN_6 ? 8'h0 : {io_in_bits_cmd[0], 7'h40} | io_mem_resp_bits_rdata[7:0];	// src/main/scala/bus/simplebus/SimpleBus.scala:74:22, src/main/scala/nutcore/mem/EmbeddedTLB.scala:260:32, :275:18, :326:31, :327:{32,68,79}
  wire        _GEN_7 =
    ~(permCheck & ~permAD
      & (io_mem_resp_bits_rdata[1] | io_pf_status_mxr & io_mem_resp_bits_rdata[3]))
    & ~(io_in_bits_cmd[0]) & ~(io_in_bits_cmd[3])
    | ~(permCheck & ~permAD & io_mem_resp_bits_rdata[2]) & io_in_bits_cmd[0];	// src/main/scala/bus/simplebus/SimpleBus.scala:73:{18,29,33}, :74:22, src/main/scala/nutcore/mem/EmbeddedTLB.scala:298:44, :320:86, :321:83, :322:39, :323:{47,62,79}, :324:48, :337:{19,29,46,50,61}
  wire        _GEN_8 = (|level) & _GEN_7;	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:247:12, :254:22, :319:{27,36}, :337:{46,80}, :339:22
  wire        _GEN_9 = _GEN_5 | ~_GEN_3 | needFlush;	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:247:12, :260:32, :262:18, :266:26, :275:18, :299:31, :300:24
  assign loadPF =
    _GEN_9
      ? _loadPF_T_9
      : _GEN_1
          ? (_GEN_2
               ? ~(io_in_bits_cmd[0]) & ~(io_in_bits_cmd[3]) & ~isAMO__bore
               : _loadPF_T_9)
          : _GEN_8
              ? ~(io_in_bits_cmd[0]) & ~(io_in_bits_cmd[3]) & ~isAMO__bore
              : _loadPF_T_9;	// src/main/scala/bus/simplebus/SimpleBus.scala:73:{18,29,33}, :74:22, src/main/scala/nutcore/mem/EmbeddedTLB.scala:247:{12,47,50}, :275:18, :303:{49,82}, :304:{28,60}, :308:{22,38}, :319:36, :337:80, :339:{22,38}
  assign storePF =
    _GEN_9
      ? _storePF_T_13
      : _GEN_1
          ? (_GEN_2 ? io_in_bits_cmd[0] | isAMO__bore : _storePF_T_13)
          : _GEN_8 ? io_in_bits_cmd[0] | isAMO__bore : _storePF_T_13;	// src/main/scala/bus/simplebus/SimpleBus.scala:74:22, src/main/scala/nutcore/mem/EmbeddedTLB.scala:247:12, :248:{13,52}, :275:18, :303:{49,82}, :304:{28,60}, :309:{23,40}, :319:36, :337:80, :339:22, :340:{23,40}
  wire        missMetaRefill = ~_GEN_5 & _GEN_3 & ~_GEN_4 & (|level) & ~_GEN_7;	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:204:13, :254:22, :259:32, :260:32, :262:18, :275:18, :299:31, :300:24, :303:82, :319:{27,36}, :337:{46,80}, :343:30, src/main/scala/utils/LFSR64.scala:27:22
  wire [17:0] missMask =
    _GEN_6 ? 18'h3FFFF : (&level) ? 18'h0 : _missMask_T_1 ? 18'h3FE00 : 18'h3FFFF;	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:254:22, :257:26, :260:32, :275:18, :303:{58,73}, :346:{26,59}
  wire        cmd = state == 3'h3;	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:253:22, :278:15, :372:23
  wire [31:0] io_mem_req_bits_addr_0 = hitWB ? _hitData_T_10[31:0] : raddr;	// src/main/scala/chisel3/util/Mux.scala:30:73, src/main/scala/nutcore/mem/EmbeddedTLB.scala:221:70, :226:81, :262:18, :373:35
  wire [63:0] io_mem_req_bits_wdata_0 = hitWB ? {24'h0, hitWBStore} : memRespStore;	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:226:81, :228:29, :256:25, :373:138
  wire [3:0]  io_mem_req_bits_cmd_0 = {3'h0, cmd};	// src/main/scala/bus/simplebus/SimpleBus.scala:65:14, src/main/scala/nutcore/mem/EmbeddedTLB.scala:253:22, :372:23
  wire        io_mem_req_valid_0 = (state == 3'h1 | cmd) & ~needFlush;	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:253:22, :266:26, :282:15, :372:23, :374:{31,48,74,77}
  reg         REG;	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:378:33
  reg  [3:0]  REG_1;	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:379:21
  reg  [3:0]  REG_2;	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:379:60
  reg  [26:0] REG_3;	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:379:84
  reg  [15:0] REG_4;	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:380:19
  reg  [17:0] REG_5;	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:380:72
  reg  [7:0]  REG_6;	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:381:19
  reg  [19:0] REG_7;	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:381:77
  reg  [31:0] REG_8;	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:382:22
  wire [31:0] io_out_bits_addr_0 =
    hit
      ? {_hitData_T_10[51:32], 12'h0} & {2'h3, _hitMeta_T_10[25:8], 12'h0}
        | io_in_bits_addr[31:0] & {2'h0, ~(_hitMeta_T_10[25:8]), 12'hFFF}
      : {memRespStore[29:10], 12'h0} & {2'h3, missMaskStore, 12'h0}
        | io_in_bits_addr[31:0] & {2'h0, ~missMaskStore, 12'hFFF};	// src/main/scala/chisel3/util/Mux.scala:30:73, src/main/scala/nutcore/mem/EmbeddedTLB.scala:210:25, :220:70, :221:70, :228:33, :254:22, :256:25, :258:26, :386:{26,63,122}, src/main/scala/nutcore/mem/TLB.scala:127:{24,49}, src/main/scala/utils/BitUtils.scala:34:{14,26,37,39}
  assign io_out_valid_0 =
    io_in_valid & (hit & ~hitWB ? ~(_io_isFinish_T_1 | loadPF | storePF) : state == 3'h4);	// src/main/scala/nutcore/Bundle.scala:131:23, src/main/scala/nutcore/mem/EmbeddedTLB.scala:210:25, :226:81, :247:12, :248:13, :253:22, :275:18, :342:27, :387:{31,37,42,45,53,78,97}
  wire        io_in_ready_0 =
    io_out_ready & ~(|state) & ~miss & ~hitWB & io_mdReady & ~_io_isFinish_T_1 & ~loadPF
    & ~storePF;	// src/main/scala/nutcore/Bundle.scala:131:23, src/main/scala/nutcore/mem/EmbeddedTLB.scala:211:26, :226:81, :247:12, :248:13, :253:22, :275:18, :378:82, :387:45, :389:{56,86,90,107,118}
  wire        io_isFinish_0 = _io_isFinish_T | _io_isFinish_T_1;	// src/main/scala/chisel3/util/Decoupled.scala:51:35, src/main/scala/nutcore/Bundle.scala:131:23, src/main/scala/nutcore/mem/EmbeddedTLB.scala:392:30
  `ifndef SYNTHESIS	// src/main/scala/utils/Debug.scala:49:26
    always @(posedge clock) begin	// src/main/scala/utils/Debug.scala:49:26
      if ((`PRINTF_COND_) & (|state) & ~_GEN & _GEN_0 & io_mem_resp_valid & ~needFlush
          & _GEN_1 & _GEN_2 & _LogPerfHelper_logEnable & ~reset) begin	// difftest/src/main/scala/common/LogPerfControl.scala:60:79, src/main/scala/nutcore/mem/EmbeddedTLB.scala:253:22, :266:26, :275:18, :300:24, :303:49, :304:28, src/main/scala/utils/Debug.scala:49:26, :50:15
        $fwrite(32'h80000002, "[%d] EmbeddedTLBExec_1: ", _LogPerfHelper_timer);	// difftest/src/main/scala/common/LogPerfControl.scala:60:79, src/main/scala/utils/Debug.scala:49:26
        $fwrite(32'h80000002, "tlbException!!! ");	// src/main/scala/utils/Debug.scala:49:26, :50:15
        $fwrite(32'h80000002,
                " req:addr = 0x%x, cmd = %d, size = %d, wmask = 0x%x, wdata = 0x%x  Memreq:DecoupledIO(ready -> %d, valid -> %d, bits -> addr = 0x%x, cmd = %d, size = %d, wmask = 0x%x, wdata = 0x%x)  MemResp:DecoupledIO(ready -> %d, valid -> %d, bits -> rdata = %x, cmd = %d)",
                io_in_bits_addr, io_in_bits_cmd, io_in_bits_size, io_in_bits_wmask,
                io_in_bits_wdata, io_mem_req_ready, io_mem_req_valid_0,
                io_mem_req_bits_addr_0, io_mem_req_bits_cmd_0, 3'h3, 8'hFF,
                io_mem_req_bits_wdata_0, 1'h1, io_mem_resp_valid, io_mem_resp_bits_rdata,
                io_mem_resp_bits_cmd);	// src/main/scala/bus/simplebus/SimpleBus.scala:65:14, :68:16, src/main/scala/nutcore/mem/EmbeddedTLB.scala:178:14, :277:13, :278:15, :373:{35,138}, :374:74, src/main/scala/utils/Debug.scala:49:26, :50:15
        $fwrite(32'h80000002, " level:%d", level);	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:254:22, src/main/scala/utils/Debug.scala:49:26, :50:15
        $fwrite(32'h80000002, "\n");	// src/main/scala/utils/Debug.scala:49:26, :50:15
      end
      if ((`PRINTF_COND_) & _LogPerfHelper_1_logEnable & ~reset) begin	// difftest/src/main/scala/common/LogPerfControl.scala:60:79, src/main/scala/utils/Debug.scala:49:26, :50:15
        $fwrite(32'h80000002, "[%d] EmbeddedTLBExec_1: ", _LogPerfHelper_1_timer);	// difftest/src/main/scala/common/LogPerfControl.scala:60:79, src/main/scala/utils/Debug.scala:49:26
        $fwrite(32'h80000002, "In(%d, %d) Out(%d, %d) InAddr:%x OutAddr:%x cmd:%d \n",
                io_in_valid, io_in_ready_0, io_out_valid_0, io_out_ready, io_in_bits_addr,
                io_out_bits_addr_0, io_in_bits_cmd);	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:386:26, :387:31, :389:86, src/main/scala/utils/Debug.scala:49:26, :50:15
        $fwrite(32'h80000002, "[%d] EmbeddedTLBExec_1: ", _LogPerfHelper_1_timer);	// difftest/src/main/scala/common/LogPerfControl.scala:60:79, src/main/scala/utils/Debug.scala:49:26
        $fwrite(32'h80000002,
                "isAMO:%d io.Flush:%d needFlush:%d alreadyOutFire:%d isFinish:%d\n",
                isAMO__bore, 1'h0, needFlush, alreadyOutFire, io_isFinish_0);	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:178:14, :263:33, :266:26, :269:17, :392:30, src/main/scala/utils/Debug.scala:49:26, :50:15
        $fwrite(32'h80000002, "[%d] EmbeddedTLBExec_1: ", _LogPerfHelper_1_timer);	// difftest/src/main/scala/common/LogPerfControl.scala:60:79, src/main/scala/utils/Debug.scala:49:26
        $fwrite(32'h80000002,
                "hit:%d hitWB:%d hitVPN:%x hitFlag:%x hitPPN:%x hitRefillFlag:%x hitWBStore:%x hitCheck:%d hitExec:%d hitLoad:%d hitStore:%d\n",
                hit, hitWB, _hitMeta_T_10[68:42], _hitMeta_T_10[7:0],
                _hitData_T_10[51:32], hitRefillFlag, hitWBStore, hitCheck,
                hitCheck & ~hitADCheck & _hitMeta_T_10[3], hitLoad, hitStore);	// src/main/scala/chisel3/util/Mux.scala:30:73, src/main/scala/nutcore/mem/EmbeddedTLB.scala:210:25, :220:70, :221:70, :222:38, :226:81, :227:69, :228:29, :231:86, :232:78, :233:{29,41}, :234:41, :235:42, :396:171, src/main/scala/utils/Debug.scala:49:26, :50:15
        $fwrite(32'h80000002, "[%d] EmbeddedTLBExec_1: ", _LogPerfHelper_1_timer);	// difftest/src/main/scala/common/LogPerfControl.scala:60:79, src/main/scala/utils/Debug.scala:49:26
        $fwrite(32'h80000002,
                "miss:%d state:%d level:%d raddr:%x memRdata:%x missMask:%x missRefillFlag:%x missMetaRefill:%d\n",
                miss, state, level, raddr, io_mem_resp_bits_rdata, missMask,
                missRefillFlag, missMetaRefill);	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:211:26, :253:22, :254:22, :257:26, :259:32, :260:32, :262:18, :275:18, src/main/scala/utils/Debug.scala:49:26, :50:15
        $fwrite(32'h80000002, "[%d] EmbeddedTLBExec_1: ", _LogPerfHelper_1_timer);	// difftest/src/main/scala/common/LogPerfControl.scala:60:79, src/main/scala/utils/Debug.scala:49:26
        $fwrite(32'h80000002,
                "meta/data: (0)%x|%b|%x (1)%x|%b|%x (2)%x|%b|%x (3)%x|%b|%x rread:%d\n",
                io_md_0[120:94], io_md_0[59:52], io_md_0[51:32], io_md_1[120:94],
                io_md_1[59:52], io_md_1[51:32], io_md_2[120:94], io_md_2[59:52],
                io_md_2[51:32], io_md_3[120:94], io_md_3[59:52], io_md_3[51:32],
                io_mdReady);	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:398:{96,127,159,190,221,253,284,315,347,378,409,441}, src/main/scala/utils/Debug.scala:49:26, :50:15
        $fwrite(32'h80000002, "[%d] EmbeddedTLBExec_1: ", _LogPerfHelper_1_timer);	// difftest/src/main/scala/common/LogPerfControl.scala:60:79, src/main/scala/utils/Debug.scala:49:26
        $fwrite(32'h80000002,
                "md: wen:%d windex:%x waymask:%x vpn:%x asid:%x mask:%x flag:%x asid:%x ppn:%x pteaddr:%x\n",
                REG, REG_1, REG_2, REG_3, REG_4, REG_5, REG_6, REG_4, REG_7, REG_8);	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:378:33, :379:{21,60,84}, :380:{19,72}, :381:{19,77}, :382:22, src/main/scala/utils/Debug.scala:49:26, :50:15
        $fwrite(32'h80000002, "[%d] EmbeddedTLBExec_1: ", _LogPerfHelper_1_timer);	// difftest/src/main/scala/common/LogPerfControl.scala:60:79, src/main/scala/utils/Debug.scala:49:26
        $fwrite(32'h80000002,
                "MemReq(%d, %d) MemResp(%d, %d) addr:%x cmd:%d rdata:%x cmd:%d\n",
                io_mem_req_valid_0, io_mem_req_ready, io_mem_resp_valid, 1'h1,
                io_mem_req_bits_addr_0, io_mem_req_bits_cmd_0, io_mem_resp_bits_rdata,
                io_mem_resp_bits_cmd);	// src/main/scala/bus/simplebus/SimpleBus.scala:65:14, src/main/scala/nutcore/mem/EmbeddedTLB.scala:178:14, :277:13, :373:35, :374:74, src/main/scala/utils/Debug.scala:49:26, :50:15
        $fwrite(32'h80000002, "[%d] EmbeddedTLBExec_1: ", _LogPerfHelper_1_timer);	// difftest/src/main/scala/common/LogPerfControl.scala:60:79, src/main/scala/utils/Debug.scala:49:26
        $fwrite(32'h80000002,
                "io.ipf:%d hitinstrPF:%d missIPF:%d pf.loadPF:%d pf.storePF:%d loadPF:%d storePF:%d\n",
                ~hit & missIPF, 1'h0, missIPF, io_pf_loadPF_REG, io_pf_storePF_REG,
                loadPF, storePF);	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:178:14, :210:25, :242:26, :243:27, :247:12, :248:13, :269:17, :272:24, :275:18, :391:16, src/main/scala/utils/Debug.scala:49:26, :50:15
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
  always @(posedge clock) begin	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:177:7
    automatic logic _GEN_10;	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:262:18, :277:32, :281:37
    _GEN_10 = hitWB | ~miss;	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:211:26, :226:81, :262:18, :277:32, :281:37
    if (reset) begin	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:177:7
      victimWaymask_lfsr <= 64'h1234567887654321;	// src/main/scala/utils/LFSR64.scala:25:23
      io_pf_loadPF_REG <= 1'h0;	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:178:14, :242:26, :269:17
      io_pf_storePF_REG <= 1'h0;	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:178:14, :243:27, :269:17
      state <= 3'h0;	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:253:22
      level <= 2'h3;	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:254:22
      alreadyOutFire <= 1'h0;	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:178:14, :263:33, :269:17
      needFlush <= 1'h0;	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:178:14, :266:26, :269:17
      missIPF <= 1'h0;	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:178:14, :269:17, :272:24
      REG <= 1'h0;	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:178:14, :269:17, :378:33
    end
    else begin	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:177:7
      automatic logic _GEN_11;	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:263:33
      automatic logic _GEN_12;	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:270:21
      automatic logic _GEN_13;	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:275:18
      automatic logic _GEN_14;	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:275:18
      automatic logic _GEN_15;	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:360:53
      automatic logic _GEN_16;	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:272:24, :275:18, :360:71, :362:15
      automatic logic _GEN_17;	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:272:24, :275:18
      _GEN_11 = _io_isFinish_T | alreadyOutFire;	// src/main/scala/chisel3/util/Decoupled.scala:51:35, src/main/scala/nutcore/mem/EmbeddedTLB.scala:263:33
      _GEN_12 = _io_isFinish_T & needFlush;	// src/main/scala/chisel3/util/Decoupled.scala:51:35, src/main/scala/nutcore/mem/EmbeddedTLB.scala:266:26, :270:21
      _GEN_13 = state == 3'h3;	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:253:22, :275:18, :278:15
      _GEN_14 = state == 3'h4;	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:253:22, :275:18, :342:27
      _GEN_15 = _io_isFinish_T | alreadyOutFire;	// src/main/scala/chisel3/util/Decoupled.scala:51:35, src/main/scala/nutcore/mem/EmbeddedTLB.scala:263:33, :360:53
      _GEN_16 = _GEN_14 & _GEN_15;	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:272:24, :275:18, :360:{53,71}, :362:15
      _GEN_17 = _GEN | _GEN_0 | _GEN_13;	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:272:24, :275:18
      if (victimWaymask_lfsr == 64'h0)	// src/main/scala/utils/LFSR64.scala:25:23, :28:24
        victimWaymask_lfsr <= 64'h1;	// src/main/scala/utils/LFSR64.scala:25:23, :28:18
      else	// src/main/scala/utils/LFSR64.scala:28:24
        victimWaymask_lfsr <=
          {victimWaymask_lfsr[0] ^ victimWaymask_lfsr[1] ^ victimWaymask_lfsr[3]
             ^ victimWaymask_lfsr[4],
           victimWaymask_lfsr[63:1]};	// src/main/scala/utils/LFSR64.scala:25:23, :26:{19,29,39,43,49}, :28:{41,51}
      io_pf_loadPF_REG <= loadPF;	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:242:26, :247:12, :275:18
      io_pf_storePF_REG <= storePF;	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:243:27, :248:13, :275:18
      if (|state) begin	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:253:22, :275:18
        automatic logic _GEN_18;	// src/main/scala/chisel3/util/Decoupled.scala:51:35
        _GEN_18 = io_mem_req_ready & io_mem_req_valid_0;	// src/main/scala/chisel3/util/Decoupled.scala:51:35, src/main/scala/nutcore/mem/EmbeddedTLB.scala:374:74
        if (_GEN) begin	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:275:18
          if (needFlush)	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:266:26
            state <= 3'h0;	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:253:22
          else if (_GEN_18)	// src/main/scala/chisel3/util/Decoupled.scala:51:35
            state <= 3'h2;	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:253:22, :294:44
        end
        else if (_GEN_0) begin	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:275:18
          if (io_mem_resp_valid) begin	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:178:14
            if (needFlush)	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:266:26
              state <= 3'h0;	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:253:22
            else if (_GEN_1)	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:303:49
              state <= {_GEN_2, 2'h1};	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:231:108, :253:22, :304:{28,60}, :305:73, :316:19
            else if (|level)	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:254:22, :319:27
              state <= {2'h2, _GEN_7};	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:253:22, :303:73, :337:{46,80}, :338:21, :342:21
          end
        end
        else if (_GEN_13) begin	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:275:18
          if (needFlush)	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:266:26
            state <= 3'h0;	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:253:22
          else if (_GEN_18)	// src/main/scala/chisel3/util/Decoupled.scala:51:35
            state <= 3'h4;	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:253:22, :342:27
        end
        else if (_GEN_14 ? _GEN_15 : state == 3'h5)	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:253:22, :275:18, :305:73, :360:{53,71}, :361:13, :367:13
          state <= 3'h0;	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:253:22
        if (_GEN | ~_GEN_3) begin	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:254:22, :262:18, :275:18, :299:31, :300:24
        end
        else	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:254:22, :275:18
          level <= level - 2'h1;	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:254:22, :349:24
        alreadyOutFire <= (_GEN_17 | ~_GEN_16) & _GEN_11;	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:263:33, :272:24, :275:18, :360:71, :362:15
        if (_GEN | (_GEN_0 ? io_mem_resp_valid : _GEN_13))	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:270:35, :275:18, :291:22, :299:31, :300:24, :354:22
          needFlush <= ~(needFlush | _GEN_12) & needFlush;	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:266:26, :269:40, :270:{21,35,47}, :291:22, :293:19
        else	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:275:18, :291:22
          needFlush <= ~_GEN_12 & needFlush;	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:266:26, :269:40, :270:{21,35,47}
      end
      else begin	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:275:18
        if (hitWB)	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:226:81
          state <= 3'h3;	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:253:22, :278:15
        else if (miss)	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:211:26
          state <= 3'h1;	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:253:22, :282:15
        if (_GEN_10) begin	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:254:22, :262:18, :277:32, :281:37
        end
        else	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:254:22, :277:32, :281:37
          level <= 2'h3;	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:254:22
        alreadyOutFire <= ~(hitWB | miss) & _GEN_11;	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:211:26, :226:81, :263:33, :277:32, :280:24, :281:37, :286:24
        needFlush <= ~(hitWB | miss | _GEN_12) & needFlush;	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:211:26, :226:81, :266:26, :269:40, :270:{21,35,47}, :277:32, :279:19, :281:37, :285:19
      end
      missIPF <= (~(|state) | _GEN_17 | ~_GEN_16) & missIPF;	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:253:22, :272:24, :275:18, :360:71, :362:15
      REG <= missMetaRefill & ~needFlush | hitWB & ~(|state) & ~needFlush;	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:226:81, :253:22, :259:32, :266:26, :275:18, :374:77, :378:{33,50,63,82,93}
    end
    if (hitWB)	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:226:81
      hitWBStore <= {10'h0, _hitData_T_10[51:32], 2'h0, hitRefillFlag};	// src/main/scala/chisel3/util/Mux.scala:30:73, src/main/scala/nutcore/mem/EmbeddedTLB.scala:221:70, :227:69, :228:{29,33}
    if (_GEN_6) begin	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:258:26, :260:32, :275:18
    end
    else begin	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:258:26, :275:18
      memRespStore <= io_mem_resp_bits_rdata | {56'h0, io_in_bits_cmd[0], 7'h40};	// src/main/scala/bus/simplebus/SimpleBus.scala:74:22, src/main/scala/nutcore/mem/EmbeddedTLB.scala:256:25, :326:31, :328:50
      missMaskStore <= missMask;	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:257:26, :258:26, :275:18
    end
    if (|state) begin	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:253:22, :275:18
      if (_GEN | ~_GEN_3 | needFlush | ~_GEN_1 | _GEN_2) begin	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:262:18, :266:26, :275:18, :299:31, :300:24, :303:{49,82}, :304:{28,60}
      end
      else	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:262:18, :275:18
        raddr <=
          {io_mem_resp_bits_rdata[29:10],
           (&level) ? io_in_bits_addr[29:21] : io_in_bits_addr[20:12],
           3'h0};	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:198:54, :253:22, :254:22, :261:49, :262:18, :303:58, :317:50, src/main/scala/nutcore/mem/TLB.scala:89:8
    end
    else if (_GEN_10) begin	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:262:18, :277:32, :281:37
    end
    else	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:262:18, :277:32, :281:37
      raddr <= {io_satp[19:0], io_in_bits_addr[38:30], 3'h0};	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:198:54, :200:30, :253:22, :262:18, src/main/scala/nutcore/mem/TLB.scala:89:8
    REG_1 <= io_in_bits_addr[15:12];	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:379:21, src/main/scala/nutcore/mem/TLB.scala:200:19
    REG_2 <= waymask;	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:214:20, :379:60
    REG_3 <= io_in_bits_addr[38:12];	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:379:{84,89}
    REG_4 <= hitWB ? _hitMeta_T_10[41:26] : io_satp[59:44];	// src/main/scala/chisel3/util/Mux.scala:30:73, src/main/scala/nutcore/mem/EmbeddedTLB.scala:200:30, :220:70, :226:81, :380:{19,23}
    REG_5 <= hitWB ? _hitMeta_T_10[25:8] : missMask;	// src/main/scala/chisel3/util/Mux.scala:30:73, src/main/scala/nutcore/mem/EmbeddedTLB.scala:220:70, :226:81, :257:26, :275:18, :380:{72,76}
    REG_6 <= hitWB ? hitRefillFlag : missRefillFlag;	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:226:81, :227:69, :260:32, :275:18, :381:{19,23}
    REG_7 <= hitWB ? _hitData_T_10[51:32] : io_mem_resp_bits_rdata[29:10];	// src/main/scala/chisel3/util/Mux.scala:30:73, src/main/scala/nutcore/mem/EmbeddedTLB.scala:221:70, :226:81, :261:49, :381:{77,81}
    REG_8 <= io_mem_req_bits_addr_0;	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:373:35, :382:22
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:177:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:177:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:177:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:177:7
      automatic logic [31:0] _RANDOM[0:11];	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:177:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:177:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:177:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:177:7
        for (logic [3:0] i = 4'h0; i < 4'hC; i += 4'h1) begin
          _RANDOM[i] = `RANDOM;	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:177:7
        end	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:177:7
        victimWaymask_lfsr = {_RANDOM[4'h0], _RANDOM[4'h1]};	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:177:7, src/main/scala/utils/LFSR64.scala:25:23
        hitWBStore = {_RANDOM[4'h2], _RANDOM[4'h3][7:0]};	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:177:7, :228:29
        io_pf_loadPF_REG = _RANDOM[4'h3][8];	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:177:7, :228:29, :242:26
        io_pf_storePF_REG = _RANDOM[4'h3][9];	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:177:7, :228:29, :243:27
        state = _RANDOM[4'h3][12:10];	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:177:7, :228:29, :253:22
        level = _RANDOM[4'h3][14:13];	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:177:7, :228:29, :254:22
        memRespStore = {_RANDOM[4'h3][31:15], _RANDOM[4'h4], _RANDOM[4'h5][14:0]};	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:177:7, :228:29, :256:25
        missMaskStore = {_RANDOM[4'h5][31:15], _RANDOM[4'h6][0]};	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:177:7, :256:25, :258:26
        raddr = {_RANDOM[4'h6][31:1], _RANDOM[4'h7][0]};	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:177:7, :258:26, :262:18
        alreadyOutFire = _RANDOM[4'h7][1];	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:177:7, :262:18, :263:33
        needFlush = _RANDOM[4'h7][2];	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:177:7, :262:18, :266:26
        missIPF = _RANDOM[4'h7][3];	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:177:7, :262:18, :272:24
        REG = _RANDOM[4'h7][4];	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:177:7, :262:18, :378:33
        REG_1 = _RANDOM[4'h7][8:5];	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:177:7, :262:18, :379:21
        REG_2 = _RANDOM[4'h7][12:9];	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:177:7, :262:18, :379:60
        REG_3 = {_RANDOM[4'h7][31:13], _RANDOM[4'h8][7:0]};	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:177:7, :262:18, :379:84
        REG_4 = _RANDOM[4'h8][23:8];	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:177:7, :379:84, :380:19
        REG_5 = {_RANDOM[4'h8][31:24], _RANDOM[4'h9][9:0]};	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:177:7, :379:84, :380:72
        REG_6 = _RANDOM[4'h9][17:10];	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:177:7, :380:72, :381:19
        REG_7 = {_RANDOM[4'h9][31:18], _RANDOM[4'hA][5:0]};	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:177:7, :380:72, :381:77
        REG_8 = {_RANDOM[4'hA][31:6], _RANDOM[4'hB][5:0]};	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:177:7, :381:77, :382:22
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:177:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:177:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  LogPerfHelper LogPerfHelper (	// difftest/src/main/scala/common/LogPerfControl.scala:60:79
    .timer     (_LogPerfHelper_timer),
    .logEnable (_LogPerfHelper_logEnable),
    .clean     (/* unused */),
    .dump      (/* unused */)
  );
  LogPerfHelper LogPerfHelper_1 (	// difftest/src/main/scala/common/LogPerfControl.scala:60:79
    .timer     (_LogPerfHelper_1_timer),
    .logEnable (_LogPerfHelper_1_logEnable),
    .clean     (/* unused */),
    .dump      (/* unused */)
  );
  assign io_in_ready = io_in_ready_0;	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:177:7, :389:86
  assign io_out_valid = io_out_valid_0;	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:177:7, :387:31
  assign io_out_bits_addr = io_out_bits_addr_0;	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:177:7, :386:26
  assign io_out_bits_size = io_in_bits_size;	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:177:7
  assign io_out_bits_cmd = io_in_bits_cmd;	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:177:7
  assign io_out_bits_wmask = io_in_bits_wmask;	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:177:7
  assign io_out_bits_wdata = io_in_bits_wdata;	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:177:7
  assign io_mdWrite_wen = REG;	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:177:7, :378:33
  assign io_mdWrite_windex = REG_1;	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:177:7, :379:21
  assign io_mdWrite_waymask = REG_2;	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:177:7, :379:60
  assign io_mdWrite_wdata = {REG_3, REG_4, REG_5, REG_6, REG_7, REG_8};	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:177:7, :379:84, :380:{19,72}, :381:{19,77}, :382:22, src/main/scala/nutcore/mem/TLB.scala:217:22
  assign io_mem_req_valid = io_mem_req_valid_0;	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:177:7, :374:74
  assign io_mem_req_bits_addr = io_mem_req_bits_addr_0;	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:177:7, :373:35
  assign io_mem_req_bits_cmd = io_mem_req_bits_cmd_0;	// src/main/scala/bus/simplebus/SimpleBus.scala:65:14, src/main/scala/nutcore/mem/EmbeddedTLB.scala:177:7
  assign io_mem_req_bits_wdata = io_mem_req_bits_wdata_0;	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:177:7, :373:138
  assign io_pf_loadPF = io_pf_loadPF_REG;	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:177:7, :242:26
  assign io_pf_storePF = io_pf_storePF_REG;	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:177:7, :243:27
  assign io_pf_addr = io_in_bits_addr;	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:177:7
  assign io_isFinish = io_isFinish_0;	// src/main/scala/nutcore/mem/EmbeddedTLB.scala:177:7, :392:30
endmodule

