// Generated by CIRCT firtool-1.62.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for prints and assertions.

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module SimpleBusCrossbar1toN_1(	// src/main/scala/bus/simplebus/Crossbar.scala:25:7
  input         clock,	// src/main/scala/bus/simplebus/Crossbar.scala:25:7
                reset,	// src/main/scala/bus/simplebus/Crossbar.scala:25:7
  output        io_in_req_ready,	// src/main/scala/bus/simplebus/Crossbar.scala:26:14
  input         io_in_req_valid,	// src/main/scala/bus/simplebus/Crossbar.scala:26:14
  input  [31:0] io_in_req_bits_addr,	// src/main/scala/bus/simplebus/Crossbar.scala:26:14
  input  [2:0]  io_in_req_bits_size,	// src/main/scala/bus/simplebus/Crossbar.scala:26:14
  input  [3:0]  io_in_req_bits_cmd,	// src/main/scala/bus/simplebus/Crossbar.scala:26:14
  input  [7:0]  io_in_req_bits_wmask,	// src/main/scala/bus/simplebus/Crossbar.scala:26:14
  input  [63:0] io_in_req_bits_wdata,	// src/main/scala/bus/simplebus/Crossbar.scala:26:14
  input         io_in_resp_ready,	// src/main/scala/bus/simplebus/Crossbar.scala:26:14
  output        io_in_resp_valid,	// src/main/scala/bus/simplebus/Crossbar.scala:26:14
  output [3:0]  io_in_resp_bits_cmd,	// src/main/scala/bus/simplebus/Crossbar.scala:26:14
  output [63:0] io_in_resp_bits_rdata,	// src/main/scala/bus/simplebus/Crossbar.scala:26:14
  input         io_out_0_req_ready,	// src/main/scala/bus/simplebus/Crossbar.scala:26:14
  output        io_out_0_req_valid,	// src/main/scala/bus/simplebus/Crossbar.scala:26:14
  output [31:0] io_out_0_req_bits_addr,	// src/main/scala/bus/simplebus/Crossbar.scala:26:14
  output [3:0]  io_out_0_req_bits_cmd,	// src/main/scala/bus/simplebus/Crossbar.scala:26:14
  output [7:0]  io_out_0_req_bits_wmask,	// src/main/scala/bus/simplebus/Crossbar.scala:26:14
  output [63:0] io_out_0_req_bits_wdata,	// src/main/scala/bus/simplebus/Crossbar.scala:26:14
  output        io_out_0_resp_ready,	// src/main/scala/bus/simplebus/Crossbar.scala:26:14
  input         io_out_0_resp_valid,	// src/main/scala/bus/simplebus/Crossbar.scala:26:14
  input  [63:0] io_out_0_resp_bits_rdata,	// src/main/scala/bus/simplebus/Crossbar.scala:26:14
  input         io_out_1_req_ready,	// src/main/scala/bus/simplebus/Crossbar.scala:26:14
  output        io_out_1_req_valid,	// src/main/scala/bus/simplebus/Crossbar.scala:26:14
  output [31:0] io_out_1_req_bits_addr,	// src/main/scala/bus/simplebus/Crossbar.scala:26:14
  output [3:0]  io_out_1_req_bits_cmd,	// src/main/scala/bus/simplebus/Crossbar.scala:26:14
  output [7:0]  io_out_1_req_bits_wmask,	// src/main/scala/bus/simplebus/Crossbar.scala:26:14
  output [63:0] io_out_1_req_bits_wdata,	// src/main/scala/bus/simplebus/Crossbar.scala:26:14
  output        io_out_1_resp_ready,	// src/main/scala/bus/simplebus/Crossbar.scala:26:14
  input         io_out_1_resp_valid,	// src/main/scala/bus/simplebus/Crossbar.scala:26:14
  input  [63:0] io_out_1_resp_bits_rdata,	// src/main/scala/bus/simplebus/Crossbar.scala:26:14
  input         io_out_2_req_ready,	// src/main/scala/bus/simplebus/Crossbar.scala:26:14
  output        io_out_2_req_valid,	// src/main/scala/bus/simplebus/Crossbar.scala:26:14
  output [31:0] io_out_2_req_bits_addr,	// src/main/scala/bus/simplebus/Crossbar.scala:26:14
  output [3:0]  io_out_2_req_bits_cmd,	// src/main/scala/bus/simplebus/Crossbar.scala:26:14
  output [7:0]  io_out_2_req_bits_wmask,	// src/main/scala/bus/simplebus/Crossbar.scala:26:14
  output [63:0] io_out_2_req_bits_wdata,	// src/main/scala/bus/simplebus/Crossbar.scala:26:14
  output        io_out_2_resp_ready,	// src/main/scala/bus/simplebus/Crossbar.scala:26:14
  input         io_out_2_resp_valid,	// src/main/scala/bus/simplebus/Crossbar.scala:26:14
  input  [63:0] io_out_2_resp_bits_rdata,	// src/main/scala/bus/simplebus/Crossbar.scala:26:14
  input         io_out_3_req_ready,	// src/main/scala/bus/simplebus/Crossbar.scala:26:14
  output        io_out_3_req_valid,	// src/main/scala/bus/simplebus/Crossbar.scala:26:14
  output [31:0] io_out_3_req_bits_addr,	// src/main/scala/bus/simplebus/Crossbar.scala:26:14
  output [3:0]  io_out_3_req_bits_cmd,	// src/main/scala/bus/simplebus/Crossbar.scala:26:14
  output [7:0]  io_out_3_req_bits_wmask,	// src/main/scala/bus/simplebus/Crossbar.scala:26:14
  output [63:0] io_out_3_req_bits_wdata,	// src/main/scala/bus/simplebus/Crossbar.scala:26:14
  output        io_out_3_resp_ready,	// src/main/scala/bus/simplebus/Crossbar.scala:26:14
  input         io_out_3_resp_valid,	// src/main/scala/bus/simplebus/Crossbar.scala:26:14
  input  [63:0] io_out_3_resp_bits_rdata,	// src/main/scala/bus/simplebus/Crossbar.scala:26:14
  input         io_out_4_req_ready,	// src/main/scala/bus/simplebus/Crossbar.scala:26:14
  output        io_out_4_req_valid,	// src/main/scala/bus/simplebus/Crossbar.scala:26:14
  output [31:0] io_out_4_req_bits_addr,	// src/main/scala/bus/simplebus/Crossbar.scala:26:14
  output [3:0]  io_out_4_req_bits_cmd,	// src/main/scala/bus/simplebus/Crossbar.scala:26:14
  output [7:0]  io_out_4_req_bits_wmask,	// src/main/scala/bus/simplebus/Crossbar.scala:26:14
  output [63:0] io_out_4_req_bits_wdata,	// src/main/scala/bus/simplebus/Crossbar.scala:26:14
  output        io_out_4_resp_ready,	// src/main/scala/bus/simplebus/Crossbar.scala:26:14
  input         io_out_4_resp_valid,	// src/main/scala/bus/simplebus/Crossbar.scala:26:14
  input  [63:0] io_out_4_resp_bits_rdata,	// src/main/scala/bus/simplebus/Crossbar.scala:26:14
  input         io_out_5_req_ready,	// src/main/scala/bus/simplebus/Crossbar.scala:26:14
  output        io_out_5_req_valid,	// src/main/scala/bus/simplebus/Crossbar.scala:26:14
  output [31:0] io_out_5_req_bits_addr,	// src/main/scala/bus/simplebus/Crossbar.scala:26:14
  output [3:0]  io_out_5_req_bits_cmd,	// src/main/scala/bus/simplebus/Crossbar.scala:26:14
  output [7:0]  io_out_5_req_bits_wmask,	// src/main/scala/bus/simplebus/Crossbar.scala:26:14
  output [63:0] io_out_5_req_bits_wdata,	// src/main/scala/bus/simplebus/Crossbar.scala:26:14
  output        io_out_5_resp_ready,	// src/main/scala/bus/simplebus/Crossbar.scala:26:14
  input         io_out_5_resp_valid,	// src/main/scala/bus/simplebus/Crossbar.scala:26:14
  input  [63:0] io_out_5_resp_bits_rdata,	// src/main/scala/bus/simplebus/Crossbar.scala:26:14
  input         io_out_6_req_ready,	// src/main/scala/bus/simplebus/Crossbar.scala:26:14
  output        io_out_6_req_valid,	// src/main/scala/bus/simplebus/Crossbar.scala:26:14
  output [31:0] io_out_6_req_bits_addr,	// src/main/scala/bus/simplebus/Crossbar.scala:26:14
  output [3:0]  io_out_6_req_bits_cmd,	// src/main/scala/bus/simplebus/Crossbar.scala:26:14
  output [7:0]  io_out_6_req_bits_wmask,	// src/main/scala/bus/simplebus/Crossbar.scala:26:14
  output [63:0] io_out_6_req_bits_wdata,	// src/main/scala/bus/simplebus/Crossbar.scala:26:14
  output        io_out_6_resp_ready,	// src/main/scala/bus/simplebus/Crossbar.scala:26:14
  input         io_out_6_resp_valid,	// src/main/scala/bus/simplebus/Crossbar.scala:26:14
  input  [63:0] io_out_6_resp_bits_rdata	// src/main/scala/bus/simplebus/Crossbar.scala:26:14
);

  wire        io_in_resp_valid_0;	// src/main/scala/bus/simplebus/Crossbar.scala:71:70
  wire        io_in_req_ready_0;	// src/main/scala/bus/simplebus/Crossbar.scala:61:64
  wire        _LogPerfHelper_1_logEnable;	// difftest/src/main/scala/common/LogPerfControl.scala:60:79
  wire        _LogPerfHelper_logEnable;	// difftest/src/main/scala/common/LogPerfControl.scala:60:79
  reg  [1:0]  state;	// src/main/scala/bus/simplebus/Crossbar.scala:32:22
  wire [6:0]  outSelVec_enc =
    io_in_req_bits_addr > 32'h405FFFFF & io_in_req_bits_addr < 32'h40600010
      ? 7'h1
      : io_in_req_bits_addr > 32'h4FFFFFFF & io_in_req_bits_addr < 32'h50400000
          ? 7'h2
          : io_in_req_bits_addr > 32'h40000FFF & io_in_req_bits_addr < 32'h40001008
              ? 7'h4
              : (|(io_in_req_bits_addr[31:30])) & io_in_req_bits_addr < 32'h40001000
                  ? 7'h8
                  : io_in_req_bits_addr > 32'h40001FFF
                    & io_in_req_bits_addr < 32'h40003000
                      ? 7'h10
                      : io_in_req_bits_addr > 32'h40003FFF
                        & io_in_req_bits_addr < 32'h40005000
                          ? 7'h20
                          : {io_in_req_bits_addr > 32'h40002FFF
                               & io_in_req_bits_addr < 32'h40004000,
                             6'h0};	// src/main/scala/bus/simplebus/Crossbar.scala:37:{20,34,42}, src/main/scala/chisel3/util/Mux.scala:50:70
  wire        _outSelRespVec_T = io_in_req_ready_0 & io_in_req_valid;	// src/main/scala/bus/simplebus/Crossbar.scala:61:64, src/main/scala/chisel3/util/Decoupled.scala:51:35
  reg         outSelRespVec_0;	// src/main/scala/bus/simplebus/Crossbar.scala:39:32
  reg         outSelRespVec_1;	// src/main/scala/bus/simplebus/Crossbar.scala:39:32
  reg         outSelRespVec_2;	// src/main/scala/bus/simplebus/Crossbar.scala:39:32
  reg         outSelRespVec_3;	// src/main/scala/bus/simplebus/Crossbar.scala:39:32
  reg         outSelRespVec_4;	// src/main/scala/bus/simplebus/Crossbar.scala:39:32
  reg         outSelRespVec_5;	// src/main/scala/bus/simplebus/Crossbar.scala:39:32
  reg         outSelRespVec_6;	// src/main/scala/bus/simplebus/Crossbar.scala:39:32
  wire        reqInvalidAddr = io_in_req_valid & outSelVec_enc == 7'h0;	// src/main/scala/bus/simplebus/Crossbar.scala:42:{40,61}, src/main/scala/chisel3/util/Mux.scala:50:70
  reg  [63:0] c;	// src/main/scala/utils/GTimer.scala:24:20
  wire        _GEN = io_in_resp_ready & io_in_resp_valid_0;	// src/main/scala/bus/simplebus/Crossbar.scala:71:70, src/main/scala/chisel3/util/Decoupled.scala:51:35
  assign io_in_req_ready_0 =
    outSelVec_enc[0] & io_out_0_req_ready | outSelVec_enc[1] & io_out_1_req_ready
    | outSelVec_enc[2] & io_out_2_req_ready | outSelVec_enc[3] & io_out_3_req_ready
    | outSelVec_enc[4] & io_out_4_req_ready | outSelVec_enc[5] & io_out_5_req_ready
    | outSelVec_enc[6] & io_out_6_req_ready | reqInvalidAddr;	// src/main/scala/bus/simplebus/Crossbar.scala:42:40, :61:64, src/main/scala/chisel3/util/Mux.scala:30:73, :50:70, src/main/scala/chisel3/util/OneHot.scala:83:30
  wire        _io_out_6_resp_ready_T_1 = state == 2'h1;	// src/main/scala/bus/simplebus/Crossbar.scala:32:22, :53:37, :69:75
  assign io_in_resp_valid_0 =
    outSelRespVec_0 & io_out_0_resp_valid | outSelRespVec_1 & io_out_1_resp_valid
    | outSelRespVec_2 & io_out_2_resp_valid | outSelRespVec_3 & io_out_3_resp_valid
    | outSelRespVec_4 & io_out_4_resp_valid | outSelRespVec_5 & io_out_5_resp_valid
    | outSelRespVec_6 & io_out_6_resp_valid | state == 2'h2;	// src/main/scala/bus/simplebus/Crossbar.scala:32:22, :39:32, :54:37, :71:{70,79}, src/main/scala/chisel3/util/Mux.scala:30:73
  wire [63:0] _io_in_resp_bits_T_12 =
    (outSelRespVec_0 ? io_out_0_resp_bits_rdata : 64'h0)
    | (outSelRespVec_1 ? io_out_1_resp_bits_rdata : 64'h0)
    | (outSelRespVec_2 ? io_out_2_resp_bits_rdata : 64'h0)
    | (outSelRespVec_3 ? io_out_3_resp_bits_rdata : 64'h0)
    | (outSelRespVec_4 ? io_out_4_resp_bits_rdata : 64'h0)
    | (outSelRespVec_5 ? io_out_5_resp_bits_rdata : 64'h0)
    | (outSelRespVec_6 ? io_out_6_resp_bits_rdata : 64'h0);	// src/main/scala/bus/simplebus/Crossbar.scala:39:32, src/main/scala/chisel3/util/Mux.scala:30:73, src/main/scala/utils/GTimer.scala:24:20
  wire [3:0]  _io_in_resp_bits_T_25 =
    outSelRespVec_0 | outSelRespVec_1 | outSelRespVec_2 | outSelRespVec_3
    | outSelRespVec_4 | outSelRespVec_5 | outSelRespVec_6
      ? 4'h6
      : 4'h0;	// src/main/scala/bus/simplebus/Crossbar.scala:26:14, :39:32, src/main/scala/chisel3/util/Mux.scala:30:73
  reg  [63:0] c_1;	// src/main/scala/utils/GTimer.scala:24:20
  reg  [63:0] c_2;	// src/main/scala/utils/GTimer.scala:24:20
  `ifndef SYNTHESIS	// src/main/scala/bus/simplebus/Crossbar.scala:46:13
    always @(posedge clock) begin	// src/main/scala/bus/simplebus/Crossbar.scala:46:13
      if ((`PRINTF_COND_) & reqInvalidAddr & _LogPerfHelper_logEnable & ~reset)	// difftest/src/main/scala/common/LogPerfControl.scala:60:79, src/main/scala/bus/simplebus/Crossbar.scala:42:40, :46:13
        $fwrite(32'h80000002, "crossbar access bad addr %x, time %d\n",
                io_in_req_bits_addr, c);	// src/main/scala/bus/simplebus/Crossbar.scala:46:13, src/main/scala/utils/GTimer.scala:24:20
      if (~reset & reqInvalidAddr) begin	// src/main/scala/bus/simplebus/Crossbar.scala:42:40, :46:13, :49:9
        if (`ASSERT_VERBOSE_COND_)	// src/main/scala/bus/simplebus/Crossbar.scala:49:9
          $error("Assertion failed: address decode error, bad addr = 0x%x\n\n    at Crossbar.scala:49 assert(!reqInvalidAddr, \"address decode error, bad addr = 0x%%%%x\\n\", addr)\n",
                 io_in_req_bits_addr);	// src/main/scala/bus/simplebus/Crossbar.scala:49:9
        if (`STOP_COND_)	// src/main/scala/bus/simplebus/Crossbar.scala:49:9
          $fatal;	// src/main/scala/bus/simplebus/Crossbar.scala:49:9
      end
      if ((`PRINTF_COND_) & _LogPerfHelper_1_logEnable & _outSelRespVec_T & ~reset)	// difftest/src/main/scala/common/LogPerfControl.scala:60:79, src/main/scala/bus/simplebus/Crossbar.scala:46:13, :77:13, src/main/scala/chisel3/util/Decoupled.scala:51:35
        $fwrite(32'h80000002,
                "%d: xbar: outSelVec = Vec(%d, %d, %d, %d, %d, %d, %d), outSel.req: addr = 0x%x, cmd = %d, size = %d, wmask = 0x%x, wdata = 0x%x\n",
                c_1, outSelVec_enc[0], outSelVec_enc[1], outSelVec_enc[2],
                outSelVec_enc[3], outSelVec_enc[4], outSelVec_enc[5], outSelVec_enc[6],
                io_in_req_bits_addr, io_in_req_bits_cmd, io_in_req_bits_size,
                io_in_req_bits_wmask, io_in_req_bits_wdata);	// src/main/scala/bus/simplebus/Crossbar.scala:46:13, :77:13, src/main/scala/chisel3/util/Mux.scala:50:70, src/main/scala/chisel3/util/OneHot.scala:83:30, src/main/scala/utils/GTimer.scala:24:20
      if ((`PRINTF_COND_) & _LogPerfHelper_1_logEnable & _GEN & ~reset)	// difftest/src/main/scala/common/LogPerfControl.scala:60:79, src/main/scala/bus/simplebus/Crossbar.scala:46:13, :80:13, src/main/scala/chisel3/util/Decoupled.scala:51:35
        $fwrite(32'h80000002,
                "%d: xbar: outSelVec = Vec(%d, %d, %d, %d, %d, %d, %d), outSel.resp: rdata = %x, cmd = %d\n",
                c_2, outSelVec_enc[0], outSelVec_enc[1], outSelVec_enc[2],
                outSelVec_enc[3], outSelVec_enc[4], outSelVec_enc[5], outSelVec_enc[6],
                _io_in_resp_bits_T_12, _io_in_resp_bits_T_25);	// src/main/scala/bus/simplebus/Crossbar.scala:46:13, :80:13, src/main/scala/chisel3/util/Mux.scala:30:73, :50:70, src/main/scala/chisel3/util/OneHot.scala:83:30, src/main/scala/utils/GTimer.scala:24:20
    end // always @(posedge)
  `endif // not def SYNTHESIS
  always @(posedge clock) begin	// src/main/scala/bus/simplebus/Crossbar.scala:25:7
    if (reset) begin	// src/main/scala/bus/simplebus/Crossbar.scala:25:7
      state <= 2'h0;	// src/main/scala/bus/simplebus/Crossbar.scala:32:22
      outSelRespVec_0 <= 1'h0;	// src/main/scala/bus/simplebus/Crossbar.scala:39:32, :40:40
      outSelRespVec_1 <= 1'h0;	// src/main/scala/bus/simplebus/Crossbar.scala:39:32, :40:40
      outSelRespVec_2 <= 1'h0;	// src/main/scala/bus/simplebus/Crossbar.scala:39:32, :40:40
      outSelRespVec_3 <= 1'h0;	// src/main/scala/bus/simplebus/Crossbar.scala:39:32, :40:40
      outSelRespVec_4 <= 1'h0;	// src/main/scala/bus/simplebus/Crossbar.scala:39:32, :40:40
      outSelRespVec_5 <= 1'h0;	// src/main/scala/bus/simplebus/Crossbar.scala:39:32, :40:40
      outSelRespVec_6 <= 1'h0;	// src/main/scala/bus/simplebus/Crossbar.scala:39:32, :40:40
      c <= 64'h0;	// src/main/scala/utils/GTimer.scala:24:20
      c_1 <= 64'h0;	// src/main/scala/utils/GTimer.scala:24:20
      c_2 <= 64'h0;	// src/main/scala/utils/GTimer.scala:24:20
    end
    else begin	// src/main/scala/bus/simplebus/Crossbar.scala:25:7
      if (|state) begin	// src/main/scala/bus/simplebus/Crossbar.scala:32:22, :41:57
        if ((state == 2'h1 | state == 2'h2) & _GEN)	// src/main/scala/bus/simplebus/Crossbar.scala:32:22, :51:18, :53:37, :54:37, :56:{42,50}, :57:{43,51}, src/main/scala/chisel3/util/Decoupled.scala:51:35
          state <= 2'h0;	// src/main/scala/bus/simplebus/Crossbar.scala:32:22
      end
      else if (reqInvalidAddr)	// src/main/scala/bus/simplebus/Crossbar.scala:42:40
        state <= 2'h2;	// src/main/scala/bus/simplebus/Crossbar.scala:32:22, :54:37
      else if (_outSelRespVec_T)	// src/main/scala/chisel3/util/Decoupled.scala:51:35
        state <= 2'h1;	// src/main/scala/bus/simplebus/Crossbar.scala:32:22, :53:37
      if (_outSelRespVec_T & ~(|state)) begin	// src/main/scala/bus/simplebus/Crossbar.scala:32:22, :41:{48,57}, src/main/scala/chisel3/util/Decoupled.scala:51:35
        outSelRespVec_0 <= outSelVec_enc[0];	// src/main/scala/bus/simplebus/Crossbar.scala:39:32, src/main/scala/chisel3/util/Mux.scala:50:70, src/main/scala/chisel3/util/OneHot.scala:83:30
        outSelRespVec_1 <= outSelVec_enc[1];	// src/main/scala/bus/simplebus/Crossbar.scala:39:32, src/main/scala/chisel3/util/Mux.scala:50:70, src/main/scala/chisel3/util/OneHot.scala:83:30
        outSelRespVec_2 <= outSelVec_enc[2];	// src/main/scala/bus/simplebus/Crossbar.scala:39:32, src/main/scala/chisel3/util/Mux.scala:50:70, src/main/scala/chisel3/util/OneHot.scala:83:30
        outSelRespVec_3 <= outSelVec_enc[3];	// src/main/scala/bus/simplebus/Crossbar.scala:39:32, src/main/scala/chisel3/util/Mux.scala:50:70, src/main/scala/chisel3/util/OneHot.scala:83:30
        outSelRespVec_4 <= outSelVec_enc[4];	// src/main/scala/bus/simplebus/Crossbar.scala:39:32, src/main/scala/chisel3/util/Mux.scala:50:70, src/main/scala/chisel3/util/OneHot.scala:83:30
        outSelRespVec_5 <= outSelVec_enc[5];	// src/main/scala/bus/simplebus/Crossbar.scala:39:32, src/main/scala/chisel3/util/Mux.scala:50:70, src/main/scala/chisel3/util/OneHot.scala:83:30
        outSelRespVec_6 <= outSelVec_enc[6];	// src/main/scala/bus/simplebus/Crossbar.scala:39:32, src/main/scala/chisel3/util/Mux.scala:50:70, src/main/scala/chisel3/util/OneHot.scala:83:30
      end
      c <= c + 64'h1;	// src/main/scala/utils/GTimer.scala:24:20, :25:12
      c_1 <= c_1 + 64'h1;	// src/main/scala/utils/GTimer.scala:24:20, :25:12
      c_2 <= c_2 + 64'h1;	// src/main/scala/utils/GTimer.scala:24:20, :25:12
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/bus/simplebus/Crossbar.scala:25:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/bus/simplebus/Crossbar.scala:25:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/bus/simplebus/Crossbar.scala:25:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// src/main/scala/bus/simplebus/Crossbar.scala:25:7
      automatic logic [31:0] _RANDOM[0:6];	// src/main/scala/bus/simplebus/Crossbar.scala:25:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/bus/simplebus/Crossbar.scala:25:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/bus/simplebus/Crossbar.scala:25:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/bus/simplebus/Crossbar.scala:25:7
        for (logic [2:0] i = 3'h0; i < 3'h7; i += 3'h1) begin
          _RANDOM[i] = `RANDOM;	// src/main/scala/bus/simplebus/Crossbar.scala:25:7
        end	// src/main/scala/bus/simplebus/Crossbar.scala:25:7
        state = _RANDOM[3'h0][1:0];	// src/main/scala/bus/simplebus/Crossbar.scala:25:7, :32:22
        outSelRespVec_0 = _RANDOM[3'h0][2];	// src/main/scala/bus/simplebus/Crossbar.scala:25:7, :32:22, :39:32
        outSelRespVec_1 = _RANDOM[3'h0][3];	// src/main/scala/bus/simplebus/Crossbar.scala:25:7, :32:22, :39:32
        outSelRespVec_2 = _RANDOM[3'h0][4];	// src/main/scala/bus/simplebus/Crossbar.scala:25:7, :32:22, :39:32
        outSelRespVec_3 = _RANDOM[3'h0][5];	// src/main/scala/bus/simplebus/Crossbar.scala:25:7, :32:22, :39:32
        outSelRespVec_4 = _RANDOM[3'h0][6];	// src/main/scala/bus/simplebus/Crossbar.scala:25:7, :32:22, :39:32
        outSelRespVec_5 = _RANDOM[3'h0][7];	// src/main/scala/bus/simplebus/Crossbar.scala:25:7, :32:22, :39:32
        outSelRespVec_6 = _RANDOM[3'h0][8];	// src/main/scala/bus/simplebus/Crossbar.scala:25:7, :32:22, :39:32
        c = {_RANDOM[3'h0][31:9], _RANDOM[3'h1], _RANDOM[3'h2][8:0]};	// src/main/scala/bus/simplebus/Crossbar.scala:25:7, :32:22, src/main/scala/utils/GTimer.scala:24:20
        c_1 = {_RANDOM[3'h2][31:9], _RANDOM[3'h3], _RANDOM[3'h4][8:0]};	// src/main/scala/bus/simplebus/Crossbar.scala:25:7, src/main/scala/utils/GTimer.scala:24:20
        c_2 = {_RANDOM[3'h4][31:9], _RANDOM[3'h5], _RANDOM[3'h6][8:0]};	// src/main/scala/bus/simplebus/Crossbar.scala:25:7, src/main/scala/utils/GTimer.scala:24:20
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/bus/simplebus/Crossbar.scala:25:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/bus/simplebus/Crossbar.scala:25:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  LogPerfHelper LogPerfHelper (	// difftest/src/main/scala/common/LogPerfControl.scala:60:79
    .timer     (/* unused */),
    .logEnable (_LogPerfHelper_logEnable),
    .clean     (/* unused */),
    .dump      (/* unused */)
  );
  LogPerfHelper LogPerfHelper_1 (	// difftest/src/main/scala/common/LogPerfControl.scala:60:79
    .timer     (/* unused */),
    .logEnable (_LogPerfHelper_1_logEnable),
    .clean     (/* unused */),
    .dump      (/* unused */)
  );
  assign io_in_req_ready = io_in_req_ready_0;	// src/main/scala/bus/simplebus/Crossbar.scala:25:7, :61:64
  assign io_in_resp_valid = io_in_resp_valid_0;	// src/main/scala/bus/simplebus/Crossbar.scala:25:7, :71:70
  assign io_in_resp_bits_cmd = _io_in_resp_bits_T_25;	// src/main/scala/bus/simplebus/Crossbar.scala:25:7, src/main/scala/chisel3/util/Mux.scala:30:73
  assign io_in_resp_bits_rdata = _io_in_resp_bits_T_12;	// src/main/scala/bus/simplebus/Crossbar.scala:25:7, src/main/scala/chisel3/util/Mux.scala:30:73
  assign io_out_0_req_valid = outSelVec_enc[0] & io_in_req_valid & ~(|state);	// src/main/scala/bus/simplebus/Crossbar.scala:25:7, :32:22, :41:57, :63:60, src/main/scala/chisel3/util/Mux.scala:50:70, src/main/scala/chisel3/util/OneHot.scala:83:30
  assign io_out_0_req_bits_addr = io_in_req_bits_addr;	// src/main/scala/bus/simplebus/Crossbar.scala:25:7
  assign io_out_0_req_bits_cmd = io_in_req_bits_cmd;	// src/main/scala/bus/simplebus/Crossbar.scala:25:7
  assign io_out_0_req_bits_wmask = io_in_req_bits_wmask;	// src/main/scala/bus/simplebus/Crossbar.scala:25:7
  assign io_out_0_req_bits_wdata = io_in_req_bits_wdata;	// src/main/scala/bus/simplebus/Crossbar.scala:25:7
  assign io_out_0_resp_ready =
    outSelRespVec_0 & io_in_resp_ready & _io_out_6_resp_ready_T_1;	// src/main/scala/bus/simplebus/Crossbar.scala:25:7, :39:32, :69:{66,75}
  assign io_out_1_req_valid = outSelVec_enc[1] & io_in_req_valid & ~(|state);	// src/main/scala/bus/simplebus/Crossbar.scala:25:7, :32:22, :41:57, :63:60, src/main/scala/chisel3/util/Mux.scala:50:70, src/main/scala/chisel3/util/OneHot.scala:83:30
  assign io_out_1_req_bits_addr = io_in_req_bits_addr;	// src/main/scala/bus/simplebus/Crossbar.scala:25:7
  assign io_out_1_req_bits_cmd = io_in_req_bits_cmd;	// src/main/scala/bus/simplebus/Crossbar.scala:25:7
  assign io_out_1_req_bits_wmask = io_in_req_bits_wmask;	// src/main/scala/bus/simplebus/Crossbar.scala:25:7
  assign io_out_1_req_bits_wdata = io_in_req_bits_wdata;	// src/main/scala/bus/simplebus/Crossbar.scala:25:7
  assign io_out_1_resp_ready =
    outSelRespVec_1 & io_in_resp_ready & _io_out_6_resp_ready_T_1;	// src/main/scala/bus/simplebus/Crossbar.scala:25:7, :39:32, :69:{66,75}
  assign io_out_2_req_valid = outSelVec_enc[2] & io_in_req_valid & ~(|state);	// src/main/scala/bus/simplebus/Crossbar.scala:25:7, :32:22, :41:57, :63:60, src/main/scala/chisel3/util/Mux.scala:50:70, src/main/scala/chisel3/util/OneHot.scala:83:30
  assign io_out_2_req_bits_addr = io_in_req_bits_addr;	// src/main/scala/bus/simplebus/Crossbar.scala:25:7
  assign io_out_2_req_bits_cmd = io_in_req_bits_cmd;	// src/main/scala/bus/simplebus/Crossbar.scala:25:7
  assign io_out_2_req_bits_wmask = io_in_req_bits_wmask;	// src/main/scala/bus/simplebus/Crossbar.scala:25:7
  assign io_out_2_req_bits_wdata = io_in_req_bits_wdata;	// src/main/scala/bus/simplebus/Crossbar.scala:25:7
  assign io_out_2_resp_ready =
    outSelRespVec_2 & io_in_resp_ready & _io_out_6_resp_ready_T_1;	// src/main/scala/bus/simplebus/Crossbar.scala:25:7, :39:32, :69:{66,75}
  assign io_out_3_req_valid = outSelVec_enc[3] & io_in_req_valid & ~(|state);	// src/main/scala/bus/simplebus/Crossbar.scala:25:7, :32:22, :41:57, :63:60, src/main/scala/chisel3/util/Mux.scala:50:70, src/main/scala/chisel3/util/OneHot.scala:83:30
  assign io_out_3_req_bits_addr = io_in_req_bits_addr;	// src/main/scala/bus/simplebus/Crossbar.scala:25:7
  assign io_out_3_req_bits_cmd = io_in_req_bits_cmd;	// src/main/scala/bus/simplebus/Crossbar.scala:25:7
  assign io_out_3_req_bits_wmask = io_in_req_bits_wmask;	// src/main/scala/bus/simplebus/Crossbar.scala:25:7
  assign io_out_3_req_bits_wdata = io_in_req_bits_wdata;	// src/main/scala/bus/simplebus/Crossbar.scala:25:7
  assign io_out_3_resp_ready =
    outSelRespVec_3 & io_in_resp_ready & _io_out_6_resp_ready_T_1;	// src/main/scala/bus/simplebus/Crossbar.scala:25:7, :39:32, :69:{66,75}
  assign io_out_4_req_valid = outSelVec_enc[4] & io_in_req_valid & ~(|state);	// src/main/scala/bus/simplebus/Crossbar.scala:25:7, :32:22, :41:57, :63:60, src/main/scala/chisel3/util/Mux.scala:50:70, src/main/scala/chisel3/util/OneHot.scala:83:30
  assign io_out_4_req_bits_addr = io_in_req_bits_addr;	// src/main/scala/bus/simplebus/Crossbar.scala:25:7
  assign io_out_4_req_bits_cmd = io_in_req_bits_cmd;	// src/main/scala/bus/simplebus/Crossbar.scala:25:7
  assign io_out_4_req_bits_wmask = io_in_req_bits_wmask;	// src/main/scala/bus/simplebus/Crossbar.scala:25:7
  assign io_out_4_req_bits_wdata = io_in_req_bits_wdata;	// src/main/scala/bus/simplebus/Crossbar.scala:25:7
  assign io_out_4_resp_ready =
    outSelRespVec_4 & io_in_resp_ready & _io_out_6_resp_ready_T_1;	// src/main/scala/bus/simplebus/Crossbar.scala:25:7, :39:32, :69:{66,75}
  assign io_out_5_req_valid = outSelVec_enc[5] & io_in_req_valid & ~(|state);	// src/main/scala/bus/simplebus/Crossbar.scala:25:7, :32:22, :41:57, :63:60, src/main/scala/chisel3/util/Mux.scala:50:70, src/main/scala/chisel3/util/OneHot.scala:83:30
  assign io_out_5_req_bits_addr = io_in_req_bits_addr;	// src/main/scala/bus/simplebus/Crossbar.scala:25:7
  assign io_out_5_req_bits_cmd = io_in_req_bits_cmd;	// src/main/scala/bus/simplebus/Crossbar.scala:25:7
  assign io_out_5_req_bits_wmask = io_in_req_bits_wmask;	// src/main/scala/bus/simplebus/Crossbar.scala:25:7
  assign io_out_5_req_bits_wdata = io_in_req_bits_wdata;	// src/main/scala/bus/simplebus/Crossbar.scala:25:7
  assign io_out_5_resp_ready =
    outSelRespVec_5 & io_in_resp_ready & _io_out_6_resp_ready_T_1;	// src/main/scala/bus/simplebus/Crossbar.scala:25:7, :39:32, :69:{66,75}
  assign io_out_6_req_valid = outSelVec_enc[6] & io_in_req_valid & ~(|state);	// src/main/scala/bus/simplebus/Crossbar.scala:25:7, :32:22, :41:57, :63:60, src/main/scala/chisel3/util/Mux.scala:50:70, src/main/scala/chisel3/util/OneHot.scala:83:30
  assign io_out_6_req_bits_addr = io_in_req_bits_addr;	// src/main/scala/bus/simplebus/Crossbar.scala:25:7
  assign io_out_6_req_bits_cmd = io_in_req_bits_cmd;	// src/main/scala/bus/simplebus/Crossbar.scala:25:7
  assign io_out_6_req_bits_wmask = io_in_req_bits_wmask;	// src/main/scala/bus/simplebus/Crossbar.scala:25:7
  assign io_out_6_req_bits_wdata = io_in_req_bits_wdata;	// src/main/scala/bus/simplebus/Crossbar.scala:25:7
  assign io_out_6_resp_ready =
    outSelRespVec_6 & io_in_resp_ready & _io_out_6_resp_ready_T_1;	// src/main/scala/bus/simplebus/Crossbar.scala:25:7, :39:32, :69:{66,75}
endmodule

