// Generated by CIRCT firtool-1.62.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for prints and assertions.

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module CSR(	// src/main/scala/nutcore/backend/fu/CSR.scala:192:7
  input         clock,	// src/main/scala/nutcore/backend/fu/CSR.scala:192:7
                reset,	// src/main/scala/nutcore/backend/fu/CSR.scala:192:7
                io_in_valid,	// src/main/scala/nutcore/backend/fu/CSR.scala:193:14
  input  [63:0] io_in_bits_src1,	// src/main/scala/nutcore/backend/fu/CSR.scala:193:14
                io_in_bits_src2,	// src/main/scala/nutcore/backend/fu/CSR.scala:193:14
  input  [6:0]  io_in_bits_func,	// src/main/scala/nutcore/backend/fu/CSR.scala:193:14
  output        io_out_valid,	// src/main/scala/nutcore/backend/fu/CSR.scala:193:14
  output [63:0] io_out_bits,	// src/main/scala/nutcore/backend/fu/CSR.scala:193:14
  input  [63:0] io_cfIn_instr,	// src/main/scala/nutcore/backend/fu/CSR.scala:193:14
  input  [38:0] io_cfIn_pc,	// src/main/scala/nutcore/backend/fu/CSR.scala:193:14
  input         io_cfIn_exceptionVec_0,	// src/main/scala/nutcore/backend/fu/CSR.scala:193:14
                io_cfIn_exceptionVec_1,	// src/main/scala/nutcore/backend/fu/CSR.scala:193:14
                io_cfIn_exceptionVec_2,	// src/main/scala/nutcore/backend/fu/CSR.scala:193:14
                io_cfIn_exceptionVec_3,	// src/main/scala/nutcore/backend/fu/CSR.scala:193:14
                io_cfIn_exceptionVec_4,	// src/main/scala/nutcore/backend/fu/CSR.scala:193:14
                io_cfIn_exceptionVec_5,	// src/main/scala/nutcore/backend/fu/CSR.scala:193:14
                io_cfIn_exceptionVec_6,	// src/main/scala/nutcore/backend/fu/CSR.scala:193:14
                io_cfIn_exceptionVec_7,	// src/main/scala/nutcore/backend/fu/CSR.scala:193:14
                io_cfIn_exceptionVec_8,	// src/main/scala/nutcore/backend/fu/CSR.scala:193:14
                io_cfIn_exceptionVec_9,	// src/main/scala/nutcore/backend/fu/CSR.scala:193:14
                io_cfIn_exceptionVec_10,	// src/main/scala/nutcore/backend/fu/CSR.scala:193:14
                io_cfIn_exceptionVec_11,	// src/main/scala/nutcore/backend/fu/CSR.scala:193:14
                io_cfIn_exceptionVec_12,	// src/main/scala/nutcore/backend/fu/CSR.scala:193:14
                io_cfIn_exceptionVec_13,	// src/main/scala/nutcore/backend/fu/CSR.scala:193:14
                io_cfIn_exceptionVec_14,	// src/main/scala/nutcore/backend/fu/CSR.scala:193:14
                io_cfIn_exceptionVec_15,	// src/main/scala/nutcore/backend/fu/CSR.scala:193:14
                io_cfIn_intrVec_0,	// src/main/scala/nutcore/backend/fu/CSR.scala:193:14
                io_cfIn_intrVec_1,	// src/main/scala/nutcore/backend/fu/CSR.scala:193:14
                io_cfIn_intrVec_2,	// src/main/scala/nutcore/backend/fu/CSR.scala:193:14
                io_cfIn_intrVec_3,	// src/main/scala/nutcore/backend/fu/CSR.scala:193:14
                io_cfIn_intrVec_4,	// src/main/scala/nutcore/backend/fu/CSR.scala:193:14
                io_cfIn_intrVec_5,	// src/main/scala/nutcore/backend/fu/CSR.scala:193:14
                io_cfIn_intrVec_6,	// src/main/scala/nutcore/backend/fu/CSR.scala:193:14
                io_cfIn_intrVec_7,	// src/main/scala/nutcore/backend/fu/CSR.scala:193:14
                io_cfIn_intrVec_8,	// src/main/scala/nutcore/backend/fu/CSR.scala:193:14
                io_cfIn_intrVec_9,	// src/main/scala/nutcore/backend/fu/CSR.scala:193:14
                io_cfIn_intrVec_10,	// src/main/scala/nutcore/backend/fu/CSR.scala:193:14
                io_cfIn_intrVec_11,	// src/main/scala/nutcore/backend/fu/CSR.scala:193:14
                io_cfIn_crossPageIPFFix,	// src/main/scala/nutcore/backend/fu/CSR.scala:193:14
  output [38:0] io_redirect_target,	// src/main/scala/nutcore/backend/fu/CSR.scala:193:14
  output        io_redirect_valid,	// src/main/scala/nutcore/backend/fu/CSR.scala:193:14
  input         io_instrValid,	// src/main/scala/nutcore/backend/fu/CSR.scala:193:14
  output [1:0]  io_imemMMU_privilegeMode,	// src/main/scala/nutcore/backend/fu/CSR.scala:193:14
                io_dmemMMU_privilegeMode,	// src/main/scala/nutcore/backend/fu/CSR.scala:193:14
  output        io_dmemMMU_status_sum,	// src/main/scala/nutcore/backend/fu/CSR.scala:193:14
                io_dmemMMU_status_mxr,	// src/main/scala/nutcore/backend/fu/CSR.scala:193:14
  input         io_dmemMMU_loadPF,	// src/main/scala/nutcore/backend/fu/CSR.scala:193:14
                io_dmemMMU_storePF,	// src/main/scala/nutcore/backend/fu/CSR.scala:193:14
  input  [38:0] io_dmemMMU_addr,	// src/main/scala/nutcore/backend/fu/CSR.scala:193:14
  output        io_wenFix,	// src/main/scala/nutcore/backend/fu/CSR.scala:193:14
  input         setLrVal__bore,
                setLr__bore,
  output        lr__bore,
  input         perfCntCond_3__bore,
  output [63:0] satp__bore,
                satp__bore_0,
  input         perfCntCond_2__bore,
  input  [63:0] setLrAddr__bore,
  output [63:0] perfCnts_2__bore,
  input         meip__bore,
                mtip__bore,
                msip__bore,
  output [63:0] lrAddr__bore,
  output [11:0] _WIRE__bore,
                _WIRE__bore_0,
  input  [63:0] lsuAddr__bore
);

  wire [38:0] retTarget;	// src/main/scala/nutcore/backend/fu/CSR.scala:695:26, :708:26, :716:15
  wire [38:0] _trapTarget_T;	// src/main/scala/nutcore/backend/fu/CSR.scala:677:20
  wire [63:0] _rdata_T_146;	// src/main/scala/chisel3/util/Mux.scala:30:73
  wire        _GEN = 1'h1;	// src/main/scala/nutcore/backend/fu/CSR.scala:193:14, :494:88, :876:33
  reg  [63:0] mtvec;	// src/main/scala/nutcore/backend/fu/CSR.scala:252:22
  reg  [63:0] mcounteren;	// src/main/scala/nutcore/backend/fu/CSR.scala:253:27
  reg  [63:0] mcause;	// src/main/scala/nutcore/backend/fu/CSR.scala:254:23
  reg  [63:0] mtval;	// src/main/scala/nutcore/backend/fu/CSR.scala:255:22
  reg  [63:0] mepc;	// src/main/scala/nutcore/backend/fu/CSR.scala:256:21
  reg  [63:0] mie;	// src/main/scala/nutcore/backend/fu/CSR.scala:258:20
  reg  [63:0] mipReg;	// src/main/scala/nutcore/backend/fu/CSR.scala:260:24
  wire [11:0] _mip_T_4 =
    {meip__bore, 3'h0, mtip__bore, 3'h0, msip__bore, 3'h0} | mipReg[11:0];	// src/main/scala/nutcore/backend/fu/CSR.scala:260:24, :262:29, :631:69
  reg  [63:0] misa;	// src/main/scala/nutcore/backend/fu/CSR.scala:270:21
  reg  [63:0] mstatus;	// src/main/scala/nutcore/backend/fu/CSR.scala:278:24
  reg  [63:0] medeleg;	// src/main/scala/nutcore/backend/fu/CSR.scala:321:24
  reg  [63:0] mideleg;	// src/main/scala/nutcore/backend/fu/CSR.scala:322:24
  reg  [63:0] mscratch;	// src/main/scala/nutcore/backend/fu/CSR.scala:323:25
  reg  [63:0] pmpcfg0;	// src/main/scala/nutcore/backend/fu/CSR.scala:325:24
  reg  [63:0] pmpcfg1;	// src/main/scala/nutcore/backend/fu/CSR.scala:326:24
  reg  [63:0] pmpcfg2;	// src/main/scala/nutcore/backend/fu/CSR.scala:327:24
  reg  [63:0] pmpcfg3;	// src/main/scala/nutcore/backend/fu/CSR.scala:328:24
  reg  [63:0] pmpaddr0;	// src/main/scala/nutcore/backend/fu/CSR.scala:329:25
  reg  [63:0] pmpaddr1;	// src/main/scala/nutcore/backend/fu/CSR.scala:330:25
  reg  [63:0] pmpaddr2;	// src/main/scala/nutcore/backend/fu/CSR.scala:331:25
  reg  [63:0] pmpaddr3;	// src/main/scala/nutcore/backend/fu/CSR.scala:332:25
  reg  [63:0] stvec;	// src/main/scala/nutcore/backend/fu/CSR.scala:354:22
  wire [63:0] sieMask = mideleg & 64'h222;	// src/main/scala/nutcore/backend/fu/CSR.scala:322:24, :356:32
  reg  [63:0] satp;	// src/main/scala/nutcore/backend/fu/CSR.scala:359:21
  reg  [63:0] sepc;	// src/main/scala/nutcore/backend/fu/CSR.scala:360:21
  reg  [63:0] scause;	// src/main/scala/nutcore/backend/fu/CSR.scala:361:23
  reg  [63:0] stval;	// src/main/scala/nutcore/backend/fu/CSR.scala:362:18
  reg  [63:0] sscratch;	// src/main/scala/nutcore/backend/fu/CSR.scala:363:25
  reg  [63:0] scounteren;	// src/main/scala/nutcore/backend/fu/CSR.scala:364:27
  reg         lr;	// src/main/scala/nutcore/backend/fu/CSR.scala:377:19
  reg  [63:0] lrAddr;	// src/main/scala/nutcore/backend/fu/CSR.scala:378:23
  reg  [1:0]  privilegeMode;	// src/main/scala/nutcore/backend/fu/CSR.scala:391:30
  reg  [63:0] perfCnts_0;	// src/main/scala/nutcore/backend/fu/CSR.scala:396:47
  reg  [63:0] perfCnts_1;	// src/main/scala/nutcore/backend/fu/CSR.scala:396:47
  reg  [63:0] perfCnts_2;	// src/main/scala/nutcore/backend/fu/CSR.scala:396:47
  wire [63:0] csri = {59'h0, io_cfIn_instr[19:15]};	// src/main/scala/nutcore/backend/fu/CSR.scala:480:35, src/main/scala/utils/BitUtils.scala:49:41
  wire [63:0] wdata =
    (io_in_bits_func == 7'h1 ? io_in_bits_src1 : 64'h0)
    | (io_in_bits_func == 7'h2 ? _rdata_T_146 | io_in_bits_src1 : 64'h0)
    | (io_in_bits_func == 7'h3 ? _rdata_T_146 & ~io_in_bits_src1 : 64'h0)
    | (io_in_bits_func == 7'h5 ? csri : 64'h0)
    | (io_in_bits_func == 7'h6 ? _rdata_T_146 | csri : 64'h0)
    | (io_in_bits_func == 7'h7
         ? _rdata_T_146 & {59'h7FFFFFFFFFFFFFF, ~(io_cfIn_instr[19:15])}
         : 64'h0);	// src/main/scala/chisel3/util/Mux.scala:30:73, src/main/scala/nutcore/backend/fu/CSR.scala:192:7, :258:20, :480:35, :483:30, :484:{30,32}, :486:30, :487:{30,32}, src/main/scala/utils/BitUtils.scala:49:41, src/main/scala/utils/LookupTree.scala:24:34
  wire        _wen_T_4 =
    io_in_valid & (|io_in_bits_func)
    & (io_in_bits_src2[11:0] != 12'h180 | wdata[63:60] == 4'h0 | wdata[63:60] == 4'h8);	// src/main/scala/chisel3/util/Mux.scala:30:73, src/main/scala/nutcore/backend/fu/CSR.scala:478:18, :491:{38,60,87,109}, :494:{28,47,56,67}, :631:69
  wire        isIllegalAccess =
    privilegeMode < io_in_bits_src2[9:8] | _wen_T_4 & (&(io_in_bits_src2[11:10]))
    & ~((io_in_bits_func == 7'h2 | io_in_bits_func == 7'h6) & io_in_bits_src1 == 64'h0);	// src/main/scala/nutcore/backend/fu/CSR.scala:192:7, :258:20, :391:30, :478:18, :494:47, :495:{38,44}, :496:{24,42,50,70,78}, :497:{36,45,58,61}, :498:39
  wire        _isIllegalAddr_illegalAddr_T_2 = io_in_bits_src2[11:0] == 12'h140;	// src/main/scala/nutcore/backend/fu/CSR.scala:478:18, src/main/scala/utils/LookupTree.scala:24:34
  wire        _isIllegalAddr_illegalAddr_T_4 = io_in_bits_src2[11:0] == 12'h306;	// src/main/scala/nutcore/backend/fu/CSR.scala:478:18, src/main/scala/utils/LookupTree.scala:24:34
  wire        _isIllegalAddr_illegalAddr_T_8 = io_in_bits_src2[11:0] == 12'h104;	// src/main/scala/nutcore/backend/fu/CSR.scala:478:18, src/main/scala/utils/LookupTree.scala:24:34
  wire        _rdataDummy_T_3 = io_in_bits_src2[11:0] == 12'h144;	// src/main/scala/nutcore/backend/fu/CSR.scala:478:18, src/main/scala/utils/LookupTree.scala:24:34
  wire        _isIllegalAddr_illegalAddr_T_12 = io_in_bits_src2[11:0] == 12'h100;	// src/main/scala/nutcore/backend/fu/CSR.scala:478:18, src/main/scala/utils/LookupTree.scala:24:34
  wire        _isIllegalAddr_illegalAddr_T_14 = io_in_bits_src2[11:0] == 12'h305;	// src/main/scala/nutcore/backend/fu/CSR.scala:478:18, src/main/scala/utils/LookupTree.scala:24:34
  wire        _isIllegalAddr_illegalAddr_T_16 = io_in_bits_src2[11:0] == 12'h3B3;	// src/main/scala/nutcore/backend/fu/CSR.scala:478:18, src/main/scala/utils/LookupTree.scala:24:34
  wire        _isIllegalAddr_illegalAddr_T_18 = io_in_bits_src2[11:0] == 12'h300;	// src/main/scala/nutcore/backend/fu/CSR.scala:478:18, src/main/scala/utils/LookupTree.scala:24:34
  wire        _isIllegalAddr_illegalAddr_T_20 = io_in_bits_src2[11:0] == 12'h3A0;	// src/main/scala/nutcore/backend/fu/CSR.scala:478:18, src/main/scala/utils/LookupTree.scala:24:34
  wire        _isIllegalAddr_illegalAddr_T_22 = io_in_bits_src2[11:0] == 12'h142;	// src/main/scala/nutcore/backend/fu/CSR.scala:478:18, src/main/scala/utils/LookupTree.scala:24:34
  wire        _isIllegalAddr_illegalAddr_T_24 = io_in_bits_src2[11:0] == 12'h180;	// src/main/scala/nutcore/backend/fu/CSR.scala:478:18, :494:56, src/main/scala/utils/LookupTree.scala:24:34
  wire        _isIllegalAddr_illegalAddr_T_26 = io_in_bits_src2[11:0] == 12'h3B1;	// src/main/scala/nutcore/backend/fu/CSR.scala:478:18, src/main/scala/utils/LookupTree.scala:24:34
  wire        _isIllegalAddr_illegalAddr_T_28 = io_in_bits_src2[11:0] == 12'h3A2;	// src/main/scala/nutcore/backend/fu/CSR.scala:478:18, src/main/scala/utils/LookupTree.scala:24:34
  wire        _isIllegalAddr_illegalAddr_T_30 = io_in_bits_src2[11:0] == 12'h302;	// src/main/scala/nutcore/backend/fu/CSR.scala:478:18, src/main/scala/utils/LookupTree.scala:24:34
  wire        _isIllegalAddr_illegalAddr_T_32 = io_in_bits_src2[11:0] == 12'h105;	// src/main/scala/nutcore/backend/fu/CSR.scala:478:18, src/main/scala/utils/LookupTree.scala:24:34
  wire        _isIllegalAddr_illegalAddr_T_34 = io_in_bits_src2[11:0] == 12'h141;	// src/main/scala/nutcore/backend/fu/CSR.scala:478:18, src/main/scala/utils/LookupTree.scala:24:34
  wire        _isIllegalAddr_illegalAddr_T_36 = io_in_bits_src2[11:0] == 12'h342;	// src/main/scala/nutcore/backend/fu/CSR.scala:478:18, src/main/scala/utils/LookupTree.scala:24:34
  wire        _isIllegalAddr_illegalAddr_T_38 = io_in_bits_src2[11:0] == 12'h304;	// src/main/scala/nutcore/backend/fu/CSR.scala:478:18, src/main/scala/utils/LookupTree.scala:24:34
  wire        _isIllegalAddr_illegalAddr_T_40 = io_in_bits_src2[11:0] == 12'hB01;	// src/main/scala/nutcore/backend/fu/CSR.scala:478:18, src/main/scala/utils/LookupTree.scala:24:34
  wire        _isIllegalAddr_illegalAddr_T_42 = io_in_bits_src2[11:0] == 12'h143;	// src/main/scala/nutcore/backend/fu/CSR.scala:478:18, src/main/scala/utils/LookupTree.scala:24:34
  wire        _isIllegalAddr_illegalAddr_T_44 = io_in_bits_src2[11:0] == 12'h301;	// src/main/scala/nutcore/backend/fu/CSR.scala:478:18, src/main/scala/utils/LookupTree.scala:24:34
  wire        _isIllegalAddr_illegalAddr_T_46 = io_in_bits_src2[11:0] == 12'hB00;	// src/main/scala/nutcore/backend/fu/CSR.scala:478:18, src/main/scala/utils/LookupTree.scala:24:34
  wire        _isIllegalAddr_illegalAddr_T_48 = io_in_bits_src2[11:0] == 12'h3B0;	// src/main/scala/nutcore/backend/fu/CSR.scala:478:18, src/main/scala/utils/LookupTree.scala:24:34
  wire        _rdataDummy_T_2 = io_in_bits_src2[11:0] == 12'h344;	// src/main/scala/nutcore/backend/fu/CSR.scala:478:18, src/main/scala/utils/LookupTree.scala:24:34
  wire        _isIllegalAddr_illegalAddr_T_52 = io_in_bits_src2[11:0] == 12'hB02;	// src/main/scala/nutcore/backend/fu/CSR.scala:478:18, src/main/scala/utils/LookupTree.scala:24:34
  wire        _isIllegalAddr_illegalAddr_T_54 = io_in_bits_src2[11:0] == 12'h3A3;	// src/main/scala/nutcore/backend/fu/CSR.scala:478:18, src/main/scala/utils/LookupTree.scala:24:34
  wire        _isIllegalAddr_illegalAddr_T_56 = io_in_bits_src2[11:0] == 12'h303;	// src/main/scala/nutcore/backend/fu/CSR.scala:478:18, src/main/scala/utils/LookupTree.scala:24:34
  wire        _isIllegalAddr_illegalAddr_T_58 = io_in_bits_src2[11:0] == 12'h3B2;	// src/main/scala/nutcore/backend/fu/CSR.scala:478:18, src/main/scala/utils/LookupTree.scala:24:34
  wire        _isIllegalAddr_illegalAddr_T_62 = io_in_bits_src2[11:0] == 12'h3A1;	// src/main/scala/nutcore/backend/fu/CSR.scala:478:18, src/main/scala/utils/LookupTree.scala:24:34
  wire        _isIllegalAddr_illegalAddr_T_64 = io_in_bits_src2[11:0] == 12'h340;	// src/main/scala/nutcore/backend/fu/CSR.scala:478:18, src/main/scala/utils/LookupTree.scala:24:34
  wire        _isIllegalAddr_illegalAddr_T_68 = io_in_bits_src2[11:0] == 12'h341;	// src/main/scala/nutcore/backend/fu/CSR.scala:478:18, src/main/scala/utils/LookupTree.scala:24:34
  wire        _isIllegalAddr_illegalAddr_T_70 = io_in_bits_src2[11:0] == 12'h343;	// src/main/scala/nutcore/backend/fu/CSR.scala:478:18, src/main/scala/utils/LookupTree.scala:24:34
  wire        _isIllegalAddr_illegalAddr_T_72 = io_in_bits_src2[11:0] == 12'h106;	// src/main/scala/nutcore/backend/fu/CSR.scala:478:18, src/main/scala/utils/LookupTree.scala:24:34
  assign _rdata_T_146 =
    (_isIllegalAddr_illegalAddr_T_2 ? sscratch : 64'h0)
    | (_isIllegalAddr_illegalAddr_T_4 ? mcounteren : 64'h0)
    | (_isIllegalAddr_illegalAddr_T_8 ? mie & sieMask : 64'h0)
    | (_rdataDummy_T_3 ? {52'h0, {2'h0, mideleg[9:1] & 9'h111, 1'h0} & _mip_T_4} : 64'h0)
    | (_isIllegalAddr_illegalAddr_T_12 ? mstatus & 64'h80000003000DE122 : 64'h0)
    | (_isIllegalAddr_illegalAddr_T_14 ? mtvec : 64'h0)
    | (_isIllegalAddr_illegalAddr_T_16 ? pmpaddr3 : 64'h0)
    | (_isIllegalAddr_illegalAddr_T_18 ? mstatus : 64'h0)
    | (_isIllegalAddr_illegalAddr_T_20 ? pmpcfg0 : 64'h0)
    | (_isIllegalAddr_illegalAddr_T_22 ? scause : 64'h0)
    | (_isIllegalAddr_illegalAddr_T_24 ? satp : 64'h0)
    | (_isIllegalAddr_illegalAddr_T_26 ? pmpaddr1 : 64'h0)
    | (_isIllegalAddr_illegalAddr_T_28 ? pmpcfg2 : 64'h0)
    | (_isIllegalAddr_illegalAddr_T_30 ? medeleg : 64'h0)
    | (_isIllegalAddr_illegalAddr_T_32 ? stvec : 64'h0)
    | (_isIllegalAddr_illegalAddr_T_34 ? sepc : 64'h0)
    | (_isIllegalAddr_illegalAddr_T_36 ? mcause : 64'h0)
    | (_isIllegalAddr_illegalAddr_T_38 ? mie : 64'h0)
    | (_isIllegalAddr_illegalAddr_T_40 ? perfCnts_1 : 64'h0)
    | (_isIllegalAddr_illegalAddr_T_42 ? stval : 64'h0)
    | (_isIllegalAddr_illegalAddr_T_44 ? misa : 64'h0)
    | (_isIllegalAddr_illegalAddr_T_46 ? perfCnts_0 : 64'h0)
    | (_isIllegalAddr_illegalAddr_T_48 ? pmpaddr0 : 64'h0)
    | (_rdataDummy_T_2 ? {52'h0, _mip_T_4} : 64'h0)
    | (_isIllegalAddr_illegalAddr_T_52 ? perfCnts_2 : 64'h0)
    | (_isIllegalAddr_illegalAddr_T_54 ? pmpcfg3 : 64'h0)
    | (_isIllegalAddr_illegalAddr_T_56 ? mideleg : 64'h0)
    | (_isIllegalAddr_illegalAddr_T_58 ? pmpaddr2 : 64'h0)
    | (_isIllegalAddr_illegalAddr_T_62 ? pmpcfg1 : 64'h0)
    | (_isIllegalAddr_illegalAddr_T_64 ? mscratch : 64'h0)
    | (_isIllegalAddr_illegalAddr_T_68 ? mepc : 64'h0)
    | (_isIllegalAddr_illegalAddr_T_70 ? mtval : 64'h0)
    | (_isIllegalAddr_illegalAddr_T_72 ? scounteren : 64'h0);	// src/main/scala/chisel3/util/Mux.scala:30:73, src/main/scala/nutcore/backend/fu/CSR.scala:213:34, :252:22, :253:27, :254:23, :255:22, :256:21, :258:20, :262:29, :270:21, :278:24, :300:59, :321:24, :322:24, :323:25, :325:24, :326:24, :327:24, :328:24, :329:25, :330:25, :331:25, :332:25, :352:35, :354:22, :356:32, :359:21, :360:21, :361:23, :362:18, :363:25, :364:27, :396:47, src/main/scala/utils/LookupTree.scala:24:34, src/main/scala/utils/RegMap.scala:48:84
  wire        _resetSatp_T = io_in_bits_src2[11:0] == 12'h180;	// src/main/scala/nutcore/backend/fu/CSR.scala:478:18, :494:56, src/main/scala/utils/RegMap.scala:50:65
  wire        resetSatp = _resetSatp_T & _wen_T_4;	// src/main/scala/nutcore/backend/fu/CSR.scala:494:47, :502:35, src/main/scala/utils/RegMap.scala:50:65
  wire        _io_redirect_valid_T = io_in_bits_func == 7'h0;	// src/main/scala/nutcore/backend/fu/CSR.scala:192:7, :515:46
  wire        _isEcall_T_2 = io_in_bits_src2[11:0] == 12'h0 & _io_redirect_valid_T;	// src/main/scala/nutcore/backend/fu/CSR.scala:478:18, :515:46, :516:{22,36}
  wire        mipRaiseIntr_e_s = _mip_T_4[9] | meip__bore;	// src/main/scala/nutcore/backend/fu/CSR.scala:262:{29,47}, :619:31
  wire [11:0] _GEN_0 = mideleg[11:0] & {_mip_T_4[11:10], mipRaiseIntr_e_s, _mip_T_4[8:0]};	// src/main/scala/nutcore/backend/fu/CSR.scala:262:29, :322:24, :356:32, :619:31, :621:{26,41}, src/main/scala/utils/RegMap.scala:48:84
  wire        _csrExceptionVec_9_T = privilegeMode == 2'h1;	// src/main/scala/nutcore/backend/fu/CSR.scala:391:30, :622:70, :729:21
  wire        _intrVecEnable_11_T_2 = privilegeMode == 2'h0;	// src/main/scala/nutcore/backend/fu/CSR.scala:300:59, :391:30, :622:122
  wire        _delegS_T_3 = privilegeMode != 2'h3;	// src/main/scala/nutcore/backend/fu/CSR.scala:300:59, :391:30, :623:104
  wire [11:0] _GEN_1 =
    mie[11:0] & {_mip_T_4[11:10], mipRaiseIntr_e_s, _mip_T_4[8:0]}
    & {_GEN_0[11]
         ? _csrExceptionVec_9_T & mstatus[1] | _intrVecEnable_11_T_2
         : (&privilegeMode) & mstatus[3] | _delegS_T_3,
       _GEN_0[10]
         ? _csrExceptionVec_9_T & mstatus[1] | _intrVecEnable_11_T_2
         : (&privilegeMode) & mstatus[3] | _delegS_T_3,
       _GEN_0[9]
         ? _csrExceptionVec_9_T & mstatus[1] | _intrVecEnable_11_T_2
         : (&privilegeMode) & mstatus[3] | _delegS_T_3,
       _GEN_0[8]
         ? _csrExceptionVec_9_T & mstatus[1] | _intrVecEnable_11_T_2
         : (&privilegeMode) & mstatus[3] | _delegS_T_3,
       _GEN_0[7]
         ? _csrExceptionVec_9_T & mstatus[1] | _intrVecEnable_11_T_2
         : (&privilegeMode) & mstatus[3] | _delegS_T_3,
       _GEN_0[6]
         ? _csrExceptionVec_9_T & mstatus[1] | _intrVecEnable_11_T_2
         : (&privilegeMode) & mstatus[3] | _delegS_T_3,
       _GEN_0[5]
         ? _csrExceptionVec_9_T & mstatus[1] | _intrVecEnable_11_T_2
         : (&privilegeMode) & mstatus[3] | _delegS_T_3,
       _GEN_0[4]
         ? _csrExceptionVec_9_T & mstatus[1] | _intrVecEnable_11_T_2
         : (&privilegeMode) & mstatus[3] | _delegS_T_3,
       _GEN_0[3]
         ? _csrExceptionVec_9_T & mstatus[1] | _intrVecEnable_11_T_2
         : (&privilegeMode) & mstatus[3] | _delegS_T_3,
       _GEN_0[2]
         ? _csrExceptionVec_9_T & mstatus[1] | _intrVecEnable_11_T_2
         : (&privilegeMode) & mstatus[3] | _delegS_T_3,
       _GEN_0[1]
         ? _csrExceptionVec_9_T & mstatus[1] | _intrVecEnable_11_T_2
         : (&privilegeMode) & mstatus[3] | _delegS_T_3,
       _GEN_0[0]
         ? _csrExceptionVec_9_T & mstatus[1] | _intrVecEnable_11_T_2
         : (&privilegeMode) & mstatus[3] | _delegS_T_3};	// src/main/scala/nutcore/backend/fu/CSR.scala:258:20, :262:29, :278:24, :314:39, :391:30, :619:31, :621:{26,41}, :622:{50,70,81,104,122}, :623:{52,63,86,104}, :626:28, :627:{20,42,49,65}, :628:33
  wire [11:0] _raiseIntr_T =
    {io_cfIn_intrVec_11,
     io_cfIn_intrVec_10,
     io_cfIn_intrVec_9,
     io_cfIn_intrVec_8,
     io_cfIn_intrVec_7,
     io_cfIn_intrVec_6,
     io_cfIn_intrVec_5,
     io_cfIn_intrVec_4,
     io_cfIn_intrVec_3,
     io_cfIn_intrVec_2,
     io_cfIn_intrVec_1,
     io_cfIn_intrVec_0};	// src/main/scala/nutcore/backend/fu/CSR.scala:633:35
  wire        _exceptionNO_T_6 = io_dmemMMU_storePF | io_cfIn_exceptionVec_15;	// src/main/scala/nutcore/backend/fu/CSR.scala:648:50
  wire        _exceptionNO_T_4 = io_dmemMMU_loadPF | io_cfIn_exceptionVec_13;	// src/main/scala/nutcore/backend/fu/CSR.scala:648:50
  wire        _exceptionNO_T_16 =
    (&privilegeMode) & io_in_valid & _isEcall_T_2 | io_cfIn_exceptionVec_11;	// src/main/scala/nutcore/backend/fu/CSR.scala:391:30, :516:36, :623:52, :641:69, :648:50
  wire        _exceptionNO_T_14 =
    _csrExceptionVec_9_T & io_in_valid & _isEcall_T_2 | io_cfIn_exceptionVec_9;	// src/main/scala/nutcore/backend/fu/CSR.scala:516:36, :622:70, :642:69, :648:50
  wire        _exceptionNO_T_12 =
    privilegeMode == 2'h0 & io_in_valid & _isEcall_T_2 | io_cfIn_exceptionVec_8;	// src/main/scala/nutcore/backend/fu/CSR.scala:300:59, :391:30, :516:36, :643:{44,69}, :648:50
  wire        _exceptionNO_T_26 =
    io_in_valid & io_in_bits_src2[11:0] == 12'h1 & _io_redirect_valid_T
    | io_cfIn_exceptionVec_3;	// src/main/scala/nutcore/backend/fu/CSR.scala:478:18, :515:{23,46}, :640:46, :648:50
  wire        _exceptionNO_T_20 =
    (~(_isIllegalAddr_illegalAddr_T_72 | _isIllegalAddr_illegalAddr_T_70
       | _isIllegalAddr_illegalAddr_T_68 | io_in_bits_src2[11:0] == 12'hF14
       | _isIllegalAddr_illegalAddr_T_64 | _isIllegalAddr_illegalAddr_T_62
       | io_in_bits_src2[11:0] == 12'hF13 | _isIllegalAddr_illegalAddr_T_58
       | _isIllegalAddr_illegalAddr_T_56 | _isIllegalAddr_illegalAddr_T_54
       | _isIllegalAddr_illegalAddr_T_52 | _rdataDummy_T_2
       | _isIllegalAddr_illegalAddr_T_48 | _isIllegalAddr_illegalAddr_T_46
       | _isIllegalAddr_illegalAddr_T_44 | _isIllegalAddr_illegalAddr_T_42
       | _isIllegalAddr_illegalAddr_T_40 | _isIllegalAddr_illegalAddr_T_38
       | _isIllegalAddr_illegalAddr_T_36 | _isIllegalAddr_illegalAddr_T_34
       | _isIllegalAddr_illegalAddr_T_32 | _isIllegalAddr_illegalAddr_T_30
       | _isIllegalAddr_illegalAddr_T_28 | _isIllegalAddr_illegalAddr_T_26
       | _isIllegalAddr_illegalAddr_T_24 | _isIllegalAddr_illegalAddr_T_22
       | _isIllegalAddr_illegalAddr_T_20 | _isIllegalAddr_illegalAddr_T_18
       | _isIllegalAddr_illegalAddr_T_16 | _isIllegalAddr_illegalAddr_T_14
       | _isIllegalAddr_illegalAddr_T_12 | _rdataDummy_T_3
       | _isIllegalAddr_illegalAddr_T_8 | io_in_bits_src2[11:0] == 12'hF11
       | _isIllegalAddr_illegalAddr_T_4 | _isIllegalAddr_illegalAddr_T_2)
     & io_in_bits_src2[11:0] != 12'hF12 | isIllegalAccess) & _wen_T_4
    | io_cfIn_exceptionVec_2;	// src/main/scala/nutcore/backend/fu/CSR.scala:478:18, :494:47, :498:39, :644:{51,71}, :648:50, src/main/scala/utils/LookupTree.scala:24:34, :29:28
  wire [15:0] _GEN_2 =
    {_exceptionNO_T_6,
     io_cfIn_exceptionVec_14,
     _exceptionNO_T_4,
     io_cfIn_exceptionVec_12,
     _exceptionNO_T_16,
     io_cfIn_exceptionVec_10,
     _exceptionNO_T_14,
     _exceptionNO_T_12,
     io_cfIn_exceptionVec_7,
     io_cfIn_exceptionVec_6,
     io_cfIn_exceptionVec_5,
     io_cfIn_exceptionVec_4,
     _exceptionNO_T_26,
     _exceptionNO_T_20,
     io_cfIn_exceptionVec_1,
     io_cfIn_exceptionVec_0};	// src/main/scala/nutcore/backend/fu/CSR.scala:648:50
  wire [3:0]  _causeNO_T_1 =
    (|_raiseIntr_T)
      ? (io_cfIn_intrVec_3
           ? 4'h3
           : io_cfIn_intrVec_11
               ? 4'hB
               : io_cfIn_intrVec_7
                   ? 4'h7
                   : io_cfIn_intrVec_1
                       ? 4'h1
                       : io_cfIn_intrVec_9
                           ? 4'h9
                           : io_cfIn_intrVec_5
                               ? 4'h5
                               : io_cfIn_intrVec_0
                                   ? 4'h0
                                   : io_cfIn_intrVec_8
                                       ? 4'h8
                                       : {1'h0, io_cfIn_intrVec_4, 2'h0})
      : _exceptionNO_T_26
          ? 4'h3
          : io_cfIn_exceptionVec_12
              ? 4'hC
              : io_cfIn_exceptionVec_1
                  ? 4'h1
                  : _exceptionNO_T_20
                      ? 4'h2
                      : io_cfIn_exceptionVec_0
                          ? 4'h0
                          : _exceptionNO_T_16
                              ? 4'hB
                              : _exceptionNO_T_14
                                  ? 4'h9
                                  : _exceptionNO_T_12
                                      ? 4'h8
                                      : io_cfIn_exceptionVec_6
                                          ? 4'h6
                                          : io_cfIn_exceptionVec_4
                                              ? 4'h4
                                              : _exceptionNO_T_6
                                                  ? 4'hF
                                                  : _exceptionNO_T_4
                                                      ? 4'hD
                                                      : {1'h0,
                                                         io_cfIn_exceptionVec_7
                                                           ? 3'h7
                                                           : io_cfIn_exceptionVec_5
                                                               ? 3'h5
                                                               : 3'h0};	// src/main/scala/nutcore/backend/fu/CSR.scala:213:34, :300:59, :491:109, :631:69, :633:{35,42}, :648:50, :650:74, :653:46, src/main/scala/utils/LookupTree.scala:24:34
  wire        raiseExceptionIntr = ((|_GEN_2) | (|_raiseIntr_T)) & io_instrValid;	// src/main/scala/nutcore/backend/fu/CSR.scala:633:{35,42}, :648:50, :649:42, :656:{44,58}
  wire [63:0] _delegS_T_1 = ((|_raiseIntr_T) ? mideleg : medeleg) >> _causeNO_T_1;	// src/main/scala/nutcore/backend/fu/CSR.scala:321:24, :322:24, :633:{35,42}, :653:46, :671:18, :673:22
  wire        delegS = _delegS_T_1[0] & _delegS_T_3;	// src/main/scala/nutcore/backend/fu/CSR.scala:623:104, :673:{22,38}
  assign _trapTarget_T = delegS ? stvec[38:0] : mtvec[38:0];	// src/main/scala/nutcore/backend/fu/CSR.scala:252:22, :354:22, :673:38, :677:20
  wire        _GEN_3 =
    io_in_valid & io_in_bits_src2[11:0] == 12'h102 & _io_redirect_valid_T;	// src/main/scala/nutcore/backend/fu/CSR.scala:478:18, :515:46, :518:21, :695:15
  wire        _GEN_4 =
    io_in_valid & io_in_bits_src2[11:0] == 12'h2 & _io_redirect_valid_T;	// src/main/scala/nutcore/backend/fu/CSR.scala:478:18, :515:46, :519:21, :708:15
  assign retTarget = _GEN_4 ? 39'h0 : _GEN_3 ? sepc[38:0] : mepc[38:0];	// src/main/scala/nutcore/backend/fu/CSR.scala:256:21, :360:21, :682:26, :692:22, :695:{15,26}, :705:{15,22}, :708:{15,26}, :716:{15,22}
  always @(posedge clock) begin	// src/main/scala/nutcore/backend/fu/CSR.scala:192:7
    automatic logic        _GEN_5;	// src/main/scala/nutcore/backend/fu/CSR.scala:500:51
    automatic logic        hasInstrPageFault = io_cfIn_exceptionVec_12 & io_in_valid;	// src/main/scala/nutcore/backend/fu/CSR.scala:576:63
    automatic logic        _tvalWen_T = hasInstrPageFault | io_dmemMMU_loadPF;	// src/main/scala/nutcore/backend/fu/CSR.scala:576:63, :585:26
    automatic logic        _GEN_6;	// src/main/scala/nutcore/backend/fu/CSR.scala:585:46
    automatic logic [38:0] _tval_T = io_cfIn_pc + 39'h2;	// src/main/scala/nutcore/backend/fu/CSR.scala:586:88
    automatic logic [63:0] tval;	// src/main/scala/nutcore/backend/fu/CSR.scala:586:19
    automatic logic        tvalWen;	// src/main/scala/nutcore/backend/fu/CSR.scala:674:130
    _GEN_5 = _wen_T_4 & ~isIllegalAccess;	// src/main/scala/nutcore/backend/fu/CSR.scala:494:47, :498:39, :500:{51,54}
    _GEN_6 = _tvalWen_T | io_dmemMMU_storePF;	// src/main/scala/nutcore/backend/fu/CSR.scala:585:{26,46}
    tval =
      hasInstrPageFault
        ? (io_cfIn_crossPageIPFFix
             ? {{25{_tval_T[38]}}, _tval_T}
             : {{25{io_cfIn_pc[38]}}, io_cfIn_pc})
        : {{25{io_dmemMMU_addr[38]}}, io_dmemMMU_addr};	// src/main/scala/nutcore/backend/fu/CSR.scala:576:63, :586:{19,42,88}, src/main/scala/utils/BitUtils.scala:41:20, :42:{41,46}
    tvalWen =
      ~(_tvalWen_T | io_dmemMMU_storePF | io_cfIn_exceptionVec_4 | io_cfIn_exceptionVec_6)
      | (|_raiseIntr_T);	// src/main/scala/nutcore/backend/fu/CSR.scala:585:26, :633:{35,42}, :674:{17,103,130}
    if (reset) begin	// src/main/scala/nutcore/backend/fu/CSR.scala:192:7
      mtvec <= 64'h0;	// src/main/scala/nutcore/backend/fu/CSR.scala:252:22, :258:20
      mcounteren <= 64'h0;	// src/main/scala/nutcore/backend/fu/CSR.scala:253:27, :258:20
      mcause <= 64'h0;	// src/main/scala/nutcore/backend/fu/CSR.scala:254:23, :258:20
      mtval <= 64'h0;	// src/main/scala/nutcore/backend/fu/CSR.scala:255:22, :258:20
      mepc <= 64'h0;	// src/main/scala/nutcore/backend/fu/CSR.scala:256:21, :258:20
      mie <= 64'h0;	// src/main/scala/nutcore/backend/fu/CSR.scala:258:20
      mipReg <= 64'h0;	// src/main/scala/nutcore/backend/fu/CSR.scala:258:20, :260:24
      misa <= 64'h8000000000141105;	// src/main/scala/nutcore/backend/fu/CSR.scala:269:35, :270:21
      mstatus <= 64'hA00001800;	// src/main/scala/nutcore/backend/fu/CSR.scala:278:24
      medeleg <= 64'h0;	// src/main/scala/nutcore/backend/fu/CSR.scala:258:20, :321:24
      mideleg <= 64'h0;	// src/main/scala/nutcore/backend/fu/CSR.scala:258:20, :322:24
      mscratch <= 64'h0;	// src/main/scala/nutcore/backend/fu/CSR.scala:258:20, :323:25
      pmpcfg0 <= 64'h0;	// src/main/scala/nutcore/backend/fu/CSR.scala:258:20, :325:24
      pmpcfg1 <= 64'h0;	// src/main/scala/nutcore/backend/fu/CSR.scala:258:20, :326:24
      pmpcfg2 <= 64'h0;	// src/main/scala/nutcore/backend/fu/CSR.scala:258:20, :327:24
      pmpcfg3 <= 64'h0;	// src/main/scala/nutcore/backend/fu/CSR.scala:258:20, :328:24
      pmpaddr0 <= 64'h0;	// src/main/scala/nutcore/backend/fu/CSR.scala:258:20, :329:25
      pmpaddr1 <= 64'h0;	// src/main/scala/nutcore/backend/fu/CSR.scala:258:20, :330:25
      pmpaddr2 <= 64'h0;	// src/main/scala/nutcore/backend/fu/CSR.scala:258:20, :331:25
      pmpaddr3 <= 64'h0;	// src/main/scala/nutcore/backend/fu/CSR.scala:258:20, :332:25
      stvec <= 64'h0;	// src/main/scala/nutcore/backend/fu/CSR.scala:258:20, :354:22
      satp <= 64'h0;	// src/main/scala/nutcore/backend/fu/CSR.scala:258:20, :359:21
      sepc <= 64'h0;	// src/main/scala/nutcore/backend/fu/CSR.scala:258:20, :360:21
      scause <= 64'h0;	// src/main/scala/nutcore/backend/fu/CSR.scala:258:20, :361:23
      sscratch <= 64'h0;	// src/main/scala/nutcore/backend/fu/CSR.scala:258:20, :363:25
      scounteren <= 64'h0;	// src/main/scala/nutcore/backend/fu/CSR.scala:258:20, :364:27
      lr <= 1'h0;	// src/main/scala/nutcore/backend/fu/CSR.scala:213:34, :377:19
      lrAddr <= 64'h0;	// src/main/scala/nutcore/backend/fu/CSR.scala:258:20, :378:23
      privilegeMode <= 2'h3;	// src/main/scala/nutcore/backend/fu/CSR.scala:300:59, :391:30
      perfCnts_0 <= 64'h0;	// src/main/scala/nutcore/backend/fu/CSR.scala:258:20, :396:47
      perfCnts_1 <= 64'h0;	// src/main/scala/nutcore/backend/fu/CSR.scala:258:20, :396:47
      perfCnts_2 <= 64'h0;	// src/main/scala/nutcore/backend/fu/CSR.scala:258:20, :396:47
    end
    else begin	// src/main/scala/nutcore/backend/fu/CSR.scala:192:7
      automatic logic        _isMret_T = io_in_bits_src2[11:0] == 12'h302;	// src/main/scala/nutcore/backend/fu/CSR.scala:478:18, src/main/scala/utils/LookupTree.scala:24:34, src/main/scala/utils/RegMap.scala:50:65
      automatic logic [63:0] causeNO;	// src/main/scala/nutcore/backend/fu/CSR.scala:653:41
      automatic logic        _GEN_7;	// src/main/scala/nutcore/backend/fu/CSR.scala:682:15
      automatic logic        _GEN_8 = ~raiseExceptionIntr | delegS;	// src/main/scala/nutcore/backend/fu/CSR.scala:656:58, :673:38, :719:29, :723:19, src/main/scala/utils/RegMap.scala:50:72
      causeNO = {|_raiseIntr_T, 59'h0, _causeNO_T_1};	// src/main/scala/nutcore/backend/fu/CSR.scala:633:{35,42}, :653:{41,46}, src/main/scala/utils/BitUtils.scala:49:41
      _GEN_7 = io_in_valid & _isMret_T & _io_redirect_valid_T;	// src/main/scala/nutcore/backend/fu/CSR.scala:515:46, :682:15, src/main/scala/utils/RegMap.scala:50:65
      if (_GEN_5 & io_in_bits_src2[11:0] == 12'h305)	// src/main/scala/nutcore/backend/fu/CSR.scala:478:18, :500:51, src/main/scala/utils/LookupTree.scala:24:34, src/main/scala/utils/RegMap.scala:50:{56,65}
        mtvec <= wdata;	// src/main/scala/chisel3/util/Mux.scala:30:73, src/main/scala/nutcore/backend/fu/CSR.scala:252:22
      if (_GEN_5 & io_in_bits_src2[11:0] == 12'h306)	// src/main/scala/nutcore/backend/fu/CSR.scala:478:18, :500:51, src/main/scala/utils/LookupTree.scala:24:34, src/main/scala/utils/RegMap.scala:50:{56,65}
        mcounteren <= wdata;	// src/main/scala/chisel3/util/Mux.scala:30:73, src/main/scala/nutcore/backend/fu/CSR.scala:253:27
      if (_GEN_8) begin	// src/main/scala/nutcore/backend/fu/CSR.scala:719:29, :723:19, src/main/scala/utils/RegMap.scala:50:72
        if (_GEN_5 & io_in_bits_src2[11:0] == 12'h342)	// src/main/scala/nutcore/backend/fu/CSR.scala:478:18, :500:51, src/main/scala/utils/LookupTree.scala:24:34, src/main/scala/utils/RegMap.scala:50:{56,65}
          mcause <= wdata;	// src/main/scala/chisel3/util/Mux.scala:30:73, src/main/scala/nutcore/backend/fu/CSR.scala:254:23
      end
      else	// src/main/scala/nutcore/backend/fu/CSR.scala:719:29, :723:19, src/main/scala/utils/RegMap.scala:50:72
        mcause <= causeNO;	// src/main/scala/nutcore/backend/fu/CSR.scala:254:23, :653:41
      if (~raiseExceptionIntr | delegS | ~tvalWen) begin	// src/main/scala/nutcore/backend/fu/CSR.scala:596:3, :656:58, :673:38, :674:130, :719:29, :723:19, :740:20, src/main/scala/utils/RegMap.scala:50:72
        if (io_cfIn_exceptionVec_4 | io_cfIn_exceptionVec_6)	// src/main/scala/nutcore/backend/fu/CSR.scala:595:30
          mtval <= {{25{lsuAddr__bore[38]}}, lsuAddr__bore[38:0]};	// src/main/scala/nutcore/backend/fu/CSR.scala:255:22, :582:28, src/main/scala/utils/BitUtils.scala:41:20, :42:{41,46}
        else if (_GEN_6 & (&privilegeMode))	// src/main/scala/nutcore/backend/fu/CSR.scala:391:30, :585:{46,67}, :587:{24,34}, :588:13, src/main/scala/utils/RegMap.scala:50:72
          mtval <= tval;	// src/main/scala/nutcore/backend/fu/CSR.scala:255:22, :586:19
        else if (_GEN_5 & io_in_bits_src2[11:0] == 12'h343)	// src/main/scala/nutcore/backend/fu/CSR.scala:478:18, :500:51, src/main/scala/utils/LookupTree.scala:24:34, src/main/scala/utils/RegMap.scala:50:{56,65}
          mtval <= wdata;	// src/main/scala/chisel3/util/Mux.scala:30:73, src/main/scala/nutcore/backend/fu/CSR.scala:255:22
      end
      else	// src/main/scala/nutcore/backend/fu/CSR.scala:596:3, :719:29, :723:19
        mtval <= 64'h0;	// src/main/scala/nutcore/backend/fu/CSR.scala:255:22, :258:20
      if (_GEN_8) begin	// src/main/scala/nutcore/backend/fu/CSR.scala:719:29, :723:19, src/main/scala/utils/RegMap.scala:50:72
        if (_GEN_5 & io_in_bits_src2[11:0] == 12'h341)	// src/main/scala/nutcore/backend/fu/CSR.scala:478:18, :500:51, src/main/scala/utils/LookupTree.scala:24:34, src/main/scala/utils/RegMap.scala:50:{56,65}
          mepc <= wdata;	// src/main/scala/chisel3/util/Mux.scala:30:73, src/main/scala/nutcore/backend/fu/CSR.scala:256:21
      end
      else	// src/main/scala/nutcore/backend/fu/CSR.scala:719:29, :723:19, src/main/scala/utils/RegMap.scala:50:72
        mepc <= {{25{io_cfIn_pc[38]}}, io_cfIn_pc};	// src/main/scala/nutcore/backend/fu/CSR.scala:256:21, src/main/scala/utils/BitUtils.scala:41:20, :42:{41,46}
      if (_GEN_5 & io_in_bits_src2[11:0] == 12'h304)	// src/main/scala/nutcore/backend/fu/CSR.scala:478:18, :500:51, src/main/scala/utils/LookupTree.scala:24:34, src/main/scala/utils/RegMap.scala:50:{56,65}
        mie <= wdata;	// src/main/scala/chisel3/util/Mux.scala:30:73, src/main/scala/nutcore/backend/fu/CSR.scala:258:20
      else if (_GEN_5 & io_in_bits_src2[11:0] == 12'h104)	// src/main/scala/nutcore/backend/fu/CSR.scala:478:18, :500:51, src/main/scala/utils/LookupTree.scala:24:34, src/main/scala/utils/RegMap.scala:50:{56,65}
        mie <= wdata & sieMask | mie & ~sieMask;	// src/main/scala/chisel3/util/Mux.scala:30:73, src/main/scala/nutcore/backend/fu/CSR.scala:258:20, :356:32, src/main/scala/utils/BitUtils.scala:34:{14,26,37,39}
      if (_GEN_5 & io_in_bits_src2[11:0] == 12'h144)	// src/main/scala/nutcore/backend/fu/CSR.scala:478:18, :500:51, src/main/scala/utils/LookupTree.scala:24:34, src/main/scala/utils/RegMap.scala:50:{56,65}
        mipReg <= wdata & sieMask | mipReg & ~sieMask;	// src/main/scala/chisel3/util/Mux.scala:30:73, src/main/scala/nutcore/backend/fu/CSR.scala:260:24, :356:32, src/main/scala/utils/BitUtils.scala:34:{14,26,37,39}
      else if (_GEN_5 & io_in_bits_src2[11:0] == 12'h344)	// src/main/scala/nutcore/backend/fu/CSR.scala:478:18, :500:51, src/main/scala/utils/LookupTree.scala:24:34, src/main/scala/utils/RegMap.scala:50:{56,65}
        mipReg <= wdata & 64'h77F | mipReg & 64'hFFFFFFFFFFFFF880;	// src/main/scala/chisel3/util/Mux.scala:30:73, src/main/scala/nutcore/backend/fu/CSR.scala:260:24, src/main/scala/utils/BitUtils.scala:34:{14,26,37,39}
      if (_GEN_5 & io_in_bits_src2[11:0] == 12'h301)	// src/main/scala/nutcore/backend/fu/CSR.scala:478:18, :500:51, src/main/scala/utils/LookupTree.scala:24:34, src/main/scala/utils/RegMap.scala:50:{56,65}
        misa <= wdata;	// src/main/scala/chisel3/util/Mux.scala:30:73, src/main/scala/nutcore/backend/fu/CSR.scala:270:21
      if (raiseExceptionIntr) begin	// src/main/scala/nutcore/backend/fu/CSR.scala:656:58
        mstatus <=
          {mstatus[63:13],
           delegS ? mstatus[12:11] : privilegeMode,
           mstatus[10:9],
           delegS ? privilegeMode[0] : mstatus[8],
           delegS ? mstatus[7] : mstatus[3],
           mstatus[6],
           delegS ? mstatus[1] : mstatus[5],
           mstatus[4],
           delegS & mstatus[3],
           mstatus[2],
           ~delegS & mstatus[1],
           mstatus[0]};	// src/main/scala/nutcore/backend/fu/CSR.scala:278:24, :391:30, :673:38, :690:27, :720:47, :721:{30,47}, :723:19, :726:22, :727:24, :728:23, :736:22, :737:24, :738:23, :750:27
        privilegeMode <= {~delegS, 1'h1};	// src/main/scala/nutcore/backend/fu/CSR.scala:193:14, :391:30, :494:88, :673:38, :721:30, :723:19, :728:23, :729:21, :739:21
      end
      else if (_GEN_4) begin	// src/main/scala/nutcore/backend/fu/CSR.scala:708:15
        mstatus <= {mstatus[63:5], 1'h1, mstatus[3:1], mstatus[4]};	// src/main/scala/nutcore/backend/fu/CSR.scala:193:14, :278:24, :494:88, :709:47, :715:27
        privilegeMode <= 2'h0;	// src/main/scala/nutcore/backend/fu/CSR.scala:300:59, :391:30
      end
      else if (_GEN_3) begin	// src/main/scala/nutcore/backend/fu/CSR.scala:695:15
        mstatus <=
          {mstatus[63:9], 1'h0, mstatus[7:6], 1'h1, mstatus[4:2], mstatus[5], mstatus[0]};	// src/main/scala/nutcore/backend/fu/CSR.scala:193:14, :213:34, :278:24, :494:88, :696:47, :697:47, :703:27
        privilegeMode <= {1'h0, mstatus[8]};	// src/main/scala/nutcore/backend/fu/CSR.scala:213:34, :278:24, :391:30, :696:47, :700:25
      end
      else if (_GEN_7) begin	// src/main/scala/nutcore/backend/fu/CSR.scala:682:15
        mstatus <=
          {mstatus[63:13],
           2'h0,
           mstatus[10:8],
           1'h1,
           mstatus[6:4],
           mstatus[7],
           mstatus[2:0]};	// src/main/scala/nutcore/backend/fu/CSR.scala:193:14, :278:24, :300:59, :494:88, :683:47, :690:27
        privilegeMode <= mstatus[12:11];	// src/main/scala/nutcore/backend/fu/CSR.scala:278:24, :391:30, :683:47
      end
      else if (_GEN_5 & io_in_bits_src2[11:0] == 12'h300) begin	// src/main/scala/nutcore/backend/fu/CSR.scala:478:18, :500:51, src/main/scala/utils/LookupTree.scala:24:34, src/main/scala/utils/RegMap.scala:50:{56,65}
        automatic logic [62:0] _mstatus_T_7;	// src/main/scala/utils/BitUtils.scala:34:26
        _mstatus_T_7 =
          {40'h0, wdata[22:1] & 22'h3F3FD5, 1'h0} | mstatus[62:0] & 63'h7FFFFFFFFF818055;	// src/main/scala/chisel3/util/Mux.scala:30:73, src/main/scala/nutcore/backend/fu/CSR.scala:213:34, :278:24, :301:23, src/main/scala/utils/BitUtils.scala:34:{14,26,37,39}
        mstatus <= {&(_mstatus_T_7[14:13]), _mstatus_T_7};	// src/main/scala/nutcore/backend/fu/CSR.scala:278:24, :316:47, :317:{25,40}, src/main/scala/utils/BitUtils.scala:34:26
      end
      else if (_GEN_5 & io_in_bits_src2[11:0] == 12'h100) begin	// src/main/scala/nutcore/backend/fu/CSR.scala:478:18, :500:51, src/main/scala/utils/LookupTree.scala:24:34, src/main/scala/utils/RegMap.scala:50:{56,65}
        automatic logic [62:0] _mstatus_T_3;	// src/main/scala/utils/BitUtils.scala:34:26
        _mstatus_T_3 =
          {43'h0, wdata[19:1] & 19'h63091, 1'h0} | mstatus[62:0] & 63'h7FFFFFFFFFF39EDD;	// src/main/scala/chisel3/util/Mux.scala:30:73, src/main/scala/nutcore/backend/fu/CSR.scala:213:34, :278:24, :338:23, src/main/scala/utils/BitUtils.scala:34:{14,26,37,39}
        mstatus <= {&(_mstatus_T_3[14:13]), _mstatus_T_3};	// src/main/scala/nutcore/backend/fu/CSR.scala:278:24, :316:47, :317:{25,40}, src/main/scala/utils/BitUtils.scala:34:26
      end
      if (_GEN_5 & _isMret_T)	// src/main/scala/nutcore/backend/fu/CSR.scala:500:51, src/main/scala/utils/RegMap.scala:50:{56,65}
        medeleg <= wdata & 64'hBBFF | medeleg & 64'hFFFFFFFFFFFF4400;	// src/main/scala/chisel3/util/Mux.scala:30:73, src/main/scala/nutcore/backend/fu/CSR.scala:321:24, src/main/scala/utils/BitUtils.scala:34:{14,26,37,39}
      if (_GEN_5 & io_in_bits_src2[11:0] == 12'h303)	// src/main/scala/nutcore/backend/fu/CSR.scala:478:18, :500:51, src/main/scala/utils/LookupTree.scala:24:34, src/main/scala/utils/RegMap.scala:50:{56,65}
        mideleg <= wdata & 64'h222 | mideleg & 64'hFFFFFFFFFFFFFDDD;	// src/main/scala/chisel3/util/Mux.scala:30:73, src/main/scala/nutcore/backend/fu/CSR.scala:322:24, :356:32, src/main/scala/utils/BitUtils.scala:34:{14,26,37,39}
      if (_GEN_5 & io_in_bits_src2[11:0] == 12'h340)	// src/main/scala/nutcore/backend/fu/CSR.scala:478:18, :500:51, src/main/scala/utils/LookupTree.scala:24:34, src/main/scala/utils/RegMap.scala:50:{56,65}
        mscratch <= wdata;	// src/main/scala/chisel3/util/Mux.scala:30:73, src/main/scala/nutcore/backend/fu/CSR.scala:323:25
      if (_GEN_5 & io_in_bits_src2[11:0] == 12'h3A0)	// src/main/scala/nutcore/backend/fu/CSR.scala:478:18, :500:51, src/main/scala/utils/LookupTree.scala:24:34, src/main/scala/utils/RegMap.scala:50:{56,65}
        pmpcfg0 <= wdata;	// src/main/scala/chisel3/util/Mux.scala:30:73, src/main/scala/nutcore/backend/fu/CSR.scala:325:24
      if (_GEN_5 & io_in_bits_src2[11:0] == 12'h3A1)	// src/main/scala/nutcore/backend/fu/CSR.scala:478:18, :500:51, src/main/scala/utils/LookupTree.scala:24:34, src/main/scala/utils/RegMap.scala:50:{56,65}
        pmpcfg1 <= wdata;	// src/main/scala/chisel3/util/Mux.scala:30:73, src/main/scala/nutcore/backend/fu/CSR.scala:326:24
      if (_GEN_5 & io_in_bits_src2[11:0] == 12'h3A2)	// src/main/scala/nutcore/backend/fu/CSR.scala:478:18, :500:51, src/main/scala/utils/LookupTree.scala:24:34, src/main/scala/utils/RegMap.scala:50:{56,65}
        pmpcfg2 <= wdata;	// src/main/scala/chisel3/util/Mux.scala:30:73, src/main/scala/nutcore/backend/fu/CSR.scala:327:24
      if (_GEN_5 & io_in_bits_src2[11:0] == 12'h3A3)	// src/main/scala/nutcore/backend/fu/CSR.scala:478:18, :500:51, src/main/scala/utils/LookupTree.scala:24:34, src/main/scala/utils/RegMap.scala:50:{56,65}
        pmpcfg3 <= wdata;	// src/main/scala/chisel3/util/Mux.scala:30:73, src/main/scala/nutcore/backend/fu/CSR.scala:328:24
      if (_GEN_5 & io_in_bits_src2[11:0] == 12'h3B0)	// src/main/scala/nutcore/backend/fu/CSR.scala:478:18, :500:51, src/main/scala/utils/LookupTree.scala:24:34, src/main/scala/utils/RegMap.scala:50:{56,65}
        pmpaddr0 <= wdata & 64'h3FFFFFFF | pmpaddr0 & 64'hFFFFFFFFC0000000;	// src/main/scala/chisel3/util/Mux.scala:30:73, src/main/scala/nutcore/backend/fu/CSR.scala:329:25, src/main/scala/utils/BitUtils.scala:34:{14,26,37,39}
      if (_GEN_5 & io_in_bits_src2[11:0] == 12'h3B1)	// src/main/scala/nutcore/backend/fu/CSR.scala:478:18, :500:51, src/main/scala/utils/LookupTree.scala:24:34, src/main/scala/utils/RegMap.scala:50:{56,65}
        pmpaddr1 <= wdata & 64'h3FFFFFFF | pmpaddr1 & 64'hFFFFFFFFC0000000;	// src/main/scala/chisel3/util/Mux.scala:30:73, src/main/scala/nutcore/backend/fu/CSR.scala:330:25, src/main/scala/utils/BitUtils.scala:34:{14,26,37,39}
      if (_GEN_5 & io_in_bits_src2[11:0] == 12'h3B2)	// src/main/scala/nutcore/backend/fu/CSR.scala:478:18, :500:51, src/main/scala/utils/LookupTree.scala:24:34, src/main/scala/utils/RegMap.scala:50:{56,65}
        pmpaddr2 <= wdata & 64'h3FFFFFFF | pmpaddr2 & 64'hFFFFFFFFC0000000;	// src/main/scala/chisel3/util/Mux.scala:30:73, src/main/scala/nutcore/backend/fu/CSR.scala:331:25, src/main/scala/utils/BitUtils.scala:34:{14,26,37,39}
      if (_GEN_5 & io_in_bits_src2[11:0] == 12'h3B3)	// src/main/scala/nutcore/backend/fu/CSR.scala:478:18, :500:51, src/main/scala/utils/LookupTree.scala:24:34, src/main/scala/utils/RegMap.scala:50:{56,65}
        pmpaddr3 <= wdata & 64'h3FFFFFFF | pmpaddr3 & 64'hFFFFFFFFC0000000;	// src/main/scala/chisel3/util/Mux.scala:30:73, src/main/scala/nutcore/backend/fu/CSR.scala:332:25, src/main/scala/utils/BitUtils.scala:34:{14,26,37,39}
      if (_GEN_5 & io_in_bits_src2[11:0] == 12'h105)	// src/main/scala/nutcore/backend/fu/CSR.scala:478:18, :500:51, src/main/scala/utils/LookupTree.scala:24:34, src/main/scala/utils/RegMap.scala:50:{56,65}
        stvec <= wdata;	// src/main/scala/chisel3/util/Mux.scala:30:73, src/main/scala/nutcore/backend/fu/CSR.scala:354:22
      if (_GEN_5 & _resetSatp_T)	// src/main/scala/nutcore/backend/fu/CSR.scala:500:51, src/main/scala/utils/RegMap.scala:50:{56,65}
        satp <= wdata;	// src/main/scala/chisel3/util/Mux.scala:30:73, src/main/scala/nutcore/backend/fu/CSR.scala:359:21
      if (raiseExceptionIntr & delegS) begin	// src/main/scala/nutcore/backend/fu/CSR.scala:656:58, :673:38, :719:29, :723:19, :724:14, src/main/scala/utils/RegMap.scala:50:72
        sepc <= {{25{io_cfIn_pc[38]}}, io_cfIn_pc};	// src/main/scala/nutcore/backend/fu/CSR.scala:360:21, src/main/scala/utils/BitUtils.scala:41:20, :42:{41,46}
        scause <= causeNO;	// src/main/scala/nutcore/backend/fu/CSR.scala:361:23, :653:41
      end
      else begin	// src/main/scala/nutcore/backend/fu/CSR.scala:719:29, :723:19, :724:14, src/main/scala/utils/RegMap.scala:50:72
        if (_GEN_5 & io_in_bits_src2[11:0] == 12'h141)	// src/main/scala/nutcore/backend/fu/CSR.scala:478:18, :500:51, src/main/scala/utils/LookupTree.scala:24:34, src/main/scala/utils/RegMap.scala:50:{56,65}
          sepc <= wdata;	// src/main/scala/chisel3/util/Mux.scala:30:73, src/main/scala/nutcore/backend/fu/CSR.scala:360:21
        if (_GEN_5 & io_in_bits_src2[11:0] == 12'h142)	// src/main/scala/nutcore/backend/fu/CSR.scala:478:18, :500:51, src/main/scala/utils/LookupTree.scala:24:34, src/main/scala/utils/RegMap.scala:50:{56,65}
          scause <= wdata;	// src/main/scala/chisel3/util/Mux.scala:30:73, src/main/scala/nutcore/backend/fu/CSR.scala:361:23
      end
      if (_GEN_5 & io_in_bits_src2[11:0] == 12'h140)	// src/main/scala/nutcore/backend/fu/CSR.scala:478:18, :500:51, src/main/scala/utils/LookupTree.scala:24:34, src/main/scala/utils/RegMap.scala:50:{56,65}
        sscratch <= wdata;	// src/main/scala/chisel3/util/Mux.scala:30:73, src/main/scala/nutcore/backend/fu/CSR.scala:363:25
      if (_GEN_5 & io_in_bits_src2[11:0] == 12'h106)	// src/main/scala/nutcore/backend/fu/CSR.scala:478:18, :500:51, src/main/scala/utils/LookupTree.scala:24:34, src/main/scala/utils/RegMap.scala:50:{56,65}
        scounteren <= wdata;	// src/main/scala/chisel3/util/Mux.scala:30:73, src/main/scala/nutcore/backend/fu/CSR.scala:364:27
      lr <= ~(_GEN_3 | _GEN_7) & (setLr__bore ? setLrVal__bore : lr);	// src/main/scala/nutcore/backend/fu/CSR.scala:377:19, :385:14, :386:8, :682:{15,26}, :691:8, :695:{15,26}, :704:8
      if (setLr__bore)
        lrAddr <= setLrAddr__bore;	// src/main/scala/nutcore/backend/fu/CSR.scala:378:23
      if (_GEN)	// src/main/scala/nutcore/backend/fu/CSR.scala:876:33
        perfCnts_0 <= perfCnts_0 + 64'h1;	// src/main/scala/nutcore/backend/fu/CSR.scala:396:47, :859:71
      else if (_GEN_5 & io_in_bits_src2[11:0] == 12'hB00)	// src/main/scala/nutcore/backend/fu/CSR.scala:478:18, :500:51, src/main/scala/utils/LookupTree.scala:24:34, src/main/scala/utils/RegMap.scala:50:{56,65}
        perfCnts_0 <= wdata;	// src/main/scala/chisel3/util/Mux.scala:30:73, src/main/scala/nutcore/backend/fu/CSR.scala:396:47
      if (_GEN_5 & io_in_bits_src2[11:0] == 12'hB01)	// src/main/scala/nutcore/backend/fu/CSR.scala:478:18, :500:51, src/main/scala/utils/LookupTree.scala:24:34, src/main/scala/utils/RegMap.scala:50:{56,65}
        perfCnts_1 <= wdata;	// src/main/scala/chisel3/util/Mux.scala:30:73, src/main/scala/nutcore/backend/fu/CSR.scala:396:47
      if (perfCntCond_3__bore)
        perfCnts_2 <= perfCnts_2 + 64'h2;	// src/main/scala/nutcore/backend/fu/CSR.scala:396:47, :869:86
      else if (perfCntCond_2__bore)
        perfCnts_2 <= perfCnts_2 + 64'h1;	// src/main/scala/nutcore/backend/fu/CSR.scala:396:47, :859:71
      else if (_GEN_5 & io_in_bits_src2[11:0] == 12'hB02)	// src/main/scala/nutcore/backend/fu/CSR.scala:478:18, :500:51, src/main/scala/utils/LookupTree.scala:24:34, src/main/scala/utils/RegMap.scala:50:{56,65}
        perfCnts_2 <= wdata;	// src/main/scala/chisel3/util/Mux.scala:30:73, src/main/scala/nutcore/backend/fu/CSR.scala:396:47
    end
    if (raiseExceptionIntr & delegS & tvalWen)	// src/main/scala/nutcore/backend/fu/CSR.scala:585:67, :656:58, :673:38, :674:130, :719:29, :723:19, :730:{20,27}
      stval <= 64'h0;	// src/main/scala/nutcore/backend/fu/CSR.scala:258:20, :362:18
    else if (~_GEN_6 | (&privilegeMode)) begin	// src/main/scala/nutcore/backend/fu/CSR.scala:391:30, :585:{46,67}, :587:{24,34}, src/main/scala/utils/RegMap.scala:50:72
      if (_GEN_5 & io_in_bits_src2[11:0] == 12'h143)	// src/main/scala/nutcore/backend/fu/CSR.scala:478:18, :500:51, src/main/scala/utils/LookupTree.scala:24:34, src/main/scala/utils/RegMap.scala:50:{56,65}
        stval <= wdata;	// src/main/scala/chisel3/util/Mux.scala:30:73, src/main/scala/nutcore/backend/fu/CSR.scala:362:18
    end
    else	// src/main/scala/nutcore/backend/fu/CSR.scala:585:67, :587:34, src/main/scala/utils/RegMap.scala:50:72
      stval <= tval;	// src/main/scala/nutcore/backend/fu/CSR.scala:362:18, :586:19
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/nutcore/backend/fu/CSR.scala:192:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/nutcore/backend/fu/CSR.scala:192:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/nutcore/backend/fu/CSR.scala:192:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// src/main/scala/nutcore/backend/fu/CSR.scala:192:7
      automatic logic [31:0] _RANDOM[0:74];	// src/main/scala/nutcore/backend/fu/CSR.scala:192:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/nutcore/backend/fu/CSR.scala:192:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/nutcore/backend/fu/CSR.scala:192:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/nutcore/backend/fu/CSR.scala:192:7
        for (logic [6:0] i = 7'h0; i < 7'h4B; i += 7'h1) begin
          _RANDOM[i] = `RANDOM;	// src/main/scala/nutcore/backend/fu/CSR.scala:192:7
        end	// src/main/scala/nutcore/backend/fu/CSR.scala:192:7
        mtvec = {_RANDOM[7'h2], _RANDOM[7'h3]};	// src/main/scala/nutcore/backend/fu/CSR.scala:192:7, :252:22
        mcounteren = {_RANDOM[7'h4], _RANDOM[7'h5]};	// src/main/scala/nutcore/backend/fu/CSR.scala:192:7, :253:27
        mcause = {_RANDOM[7'h6], _RANDOM[7'h7]};	// src/main/scala/nutcore/backend/fu/CSR.scala:192:7, :254:23
        mtval = {_RANDOM[7'h8], _RANDOM[7'h9]};	// src/main/scala/nutcore/backend/fu/CSR.scala:192:7, :255:22
        mepc = {_RANDOM[7'hA], _RANDOM[7'hB]};	// src/main/scala/nutcore/backend/fu/CSR.scala:192:7, :256:21
        mie = {_RANDOM[7'hC], _RANDOM[7'hD]};	// src/main/scala/nutcore/backend/fu/CSR.scala:192:7, :258:20
        mipReg = {_RANDOM[7'hE], _RANDOM[7'hF]};	// src/main/scala/nutcore/backend/fu/CSR.scala:192:7, :260:24
        misa = {_RANDOM[7'h10], _RANDOM[7'h11]};	// src/main/scala/nutcore/backend/fu/CSR.scala:192:7, :270:21
        mstatus = {_RANDOM[7'h1A], _RANDOM[7'h1B]};	// src/main/scala/nutcore/backend/fu/CSR.scala:192:7, :278:24
        medeleg = {_RANDOM[7'h1C], _RANDOM[7'h1D]};	// src/main/scala/nutcore/backend/fu/CSR.scala:192:7, :321:24
        mideleg = {_RANDOM[7'h1E], _RANDOM[7'h1F]};	// src/main/scala/nutcore/backend/fu/CSR.scala:192:7, :322:24
        mscratch = {_RANDOM[7'h20], _RANDOM[7'h21]};	// src/main/scala/nutcore/backend/fu/CSR.scala:192:7, :323:25
        pmpcfg0 = {_RANDOM[7'h22], _RANDOM[7'h23]};	// src/main/scala/nutcore/backend/fu/CSR.scala:192:7, :325:24
        pmpcfg1 = {_RANDOM[7'h24], _RANDOM[7'h25]};	// src/main/scala/nutcore/backend/fu/CSR.scala:192:7, :326:24
        pmpcfg2 = {_RANDOM[7'h26], _RANDOM[7'h27]};	// src/main/scala/nutcore/backend/fu/CSR.scala:192:7, :327:24
        pmpcfg3 = {_RANDOM[7'h28], _RANDOM[7'h29]};	// src/main/scala/nutcore/backend/fu/CSR.scala:192:7, :328:24
        pmpaddr0 = {_RANDOM[7'h2A], _RANDOM[7'h2B]};	// src/main/scala/nutcore/backend/fu/CSR.scala:192:7, :329:25
        pmpaddr1 = {_RANDOM[7'h2C], _RANDOM[7'h2D]};	// src/main/scala/nutcore/backend/fu/CSR.scala:192:7, :330:25
        pmpaddr2 = {_RANDOM[7'h2E], _RANDOM[7'h2F]};	// src/main/scala/nutcore/backend/fu/CSR.scala:192:7, :331:25
        pmpaddr3 = {_RANDOM[7'h30], _RANDOM[7'h31]};	// src/main/scala/nutcore/backend/fu/CSR.scala:192:7, :332:25
        stvec = {_RANDOM[7'h32], _RANDOM[7'h33]};	// src/main/scala/nutcore/backend/fu/CSR.scala:192:7, :354:22
        satp = {_RANDOM[7'h34], _RANDOM[7'h35]};	// src/main/scala/nutcore/backend/fu/CSR.scala:192:7, :359:21
        sepc = {_RANDOM[7'h36], _RANDOM[7'h37]};	// src/main/scala/nutcore/backend/fu/CSR.scala:192:7, :360:21
        scause = {_RANDOM[7'h38], _RANDOM[7'h39]};	// src/main/scala/nutcore/backend/fu/CSR.scala:192:7, :361:23
        stval = {_RANDOM[7'h3A], _RANDOM[7'h3B]};	// src/main/scala/nutcore/backend/fu/CSR.scala:192:7, :362:18
        sscratch = {_RANDOM[7'h3C], _RANDOM[7'h3D]};	// src/main/scala/nutcore/backend/fu/CSR.scala:192:7, :363:25
        scounteren = {_RANDOM[7'h3E], _RANDOM[7'h3F]};	// src/main/scala/nutcore/backend/fu/CSR.scala:192:7, :364:27
        lr = _RANDOM[7'h42][0];	// src/main/scala/nutcore/backend/fu/CSR.scala:192:7, :377:19
        lrAddr = {_RANDOM[7'h42][31:1], _RANDOM[7'h43], _RANDOM[7'h44][0]};	// src/main/scala/nutcore/backend/fu/CSR.scala:192:7, :377:19, :378:23
        privilegeMode = _RANDOM[7'h44][2:1];	// src/main/scala/nutcore/backend/fu/CSR.scala:192:7, :378:23, :391:30
        perfCnts_0 = {_RANDOM[7'h44][31:3], _RANDOM[7'h45], _RANDOM[7'h46][2:0]};	// src/main/scala/nutcore/backend/fu/CSR.scala:192:7, :378:23, :396:47
        perfCnts_1 = {_RANDOM[7'h46][31:3], _RANDOM[7'h47], _RANDOM[7'h48][2:0]};	// src/main/scala/nutcore/backend/fu/CSR.scala:192:7, :396:47
        perfCnts_2 = {_RANDOM[7'h48][31:3], _RANDOM[7'h49], _RANDOM[7'h4A][2:0]};	// src/main/scala/nutcore/backend/fu/CSR.scala:192:7, :396:47
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/nutcore/backend/fu/CSR.scala:192:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/nutcore/backend/fu/CSR.scala:192:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_out_valid = io_in_valid;	// src/main/scala/nutcore/backend/fu/CSR.scala:192:7
  assign io_out_bits = _rdata_T_146;	// src/main/scala/chisel3/util/Mux.scala:30:73, src/main/scala/nutcore/backend/fu/CSR.scala:192:7
  assign io_redirect_target =
    resetSatp ? io_cfIn_pc + 39'h4 : raiseExceptionIntr ? _trapTarget_T : retTarget;	// src/main/scala/nutcore/backend/fu/CSR.scala:192:7, :502:35, :656:58, :661:{28,51,61}, :677:20, :695:26, :708:26, :716:15
  assign io_redirect_valid =
    io_in_valid & _io_redirect_valid_T | raiseExceptionIntr | resetSatp;	// src/main/scala/nutcore/backend/fu/CSR.scala:192:7, :502:35, :515:46, :656:58, :659:{31,80}
  assign io_imemMMU_privilegeMode = privilegeMode;	// src/main/scala/nutcore/backend/fu/CSR.scala:192:7, :391:30
  assign io_dmemMMU_privilegeMode = mstatus[17] ? mstatus[12:11] : privilegeMode;	// src/main/scala/nutcore/backend/fu/CSR.scala:192:7, :278:24, :314:39, :391:30, :551:34
  assign io_dmemMMU_status_sum = mstatus[18];	// src/main/scala/nutcore/backend/fu/CSR.scala:192:7, :278:24, :314:39
  assign io_dmemMMU_status_mxr = mstatus[19];	// src/main/scala/nutcore/backend/fu/CSR.scala:192:7, :278:24, :314:39
  assign io_wenFix = |_GEN_2;	// src/main/scala/nutcore/backend/fu/CSR.scala:192:7, :648:50, :649:42
  assign lr__bore = lr;	// src/main/scala/nutcore/backend/fu/CSR.scala:192:7, :377:19
  assign satp__bore = satp;	// src/main/scala/nutcore/backend/fu/CSR.scala:192:7, :359:21
  assign satp__bore_0 = satp;	// src/main/scala/nutcore/backend/fu/CSR.scala:192:7, :359:21
  assign perfCnts_2__bore = perfCnts_2;	// src/main/scala/nutcore/backend/fu/CSR.scala:192:7, :396:47
  assign lrAddr__bore = lrAddr;	// src/main/scala/nutcore/backend/fu/CSR.scala:192:7, :378:23
  assign _WIRE__bore = _GEN_1;	// src/main/scala/nutcore/backend/fu/CSR.scala:192:7, :628:33
  assign _WIRE__bore_0 = _GEN_1;	// src/main/scala/nutcore/backend/fu/CSR.scala:192:7, :628:33
endmodule

