// Generated by CIRCT firtool-1.62.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for prints and assertions.

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module EXU(	// src/main/scala/nutcore/backend/seq/EXU.scala:28:7
  input         clock,	// src/main/scala/nutcore/backend/seq/EXU.scala:28:7
                reset,	// src/main/scala/nutcore/backend/seq/EXU.scala:28:7
  output        io_in_ready,	// src/main/scala/nutcore/backend/seq/EXU.scala:29:14
  input         io_in_valid,	// src/main/scala/nutcore/backend/seq/EXU.scala:29:14
  input  [63:0] io_in_bits_cf_instr,	// src/main/scala/nutcore/backend/seq/EXU.scala:29:14
  input  [38:0] io_in_bits_cf_pc,	// src/main/scala/nutcore/backend/seq/EXU.scala:29:14
                io_in_bits_cf_pnpc,	// src/main/scala/nutcore/backend/seq/EXU.scala:29:14
  input         io_in_bits_cf_exceptionVec_0,	// src/main/scala/nutcore/backend/seq/EXU.scala:29:14
                io_in_bits_cf_exceptionVec_1,	// src/main/scala/nutcore/backend/seq/EXU.scala:29:14
                io_in_bits_cf_exceptionVec_2,	// src/main/scala/nutcore/backend/seq/EXU.scala:29:14
                io_in_bits_cf_exceptionVec_3,	// src/main/scala/nutcore/backend/seq/EXU.scala:29:14
                io_in_bits_cf_exceptionVec_5,	// src/main/scala/nutcore/backend/seq/EXU.scala:29:14
                io_in_bits_cf_exceptionVec_7,	// src/main/scala/nutcore/backend/seq/EXU.scala:29:14
                io_in_bits_cf_exceptionVec_8,	// src/main/scala/nutcore/backend/seq/EXU.scala:29:14
                io_in_bits_cf_exceptionVec_9,	// src/main/scala/nutcore/backend/seq/EXU.scala:29:14
                io_in_bits_cf_exceptionVec_10,	// src/main/scala/nutcore/backend/seq/EXU.scala:29:14
                io_in_bits_cf_exceptionVec_11,	// src/main/scala/nutcore/backend/seq/EXU.scala:29:14
                io_in_bits_cf_exceptionVec_12,	// src/main/scala/nutcore/backend/seq/EXU.scala:29:14
                io_in_bits_cf_exceptionVec_13,	// src/main/scala/nutcore/backend/seq/EXU.scala:29:14
                io_in_bits_cf_exceptionVec_14,	// src/main/scala/nutcore/backend/seq/EXU.scala:29:14
                io_in_bits_cf_exceptionVec_15,	// src/main/scala/nutcore/backend/seq/EXU.scala:29:14
                io_in_bits_cf_intrVec_0,	// src/main/scala/nutcore/backend/seq/EXU.scala:29:14
                io_in_bits_cf_intrVec_1,	// src/main/scala/nutcore/backend/seq/EXU.scala:29:14
                io_in_bits_cf_intrVec_2,	// src/main/scala/nutcore/backend/seq/EXU.scala:29:14
                io_in_bits_cf_intrVec_3,	// src/main/scala/nutcore/backend/seq/EXU.scala:29:14
                io_in_bits_cf_intrVec_4,	// src/main/scala/nutcore/backend/seq/EXU.scala:29:14
                io_in_bits_cf_intrVec_5,	// src/main/scala/nutcore/backend/seq/EXU.scala:29:14
                io_in_bits_cf_intrVec_6,	// src/main/scala/nutcore/backend/seq/EXU.scala:29:14
                io_in_bits_cf_intrVec_7,	// src/main/scala/nutcore/backend/seq/EXU.scala:29:14
                io_in_bits_cf_intrVec_8,	// src/main/scala/nutcore/backend/seq/EXU.scala:29:14
                io_in_bits_cf_intrVec_9,	// src/main/scala/nutcore/backend/seq/EXU.scala:29:14
                io_in_bits_cf_intrVec_10,	// src/main/scala/nutcore/backend/seq/EXU.scala:29:14
                io_in_bits_cf_intrVec_11,	// src/main/scala/nutcore/backend/seq/EXU.scala:29:14
  input  [3:0]  io_in_bits_cf_brIdx,	// src/main/scala/nutcore/backend/seq/EXU.scala:29:14
  input         io_in_bits_cf_crossPageIPFFix,	// src/main/scala/nutcore/backend/seq/EXU.scala:29:14
  input  [2:0]  io_in_bits_ctrl_fuType,	// src/main/scala/nutcore/backend/seq/EXU.scala:29:14
  input  [6:0]  io_in_bits_ctrl_fuOpType,	// src/main/scala/nutcore/backend/seq/EXU.scala:29:14
  input         io_in_bits_ctrl_rfWen,	// src/main/scala/nutcore/backend/seq/EXU.scala:29:14
  input  [4:0]  io_in_bits_ctrl_rfDest,	// src/main/scala/nutcore/backend/seq/EXU.scala:29:14
  input  [63:0] io_in_bits_data_src1,	// src/main/scala/nutcore/backend/seq/EXU.scala:29:14
                io_in_bits_data_src2,	// src/main/scala/nutcore/backend/seq/EXU.scala:29:14
                io_in_bits_data_imm,	// src/main/scala/nutcore/backend/seq/EXU.scala:29:14
  output        io_out_valid,	// src/main/scala/nutcore/backend/seq/EXU.scala:29:14
  output [38:0] io_out_bits_decode_cf_pc,	// src/main/scala/nutcore/backend/seq/EXU.scala:29:14
                io_out_bits_decode_cf_redirect_target,	// src/main/scala/nutcore/backend/seq/EXU.scala:29:14
  output        io_out_bits_decode_cf_redirect_valid,	// src/main/scala/nutcore/backend/seq/EXU.scala:29:14
  output [2:0]  io_out_bits_decode_ctrl_fuType,	// src/main/scala/nutcore/backend/seq/EXU.scala:29:14
  output        io_out_bits_decode_ctrl_rfWen,	// src/main/scala/nutcore/backend/seq/EXU.scala:29:14
  output [4:0]  io_out_bits_decode_ctrl_rfDest,	// src/main/scala/nutcore/backend/seq/EXU.scala:29:14
  output [63:0] io_out_bits_commits_0,	// src/main/scala/nutcore/backend/seq/EXU.scala:29:14
                io_out_bits_commits_1,	// src/main/scala/nutcore/backend/seq/EXU.scala:29:14
                io_out_bits_commits_2,	// src/main/scala/nutcore/backend/seq/EXU.scala:29:14
                io_out_bits_commits_3,	// src/main/scala/nutcore/backend/seq/EXU.scala:29:14
  input         io_flush,	// src/main/scala/nutcore/backend/seq/EXU.scala:29:14
                io_dmem_req_ready,	// src/main/scala/nutcore/backend/seq/EXU.scala:29:14
  output        io_dmem_req_valid,	// src/main/scala/nutcore/backend/seq/EXU.scala:29:14
  output [38:0] io_dmem_req_bits_addr,	// src/main/scala/nutcore/backend/seq/EXU.scala:29:14
  output [2:0]  io_dmem_req_bits_size,	// src/main/scala/nutcore/backend/seq/EXU.scala:29:14
  output [3:0]  io_dmem_req_bits_cmd,	// src/main/scala/nutcore/backend/seq/EXU.scala:29:14
  output [7:0]  io_dmem_req_bits_wmask,	// src/main/scala/nutcore/backend/seq/EXU.scala:29:14
  output [63:0] io_dmem_req_bits_wdata,	// src/main/scala/nutcore/backend/seq/EXU.scala:29:14
  input         io_dmem_resp_valid,	// src/main/scala/nutcore/backend/seq/EXU.scala:29:14
  input  [63:0] io_dmem_resp_bits_rdata,	// src/main/scala/nutcore/backend/seq/EXU.scala:29:14
  output        io_forward_valid,	// src/main/scala/nutcore/backend/seq/EXU.scala:29:14
                io_forward_wb_rfWen,	// src/main/scala/nutcore/backend/seq/EXU.scala:29:14
  output [4:0]  io_forward_wb_rfDest,	// src/main/scala/nutcore/backend/seq/EXU.scala:29:14
  output [63:0] io_forward_wb_rfData,	// src/main/scala/nutcore/backend/seq/EXU.scala:29:14
  output [2:0]  io_forward_fuType,	// src/main/scala/nutcore/backend/seq/EXU.scala:29:14
  output [1:0]  io_memMMU_imem_privilegeMode,	// src/main/scala/nutcore/backend/seq/EXU.scala:29:14
                io_memMMU_dmem_privilegeMode,	// src/main/scala/nutcore/backend/seq/EXU.scala:29:14
  output        io_memMMU_dmem_status_sum,	// src/main/scala/nutcore/backend/seq/EXU.scala:29:14
                io_memMMU_dmem_status_mxr,	// src/main/scala/nutcore/backend/seq/EXU.scala:29:14
  input         io_memMMU_dmem_loadPF,	// src/main/scala/nutcore/backend/seq/EXU.scala:29:14
                io_memMMU_dmem_storePF,	// src/main/scala/nutcore/backend/seq/EXU.scala:29:14
  input  [38:0] io_memMMU_dmem_addr,	// src/main/scala/nutcore/backend/seq/EXU.scala:29:14
  input         csr_perfCntCond_3__bore,
  output [63:0] csr_satp__bore,
                csr_satp__bore_0,
  input         csr_perfCntCond_2__bore,
  output        alu_REG__bore_valid,
  output [38:0] alu_REG__bore_pc,
  output        alu_REG__bore_isMissPredict,
  output [38:0] alu_REG__bore_actualTarget,
  output        alu_REG__bore_actualTaken,
  output [6:0]  alu_REG__bore_fuOpType,
  output [1:0]  alu_REG__bore_btbType,
  output        alu_REG__bore_isRVC,
  output [63:0] csr_perfCnts_2__bore,
  input         lsu_lsExecUnit_dtlbFinish__bore,
                csr_meip__bore,
  output        mou__WIRE_1__bore,
                mou__WIRE_1__bore_0,
                mou__WIRE_1__bore_1,
                lsu__WIRE__bore,
  input         csr_mtip__bore,
                csr_msip__bore,
  output        mou__WIRE__bore,
                mou__WIRE__bore_0,
  input         lsu_lsExecUnit_dtlbPF__bore,
                lsu_dtlbPF__bore,
                lsu_lsExecUnit_dtlbEnable__bore,
  output [11:0] csr__WIRE__bore,
                csr__WIRE__bore_0
);

  wire        _GEN;	// src/main/scala/nutcore/backend/seq/EXU.scala:130:33
  wire [38:0] _mou_io_redirect_target;	// src/main/scala/nutcore/backend/seq/EXU.scala:82:19
  wire        _mou_io_redirect_valid;	// src/main/scala/nutcore/backend/seq/EXU.scala:82:19
  wire [38:0] _csr_io_redirect_target;	// src/main/scala/nutcore/backend/seq/EXU.scala:68:19
  wire        _csr_io_redirect_valid;	// src/main/scala/nutcore/backend/seq/EXU.scala:68:19
  wire        _csr_io_wenFix;	// src/main/scala/nutcore/backend/seq/EXU.scala:68:19
  wire        _csr_lr__bore;	// src/main/scala/nutcore/backend/seq/EXU.scala:68:19
  wire [63:0] _csr_lrAddr__bore;	// src/main/scala/nutcore/backend/seq/EXU.scala:68:19
  wire        _mdu_io_out_valid;	// src/main/scala/nutcore/backend/seq/EXU.scala:63:19
  wire        _lsu_io_out_valid;	// src/main/scala/nutcore/backend/seq/EXU.scala:54:19
  wire [63:0] _lsu_io_out_bits;	// src/main/scala/nutcore/backend/seq/EXU.scala:54:19
  wire        _lsu_io_dtlbPF;	// src/main/scala/nutcore/backend/seq/EXU.scala:54:19
  wire        _lsu_io_loadAddrMisaligned;	// src/main/scala/nutcore/backend/seq/EXU.scala:54:19
  wire        _lsu_io_storeAddrMisaligned;	// src/main/scala/nutcore/backend/seq/EXU.scala:54:19
  wire        _lsu_setLrVal__bore;	// src/main/scala/nutcore/backend/seq/EXU.scala:54:19
  wire        _lsu_setLr__bore;	// src/main/scala/nutcore/backend/seq/EXU.scala:54:19
  wire [63:0] _lsu_setLrAddr__bore;	// src/main/scala/nutcore/backend/seq/EXU.scala:54:19
  wire [63:0] _lsu_lsExecUnit_io_in_bits_src1__bore;	// src/main/scala/nutcore/backend/seq/EXU.scala:54:19
  wire        _alu_io_out_valid;	// src/main/scala/nutcore/backend/seq/EXU.scala:46:19
  wire [63:0] _alu_io_out_bits;	// src/main/scala/nutcore/backend/seq/EXU.scala:46:19
  wire [38:0] _alu_io_redirect_target;	// src/main/scala/nutcore/backend/seq/EXU.scala:46:19
  wire        _alu_io_redirect_valid;	// src/main/scala/nutcore/backend/seq/EXU.scala:46:19
  wire        fuValids_1 = io_in_bits_ctrl_fuType == 3'h1 & io_in_valid & ~io_flush;	// src/main/scala/nutcore/backend/seq/EXU.scala:44:{57,81,84}
  wire        fuValids_3 = io_in_bits_ctrl_fuType == 3'h3 & io_in_valid & ~io_flush;	// src/main/scala/nutcore/backend/seq/EXU.scala:44:{57,81,84}
  wire        io_out_valid_0 =
    io_in_valid
    & (io_in_bits_ctrl_fuType == 3'h2
         ? _mdu_io_out_valid
         : io_in_bits_ctrl_fuType != 3'h1 | _lsu_io_out_valid);	// src/main/scala/nutcore/backend/seq/EXU.scala:44:57, :54:19, :63:19, :106:{31,59}
  wire        _GEN_0 = _alu_io_out_valid & ~(io_in_bits_ctrl_fuOpType[4]);	// src/main/scala/nutcore/backend/fu/ALU.scala:62:31, src/main/scala/nutcore/backend/seq/EXU.scala:46:19, :126:{33,50,53}
  wire        _GEN_1 = _alu_io_out_valid & io_in_bits_ctrl_fuOpType[4];	// src/main/scala/nutcore/backend/fu/ALU.scala:62:31, src/main/scala/nutcore/backend/seq/EXU.scala:46:19, :127:{33,50}
  ALU alu (	// src/main/scala/nutcore/backend/seq/EXU.scala:46:19
    .clock                   (clock),
    .reset                   (reset),
    .io_in_valid             (io_in_bits_ctrl_fuType == 3'h0 & io_in_valid & ~io_flush),	// src/main/scala/nutcore/backend/seq/EXU.scala:44:{57,81,84}
    .io_in_bits_src1         (io_in_bits_data_src1),
    .io_in_bits_src2         (io_in_bits_data_src2),
    .io_in_bits_func         (io_in_bits_ctrl_fuOpType),
    .io_out_valid            (_alu_io_out_valid),
    .io_out_bits             (_alu_io_out_bits),
    .io_cfIn_instr           (io_in_bits_cf_instr),
    .io_cfIn_pc              (io_in_bits_cf_pc),
    .io_cfIn_pnpc            (io_in_bits_cf_pnpc),
    .io_cfIn_brIdx           (io_in_bits_cf_brIdx),
    .io_redirect_target      (_alu_io_redirect_target),
    .io_redirect_valid       (_alu_io_redirect_valid),
    .io_offset               (io_in_bits_data_imm),
    .REG__bore_valid         (alu_REG__bore_valid),
    .REG__bore_pc            (alu_REG__bore_pc),
    .REG__bore_isMissPredict (alu_REG__bore_isMissPredict),
    .REG__bore_actualTarget  (alu_REG__bore_actualTarget),
    .REG__bore_actualTaken   (alu_REG__bore_actualTaken),
    .REG__bore_fuOpType      (alu_REG__bore_fuOpType),
    .REG__bore_btbType       (alu_REG__bore_btbType),
    .REG__bore_isRVC         (alu_REG__bore_isRVC)
  );
  UnpipelinedLSU lsu (	// src/main/scala/nutcore/backend/seq/EXU.scala:54:19
    .clock                            (clock),
    .reset                            (reset),
    .io_in_valid                      (fuValids_1),	// src/main/scala/nutcore/backend/seq/EXU.scala:44:81
    .io_in_bits_src1                  (io_in_bits_data_src1),
    .io_in_bits_src2                  (io_in_bits_data_imm),
    .io_in_bits_func                  (io_in_bits_ctrl_fuOpType),
    .io_out_valid                     (_lsu_io_out_valid),
    .io_out_bits                      (_lsu_io_out_bits),
    .io_wdata                         (io_in_bits_data_src2),
    .io_instr                         (io_in_bits_cf_instr[31:0]),	// src/main/scala/nutcore/backend/seq/EXU.scala:58:16
    .io_dmem_req_ready                (io_dmem_req_ready),
    .io_dmem_req_valid                (io_dmem_req_valid),
    .io_dmem_req_bits_addr            (io_dmem_req_bits_addr),
    .io_dmem_req_bits_size            (io_dmem_req_bits_size),
    .io_dmem_req_bits_cmd             (io_dmem_req_bits_cmd),
    .io_dmem_req_bits_wmask           (io_dmem_req_bits_wmask),
    .io_dmem_req_bits_wdata           (io_dmem_req_bits_wdata),
    .io_dmem_resp_valid               (io_dmem_resp_valid),
    .io_dmem_resp_bits_rdata          (io_dmem_resp_bits_rdata),
    .io_dtlbPF                        (_lsu_io_dtlbPF),
    .io_loadAddrMisaligned            (_lsu_io_loadAddrMisaligned),
    .io_storeAddrMisaligned           (_lsu_io_storeAddrMisaligned),
    .setLrVal__bore                   (_lsu_setLrVal__bore),
    .setLr__bore                      (_lsu_setLr__bore),
    .lr__bore                         (_csr_lr__bore),	// src/main/scala/nutcore/backend/seq/EXU.scala:68:19
    .setLrAddr__bore                  (_lsu_setLrAddr__bore),
    .lsExecUnit_dtlbFinish__bore      (lsu_lsExecUnit_dtlbFinish__bore),
    ._WIRE__bore                      (lsu__WIRE__bore),
    .lsExecUnit_dtlbPF__bore          (lsu_lsExecUnit_dtlbPF__bore),
    .dtlbPF__bore                     (lsu_dtlbPF__bore),
    .lsExecUnit_dtlbEnable__bore      (lsu_lsExecUnit_dtlbEnable__bore),
    .lrAddr__bore                     (_csr_lrAddr__bore),	// src/main/scala/nutcore/backend/seq/EXU.scala:68:19
    .lsExecUnit_io_in_bits_src1__bore (_lsu_lsExecUnit_io_in_bits_src1__bore)
  );
  wire        _GEN_2;	// src/main/scala/nutcore/backend/seq/EXU.scala:128:33
  assign _GEN_2 = _lsu_io_out_valid;	// src/main/scala/nutcore/backend/seq/EXU.scala:54:19, :128:33
  MDU mdu (	// src/main/scala/nutcore/backend/seq/EXU.scala:63:19
    .clock           (clock),
    .reset           (reset),
    .io_in_valid     (io_in_bits_ctrl_fuType == 3'h2 & io_in_valid & ~io_flush),	// src/main/scala/nutcore/backend/seq/EXU.scala:44:{57,81,84}
    .io_in_bits_src1 (io_in_bits_data_src1),
    .io_in_bits_src2 (io_in_bits_data_src2),
    .io_in_bits_func (io_in_bits_ctrl_fuOpType),
    .io_out_valid    (_mdu_io_out_valid),
    .io_out_bits     (io_out_bits_commits_2)
  );
  wire        _GEN_3;	// src/main/scala/nutcore/backend/seq/EXU.scala:129:33
  assign _GEN_3 = _mdu_io_out_valid;	// src/main/scala/nutcore/backend/seq/EXU.scala:63:19, :129:33
  CSR csr (	// src/main/scala/nutcore/backend/seq/EXU.scala:68:19
    .clock                    (clock),
    .reset                    (reset),
    .io_in_valid              (fuValids_3),	// src/main/scala/nutcore/backend/seq/EXU.scala:44:81
    .io_in_bits_src1          (io_in_bits_data_src1),
    .io_in_bits_src2          (io_in_bits_data_src2),
    .io_in_bits_func          (io_in_bits_ctrl_fuOpType),
    .io_out_valid             (_GEN),
    .io_out_bits              (io_out_bits_commits_3),
    .io_cfIn_instr            (io_in_bits_cf_instr),
    .io_cfIn_pc               (io_in_bits_cf_pc),
    .io_cfIn_exceptionVec_0   (io_in_bits_cf_exceptionVec_0),
    .io_cfIn_exceptionVec_1   (io_in_bits_cf_exceptionVec_1),
    .io_cfIn_exceptionVec_2   (io_in_bits_cf_exceptionVec_2),
    .io_cfIn_exceptionVec_3   (io_in_bits_cf_exceptionVec_3),
    .io_cfIn_exceptionVec_4   (_lsu_io_loadAddrMisaligned),	// src/main/scala/nutcore/backend/seq/EXU.scala:54:19
    .io_cfIn_exceptionVec_5   (io_in_bits_cf_exceptionVec_5),
    .io_cfIn_exceptionVec_6   (_lsu_io_storeAddrMisaligned),	// src/main/scala/nutcore/backend/seq/EXU.scala:54:19
    .io_cfIn_exceptionVec_7   (io_in_bits_cf_exceptionVec_7),
    .io_cfIn_exceptionVec_8   (io_in_bits_cf_exceptionVec_8),
    .io_cfIn_exceptionVec_9   (io_in_bits_cf_exceptionVec_9),
    .io_cfIn_exceptionVec_10  (io_in_bits_cf_exceptionVec_10),
    .io_cfIn_exceptionVec_11  (io_in_bits_cf_exceptionVec_11),
    .io_cfIn_exceptionVec_12  (io_in_bits_cf_exceptionVec_12),
    .io_cfIn_exceptionVec_13  (io_in_bits_cf_exceptionVec_13),
    .io_cfIn_exceptionVec_14  (io_in_bits_cf_exceptionVec_14),
    .io_cfIn_exceptionVec_15  (io_in_bits_cf_exceptionVec_15),
    .io_cfIn_intrVec_0        (io_in_bits_cf_intrVec_0),
    .io_cfIn_intrVec_1        (io_in_bits_cf_intrVec_1),
    .io_cfIn_intrVec_2        (io_in_bits_cf_intrVec_2),
    .io_cfIn_intrVec_3        (io_in_bits_cf_intrVec_3),
    .io_cfIn_intrVec_4        (io_in_bits_cf_intrVec_4),
    .io_cfIn_intrVec_5        (io_in_bits_cf_intrVec_5),
    .io_cfIn_intrVec_6        (io_in_bits_cf_intrVec_6),
    .io_cfIn_intrVec_7        (io_in_bits_cf_intrVec_7),
    .io_cfIn_intrVec_8        (io_in_bits_cf_intrVec_8),
    .io_cfIn_intrVec_9        (io_in_bits_cf_intrVec_9),
    .io_cfIn_intrVec_10       (io_in_bits_cf_intrVec_10),
    .io_cfIn_intrVec_11       (io_in_bits_cf_intrVec_11),
    .io_cfIn_crossPageIPFFix  (io_in_bits_cf_crossPageIPFFix),
    .io_redirect_target       (_csr_io_redirect_target),
    .io_redirect_valid        (_csr_io_redirect_valid),
    .io_instrValid            (io_in_valid & ~io_flush),	// src/main/scala/nutcore/backend/seq/EXU.scala:44:84, :73:36
    .io_imemMMU_privilegeMode (io_memMMU_imem_privilegeMode),
    .io_dmemMMU_privilegeMode (io_memMMU_dmem_privilegeMode),
    .io_dmemMMU_status_sum    (io_memMMU_dmem_status_sum),
    .io_dmemMMU_status_mxr    (io_memMMU_dmem_status_mxr),
    .io_dmemMMU_loadPF        (io_memMMU_dmem_loadPF),
    .io_dmemMMU_storePF       (io_memMMU_dmem_storePF),
    .io_dmemMMU_addr          (io_memMMU_dmem_addr),
    .io_wenFix                (_csr_io_wenFix),
    .setLrVal__bore           (_lsu_setLrVal__bore),	// src/main/scala/nutcore/backend/seq/EXU.scala:54:19
    .setLr__bore              (_lsu_setLr__bore),	// src/main/scala/nutcore/backend/seq/EXU.scala:54:19
    .lr__bore                 (_csr_lr__bore),
    .perfCntCond_3__bore      (csr_perfCntCond_3__bore),
    .satp__bore               (csr_satp__bore),
    .satp__bore_0             (csr_satp__bore_0),
    .perfCntCond_2__bore      (csr_perfCntCond_2__bore),
    .setLrAddr__bore          (_lsu_setLrAddr__bore),	// src/main/scala/nutcore/backend/seq/EXU.scala:54:19
    .perfCnts_2__bore         (csr_perfCnts_2__bore),
    .meip__bore               (csr_meip__bore),
    .mtip__bore               (csr_mtip__bore),
    .msip__bore               (csr_msip__bore),
    .lrAddr__bore             (_csr_lrAddr__bore),
    ._WIRE__bore              (csr__WIRE__bore),
    ._WIRE__bore_0            (csr__WIRE__bore_0),
    .lsuAddr__bore            (_lsu_lsExecUnit_io_in_bits_src1__bore)	// src/main/scala/nutcore/backend/seq/EXU.scala:54:19
  );
  MOU mou (	// src/main/scala/nutcore/backend/seq/EXU.scala:82:19
    .io_in_valid        (io_in_bits_ctrl_fuType == 3'h4 & io_in_valid & ~io_flush),	// src/main/scala/nutcore/backend/seq/EXU.scala:44:{57,81,84}
    .io_in_bits_func    (io_in_bits_ctrl_fuOpType),
    .io_cfIn_pc         (io_in_bits_cf_pc),
    .io_redirect_target (_mou_io_redirect_target),
    .io_redirect_valid  (_mou_io_redirect_valid),
    ._WIRE_1__bore      (mou__WIRE_1__bore),
    ._WIRE_1__bore_0    (mou__WIRE_1__bore_0),
    ._WIRE_1__bore_1    (mou__WIRE_1__bore_1),
    ._WIRE__bore        (mou__WIRE__bore),
    ._WIRE__bore_0      (mou__WIRE__bore_0)
  );
  assign io_in_ready = ~io_in_valid | io_out_valid_0;	// src/main/scala/nutcore/backend/seq/EXU.scala:28:7, :106:31, :117:{18,31}
  assign io_out_valid = io_out_valid_0;	// src/main/scala/nutcore/backend/seq/EXU.scala:28:7, :106:31
  assign io_out_bits_decode_cf_pc = io_in_bits_cf_pc;	// src/main/scala/nutcore/backend/seq/EXU.scala:28:7
  assign io_out_bits_decode_cf_redirect_target =
    _mou_io_redirect_valid
      ? _mou_io_redirect_target
      : _csr_io_redirect_valid ? _csr_io_redirect_target : _alu_io_redirect_target;	// src/main/scala/nutcore/backend/seq/EXU.scala:28:7, :46:19, :68:19, :82:19, :99:8, :100:10
  assign io_out_bits_decode_cf_redirect_valid =
    _mou_io_redirect_valid
      ? _mou_io_redirect_valid
      : _csr_io_redirect_valid ? _csr_io_redirect_valid : _alu_io_redirect_valid;	// src/main/scala/nutcore/backend/seq/EXU.scala:28:7, :46:19, :68:19, :82:19, :99:8, :100:10
  assign io_out_bits_decode_ctrl_fuType = io_in_bits_ctrl_fuType;	// src/main/scala/nutcore/backend/seq/EXU.scala:28:7
  assign io_out_bits_decode_ctrl_rfWen =
    io_in_bits_ctrl_rfWen
    & (~_lsu_io_dtlbPF & ~_lsu_io_loadAddrMisaligned & ~_lsu_io_storeAddrMisaligned
       | ~fuValids_1) & ~(_csr_io_wenFix & fuValids_3);	// src/main/scala/nutcore/backend/seq/EXU.scala:28:7, :44:81, :54:19, :68:19, :90:{28,41,68,71,99,102,125,128,144}
  assign io_out_bits_decode_ctrl_rfDest = io_in_bits_ctrl_rfDest;	// src/main/scala/nutcore/backend/seq/EXU.scala:28:7
  assign io_out_bits_commits_0 = _alu_io_out_bits;	// src/main/scala/nutcore/backend/seq/EXU.scala:28:7, :46:19
  assign io_out_bits_commits_1 = _lsu_io_out_bits;	// src/main/scala/nutcore/backend/seq/EXU.scala:28:7, :54:19
  assign io_forward_valid = io_in_valid;	// src/main/scala/nutcore/backend/seq/EXU.scala:28:7
  assign io_forward_wb_rfWen = io_in_bits_ctrl_rfWen;	// src/main/scala/nutcore/backend/seq/EXU.scala:28:7
  assign io_forward_wb_rfDest = io_in_bits_ctrl_rfDest;	// src/main/scala/nutcore/backend/seq/EXU.scala:28:7
  assign io_forward_wb_rfData = _alu_io_out_valid ? _alu_io_out_bits : _lsu_io_out_bits;	// src/main/scala/nutcore/backend/seq/EXU.scala:28:7, :46:19, :54:19, :122:30
  assign io_forward_fuType = io_in_bits_ctrl_fuType;	// src/main/scala/nutcore/backend/seq/EXU.scala:28:7
endmodule

